### ISSUE TITLE
nnMaxBatchSize in Config Using Standalone KataGo

### ISSUE THREAD

**Issue by bdrose** [sanderland/katrain#101]
I am getting an error in 1.2.1/1.2.2 when trying to use the already existing Katago install.

ERROR KataGo Engine Failed: Uncaught exception: Could not find key 'nnMaxBatchSize' in config file
C:\my_config.cfg

It would be nice if it would use Katago without the need to specify this variable in the config file, Lizzie and Katago seems fine on their own when not specifying it.

**Comment by sanderland** [comment]
Katrain uses the analysis engine and not the gtp engine the default analysis config should work.

**Comment by bdrose** [comment]
Thanks for the clarification.
A note for anyone else that runs into this:
When using your local standalone KataGo, the config file that works out of the box is:
<folders>\analysis_example.cfg
not, as in some other programs.
<folders>\default_gtp.cfg
