### ISSUE TITLE
Engine crashes when out of memory

### ISSUE THREAD

**Issue by scriby** [sanderland/katrain#11]
![image](https://user-images.githubusercontent.com/815188/77838780-c02e1780-712b-11ea-9a8d-11aee1ba34dc.png)

My friend is seeing this when running KaTrain (he is using a Japanese Windows computer). After the error occurs the UI becomes unresponsive. Just wondering if you had any ideas what could be going on.

**Comment by sanderland** [comment]
Hey scriby, thanks for the bug report. The show_error thing is fixed in master now, but is not the real problem. OSError 22 is very vague, I wonder if there's an earlier error when starting kata, a full output (of playing a single move to get this error) would be useful.
Also, if there's no such extra error, could he try running the latest version the hard way (with anaconda) ?

**Comment by scriby** [comment]
He’s not really an expert at using the computer, so it’s a little hard to
give complicated instructions. I can have him run the next version released
and report back whatever information is shown. How does that sound?

**Comment by sanderland** [comment]
Without any more information, I won't be able to fix it. Could you get a screenshot of the output after a single move is played?

**Comment by wonsiks** [comment]
I've met same problem when I use katago 1.3.5-bs29, but no problem after I change katago 1.3.5 version(no bs29).
You may try non bs version of katago.

**Comment by sanderland** [comment]
@wonsiks I am working on a v1 now which is fully compatible with bs29, including non-square sizes. Still, I have not seen the error, even though my windows is a Korean version (한국에서 살았을 때 샀기 때문에..) which can cause some weird codec issues.

**Comment by sanderland** [comment]
Believe it or not, I just encountered the error when running some self-play tournaments on my new AI options. I believe it is related to KataGo crashing (due to out of memory?).
https://stackoverflow.com/questions/23688492/oserror-errno-22-invalid-argument-in-subprocess

**Comment by sanderland** [comment]
Fixed in v1 to at least give an error.
