### ISSUE TITLE
Include the rank info in the SGF

### ISSUE THREAD

**Issue by fbremmer** [sanderland/katrain#113]
Instead of "katrain_Human (Normal Game) vs AI (Calibrated Rank) 2020-06-26 19 40 48.sgf"
maybe use "katrain_Human (Normal Game) vs AI (Calibrated Rank 10.0 kyu) 2020-06-26 19 40 48.sgf"

**Comment by sanderland** [comment]
I think it becomes messy, especially when more options are involved. I can try to set the BR and WR fields in the sgf though

**Comment by fbremmer** [comment]
I see. Yes, having the rank info recorded inside the game file would also be helpful, and accomplish the same purpose.
