### ISSUE TITLE
Colorblind Accessibility

### ISSUE THREAD

**Issue by EarnMuse** [sanderland/katrain#116]
Being able to change colors, or better, having a non-color based way of representing the point loss of moves would make this accessible to people with non-minor red/green colorblindness.

**Comment by sanderland** [comment]
If you pass me some alternative(s) for the current values below, I can see what I can do.
```
EVAL_COLORS = [
    [0.447, 0.129, 0.42, 1],
    [0.8, 0, 0, 1],
    [0.9, 0.4, 0.1, 1],
    [0.85, 0.89, 0.3, 1],
    [0.67, 0.9, 0.18, 1.0],
    [0.117, 0.588, 0, 1.0],
]
```

**Comment by Dontbtme** [comment]
For color-blind people, having symbols or capital letters would be the way to go, I think.
Something like:
A or ♥
B or ♦
C or ♣
D or ♠
E or ■
F or ▲

**Comment by pwcarney** [comment]
![tableau_color_pal-3](https://user-images.githubusercontent.com/8118283/87478989-afc97c00-c5f8-11ea-94f3-240da28a1cb5.png)
Here's an example of a nice colorblind palette. The standard approach is leaning more into the blues and oranges. I'm wondering how much that'll jive with a Go board, but you could see how some of these feel.

**Comment by EarnMuse** [comment]
Simply including a grey-scale option - or making it possible to select custom colors - might be ideal.

**Comment by sanderland** [comment]
semi-transparent grey-scale on black and white stones seems not ideal. I'd be happy to accept a PR on selecting custom colors, but I'd expect it'd be a serious amount of work.

**Comment by ajkenny84** [comment]
I am red-green colorblind so I tried to come up with 6 colors that make it easier _for me_ to distinguish each one.

Screenshot below with example colored dots on the black and white stones.

![Screen Shot 2020-07-27 at 8 59 50 PM](https://user-images.githubusercontent.com/1944299/88608726-79581c00-d050-11ea-9c93-650ec355355a.png)

**Comment by sanderland** [comment]
Added in 05d2cea

![image](https://user-images.githubusercontent.com/48946947/88650102-b52ec800-d0c8-11ea-86b4-7d47c8478015.png)
![image](https://user-images.githubusercontent.com/48946947/88650247-d7284a80-d0c8-11ea-8d6b-6955eedac976.png)

used the normal yellow since pure yellow is hard to see on white, hope it's ok. :)
