### ISSUE TITLE
Zoom score graph

### ISSUE THREAD

**Issue by guskal01** [sanderland/katrain#117]
Sometimes in my games a big dragon dies at the end. When I load the game in KaTrain and let it analyze it, the score graph goes up to B+100 at the end of the game and all mistakes in the beginning become invisible (line is almost flat). However, the mistakes earlier in the game are more interesting for me - I already knew that it was a big mistake to let the dragon die. I'm currently solving this problem by deleting the end of the SGF file, but it would be nicer with a solution inside KaTrain.

My ideas are:
1. Scroll inside score graph to zoom vertically.
2. Option to make autoanalyse skip end of the game.
3. Logarithmic score graph.

Side question: is it possible to make sgf analysis deeper than "live analysis"? I don't mind if it takes a few minutes to analyse the sgf.

**Comment by sanderland** [comment]
Somewhat covered by #92 maybe if you can clip the end off? Going into a branch before your dragon dies will also rescale (but not persist when going back).
Overall the zooming itself is a bit too much work for such a minor thing, so I'll put it on help wanted in case anyone wants to pick it up (rather unlikely) - but will prioritize branch deletion at least

#93 covers your side question
![image](https://user-images.githubusercontent.com/48946947/86385132-1319ec80-bc90-11ea-8942-3e7ee69a2344.png)
