### ISSUE TITLE
Where is Komi?

### ISSUE THREAD

**Issue by GimmeDatCode** [sanderland/katrain#122]
I have looked everywhere for komi and I can't find it in the user interface. This is a bug and komi must be made more clear and changeable thank you

**Comment by sanderland** [comment]
New game

**Comment by GimmeDatCode** [comment]
Thank you very much for katrain. it is very useful, and very beautiful. But komi should be visible in the UI at all times, this caused me great confusion. Thank you.

**Comment by GimmeDatCode** [comment]
I should make enhancement request?

**Comment by sanderland** [comment]
A pull request would be better.
