### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by ghistes** [sanderland/katrain#124]
Hi,

sorry for asking a noob question, but I tried to install katrain via pip3 and it failed.

So I had a closer look at your documentation where you explicitely state that you expect a 3.6 or 3.7 version of python, while my system has 3.8.2.

My question: Is there a way to make katrain work with python 3.8.2 (i.e. installing it via some other way but run it under python 3.8) or do I absolutely need a 3.6/3.7 version of python?

Many thanks!

**Comment by sanderland** [comment]
I think it's been working on 3.8 for me, what OS?

**Comment by ghistes** [comment]
Debian testing

**Comment by sanderland** [comment]
does any of this help?
https://github.com/sanderland/katrain/blob/32074d6616672c6a42057b5375e6666235205a0d/INSTALL.md

**Comment by ghistes** [comment]
Surprisingly it does not.

I've read that before I posted the issue.

My problem is that I have a working 3.8.2 python (I use it for other software without problems), yet a "pip3 install katrain" fails.

Specifically it does not fail with installing kartain itself but it fails installing dependencies (pygames or cython or something like that).

So I assume the dependencies are not properly reflected in the package (but I really don't know anything about python-packages).

My question is simply: 

Should it work with 3.8.2 or do I need a 3.6/3.7?

**Comment by sanderland** [comment]
I see, pygame seems to fail without some sdl stuff installed. Could you try the 'hard way', i.e. cloning and installing kivy/kivymd and running `python -m katrain` ?

**Comment by sanderland** [comment]
Try 1.3.1, it works for me on a 3.8 pyenv

**Comment by ghistes** [comment]
Unfortunately does not seem to work for me:

`Collecting katrain
  Downloading https://files.pythonhosted.org/packages/09/e6/eab48573622e9efbc3e3d8a3a9911e7a41d51a8af2fa7119da7fc78eaf03/KaTrain-1.3.1-py3-none-any.whl (58.6MB)
    100% |████████████████████████████████| 58.6MB 23kB/s
Collecting kivymd>=0.104.1 (from katrain)
  Downloading https://files.pythonhosted.org/packages/c4/4e/f33085dab6420009fefc214cb3f8fc88ecd9d9e766976aa14f93b033a53a/kivymd-0.104.1-py3-none-any.whl (2.4MB)
    100% |████████████████████████████████| 2.4MB 499kB/s
Collecting wheel (from katrain)
  Using cached https://files.pythonhosted.org/packages/8c/23/848298cccf8e40f5bbb59009b32848a4c38f4e7f3364297ab3c3e2e2cd14/wheel-0.34.2-py2.py3-none-any.whl
Collecting screeninfo; platform_system != "Darwin" (from katrain)
  Using cached https://files.pythonhosted.org/packages/d1/1d/d9861700fa0692d39f4aaf7233ee3dd9cbebd514546fec9344a824f63af4/screeninfo-0.6.5.tar.gz
Collecting kivy==2.0.0rc2 (from katrain)
  Downloading https://files.pythonhosted.org/packages/01/57/aae0abdf40f89f3535eeb6f9611a8b6efe86a44a785cec7efa92f60b1d85/Kivy-2.0.0rc2.tar.gz (23.6MB)
    100% |████████████████████████████████| 23.6MB 58kB/s
  Installing build dependencies ... error
  Complete output from command /usr/bin/python3 -m pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-8q7cki62 --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel cython>=0.24,<=0.29.14,!=0.27,!=0.27.2 "kivy_deps.gstreamer_dev~=0.2.0; sys_platform == \"win32\"" "kivy_deps.sdl2_dev~=0.2.0; sys_platform == \"win32\"" "kivy_deps.glew_dev~=0.2.0; sys_platform == \"win32\"" "kivy_deps.gstreamer~=0.2.0; sys_platform == \"win32\"" "kivy_deps.sdl2~=0.2.0; sys_platform == \"win32\"" "kivy_deps.glew~=0.2.0; sys_platform == \"win32\"":
  Ignoring kivy-deps.gstreamer-dev: markers 'sys_platform == "win32"' don't match your environment
  Ignoring kivy-deps.sdl2-dev: markers 'sys_platform == "win32"' don't match your environment
  Ignoring kivy-deps.glew-dev: markers 'sys_platform == "win32"' don't match your environment
  Ignoring kivy-deps.gstreamer: markers 'sys_platform == "win32"' don't match your environment
  Ignoring kivy-deps.sdl2: markers 'sys_platform == "win32"' don't match your environment
  Ignoring kivy-deps.glew: markers 'sys_platform == "win32"' don't match your environment
  Collecting setuptools
    Using cached https://files.pythonhosted.org/packages/41/fa/60888a1d591db07bc9c17dce2bcfb9f00ac507c0a23ecb827e76feb8f816/setuptools-49.1.0-py3-none-any.whl
  Collecting wheel
    Using cached https://files.pythonhosted.org/packages/8c/23/848298cccf8e40f5bbb59009b32848a4c38f4e7f3364297ab3c3e2e2cd14/wheel-0.34.2-py2.py3-none-any.whl
  Collecting cython!=0.27,!=0.27.2,<=0.29.14,>=0.24
    Using cached https://files.pythonhosted.org/packages/fc/38/990d837843c724201ea662ed2994709aee95f53a1226ded0638e71bb46ca/Cython-0.29.14-cp38-cp38-manylinux1_x86_64.whl
  Installing collected packages: setuptools, wheel, cython
  Exception:
  Traceback (most recent call last):
    File "/usr/lib/python3/dist-packages/pip/_internal/cli/base_command.py", line 143, in main
      status = self.run(options, args)
    File "/usr/lib/python3/dist-packages/pip/_internal/commands/install.py", line 377, in run
      installed = install_given_reqs(
    File "/usr/lib/python3/dist-packages/pip/_internal/req/__init__.py", line 45, in install_given_reqs
      requirement.install(
    File "/usr/lib/python3/dist-packages/pip/_internal/req/req_install.py", line 757, in install
      self.move_wheel_files(
    File "/usr/lib/python3/dist-packages/pip/_internal/req/req_install.py", line 374, in move_wheel_files
      move_wheel_files(
    File "/usr/lib/python3/dist-packages/pip/_internal/wheel.py", line 213, in move_wheel_files
      scheme = distutils_scheme(
    File "/usr/lib/python3/dist-packages/pip/_internal/locations.py", line 165, in distutils_scheme
      i.finalize_options()
    File "/usr/lib/python3.8/distutils/command/install.py", line 269, in finalize_options
      raise DistutilsOptionError(
  distutils.errors.DistutilsOptionError: must supply either home or prefix/exec-prefix -- not both

  ----------------------------------------
Command "/usr/bin/python3 -m pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-8q7cki62 --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel cython>=0.24,<=0.29.14,!=0.27,!=0.27.2 "kivy_deps.gstreamer_dev~=0.2.0; sys_platform == \"win32\"" "kivy_deps.sdl2_dev~=0.2.0; sys_platform == \"win32\"" "kivy_deps.glew_dev~=0.2.0; sys_platform == \"win32\"" "kivy_deps.gstreamer~=0.2.0; sys_platform == \"win32\"" "kivy_deps.sdl2~=0.2.0; sys_platform == \"win32\"" "kivy_deps.glew~=0.2.0; sys_platform == \"win32\""" failed with error code 2 in None
`

**Comment by sanderland** [comment]
This seems to be an issue with your python installation, and not katrain. googling ` distutils.errors.DistutilsOptionError: must supply either home or prefix/exec-prefix -- not both` shows some solutions.
