### ISSUE TITLE
Adjust AI reading strength

### ISSUE THREAD

**Issue by TuringJest** [sanderland/katrain#127]
Is it possible to limit the reading complexity to predefined levels? Or offer a style that avoids complicated tsumegos?

It probably doesn't make sense to give a move recommendation that requires beyond human level reading or even just beyond the player's level. 

This shouldn't affect ladders and nets of course.

**Comment by sanderland** [comment]
![image](https://user-images.githubusercontent.com/48946947/86567245-52378e80-bf6b-11ea-8ac8-b13700830d74.png)

**Comment by TuringJest** [comment]
That doesn't make sense, you already trained the network to follow certain playstyles. 

Sure, to train a completely new network to pro level will take a lot of time. 
But this could be trained for weaker levels with the constraint of limiting the reading depth. 

This afaik can be done approx already by using larger networks that have better feature recognition and limit the time per readout. 

A better move is of no use for a human if the follow-up can't be read on a human level.

**Comment by sanderland** [comment]
I would be very impressed if you could do this, and look forward to your PR

**Comment by TuringJest** [comment]
I would try, but I have never trained a go network. 
With the time I have at my hands I don't think I can change that too soon. 

Can only say that I have played some larger network some time ago with less than a second of readout time and it avoided complicated fights, for the most part. It would rather play a simple big move. 
Although, it might be debatable what is feature recognition and what is some kind of "hidden reading" that comes with the network optimization as it would sacrifice smaller groups for larger areas. 

So you probably have a point, too.
