### ISSUE TITLE
i18n text is not updated until restart

### ISSUE THREAD

**Issue by kaorahi** [sanderland/katrain#135]
1. Start Katrain.
2. Push Shift key (the main hamburger menu), click German icon, and push Shift key again.
3. Push F8 key (the general settings) and then Esc key.
4. Push Shift key, click English icon, and push Shift key again.
5. Push F8 key.

Then I still see the German text "1 verfugbare Modelle gefunden". I need to restart Katrain to get the expected English text "1 available model(s) found". This can also cause font problems for CJK languages.

~~~~
$ git show --quiet --pretty=format:'%h%d'
2214e7c (HEAD -> master, origin/master, origin/HEAD)
~~~~

**Comment by sanderland** [comment]
Yeah I knew about this, but considered it an unimportant edge case. Fixed anyway.
