### ISSUE TITLE
"Update AI Settings" not working

### ISSUE THREAD

**Issue by castal** [sanderland/katrain#139]
I am running 1.3.2 on my Mac.

The "AI Settings" panel is set to "Score Loss" by default. Changing to any other option such as "KataHandicap" (and clicking the "Update AI Settings") makes the change, but only for the duration of the current katrain session. After quitting and restarting katrain, the "AI Settings" value reverts back to "Score Loss". The value of the "strength" parameter for  "Score Loss" does seem to be saved across sessions, however.

**Comment by sanderland** [comment]
I can not reproduce this. Score Loss is selected by default in the absence of any AI players being selected (settings defaults to any AI selected otherwise). However, after you select another AIs option, it's settings should persist.

**Comment by castal** [comment]
At the moment, I have 7 models installed in two directories, ~/.katrain and katrain/models. The newer katago models are in ~/.katrain. I've been meaning to do some housecleaning anyway. Maybe a fresh reinstall with all the models in the right places will straighten this out. I'm on redit now if you want to chat. Otherwise, I'll be back a little later after I've cleaned up.

Here are the two direcctories:
~ 1: ls -l ~/.katrain
total 926880
-rw-r--r--  1 danielputnam  staff       4989 Jul 15 16:44 config.json
-rw-r--r--  1 danielputnam  staff       2914 Jun  3 16:38 config.json.1.1.0.backup
-rw-r--r--  1 danielputnam  staff       2925 Jun 17 16:12 config.json.1.1.2.backup
-rw-r--r--  1 danielputnam  staff       4809 Jul  7 17:39 config.json.1.2.0.backup
-rw-r--r--  1 danielputnam  staff  202733631 Jun 21 16:16 g170-b30c320x2-s4824661760-d1229536699.bin.gz
-rw-r--r--  1 danielputnam  staff  173512182 Jun 21 16:15 g170-b40c256x2-s5095420928-d1229425124.bin.gz
-rw-r--r--  1 danielputnam  staff   87358203 Jun 21 16:14 g170e-b20c256x2-s5303129600-d1228401921.bin.gz

models 25: pwd
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/katrain/models
models 26: ls -l
total 977760
-rw-r--r--  1 danielputnam  admin          0 Jul 14 15:29 __init__.py
drwxr-xr-x  3 danielputnam  admin         96 Jul 14 15:29 __pycache__
-rw-r--r--@ 1 danielputnam  admin   87357356 May 21 15:08 g170-b20c256x2-s4384473088-d968438914.bin.gz
-rw-r--r--@ 1 danielputnam  admin  202758288 May 21 15:08 g170-b30c320x2-s3530176512-d968463914.bin.gz
-rw-r--r--@ 1 danielputnam  admin  173528426 May 21 15:08 g170-b40c256x2-s3708042240-d967973220.bin.gz
-rw-r--r--  1 danielputnam  admin   36948927 Jul 14 15:29 g170e-b15c192-s1672170752-d466197061.bin.gz
-rw-r--r--  1 danielputnam  admin       8889 May 21 15:13 gtp.log

**Comment by castal** [comment]
I experimented with both "Update AI Settings" and "Update Settings" to see how they affect the "~/.katrain/config.json" file. The   "Update Settings" button reliably changes the katago model listed in the .json file.

If I change the "strength" value of "Score Loss", that change is correctly entered into the .json file. Otherwise, the "Update AI Settings"  changes only the timestamp of the .json file, but does not change the file contents. The following is a copy of the config.json file:

.katrain 23: cat config.json
{
    "engine": {
        "katago": "",
        "model": "katrain/models/g170-b30c320x2-s3530176512-d968463914.bin.gz",
        "config": "katrain/KataGo/analysis_config.cfg",
        "threads": 12,
        "max_visits": 800,
        "fast_visits": 50,
        "max_time": 4.0,
        "wide_root_noise": 0.0,
        "_enable_ownership": true
    },
    "general": {
        "sgf_load": "~/Downloads",
        "sgf_save": "./sgfout",
        "anim_pv_time": 0.5,
        "debug_level": 1,
        "lang": "en",
        "version": "1.3.0"
    },
    "timer": {
        "byo_length": 30,
        "byo_periods": 5,
        "sound": true
    },
    "game": {
        "size": "19",
        "komi": 0.5,
        "handicap": 7,
        "rules": "japanese",
        "clear_cache": true
    },
    "trainer": {
        "num_undo_prompts": [
            1,
            1,
            1,
            0.5,
            0,
            0
        ],
        "eval_thresholds": [
            12,
            6,
            3,
            1.5,
            0.5,
            0
        ],
        "save_feedback": [
            true,
            true,
            true,
            true,
            false,
            false
        ],
        "show_dots": [
            true,
            true,
            true,
            true,
            true,
            true
        ],
        "eval_off_show_last": 3,
        "eval_show_ai": true,
        "lock_ai": false
    },
    "ai": {
        "ai:default": {},
        "ai:handicap": {
            "automatic": true,
            "pda": 0
        },
        "ai:jigo": {
            "target_score": 0.5
        },
        "ai:scoreloss": {
            "strength": 0.25
        },
        "ai:policy": {
            "opening_moves": 22.0
        },
        "ai:p:weighted": {
            "weaken_fac": 1.25,
            "pick_override": 1.0,
            "lower_bound": 0.001
        },
        "ai:p:pick": {
            "pick_override": 0.95,
            "pick_n": 5,
            "pick_frac": 0.35
        },
        "ai:p:local": {
            "pick_override": 0.95,
            "stddev": 1.5,
            "pick_n": 15,
            "pick_frac": 0.0,
            "endgame": 0.5
        },
        "ai:p:tenuki": {
            "pick_override": 0.85,
            "stddev": 7.5,
            "pick_n": 5,
            "pick_frac": 0.4,
            "endgame": 0.45
        },
        "ai:p:influence": {
            "pick_override": 0.95,
            "pick_n": 5,
            "pick_frac": 0.3,
            "threshold": 3.5,
            "line_weight": 10,
            "endgame": 0.4
        },
        "ai:p:territory": {
            "pick_override": 0.95,
            "pick_n": 5,
            "pick_frac": 0.3,
            "threshold": 3.5,
            "line_weight": 2,
            "endgame": 0.4
        },
        "ai:p:rank": {
            "kyu_rank": -2.0
        }
    },
    "ui_state": {
        "play": {
            "analysis_controls": {
                "show_children": false,
                "eval": false,
                "hints": false,
                "policy": false,
                "ownership": false
            },
            "panels": {
                "graph_panel": [
                    "close",
                    {
                        "score": true,
                        "winrate": false,
                        "rank_est": false
                    }
                ],
                "stats_panel": [
                    "open",
                    {
                        "score": true,
                        "winrate": true,
                        "points": true
                    }
                ],
                "notes_panel": [
                    "close",
                    {
                        "info": true,
                        "info-details": false,
                        "notes": false
                    }
                ]
            }
        },
        "analyze": {
            "analysis_controls": {
                "show_children": true,
                "eval": false,
                "hints": true,
                "policy": false,
                "ownership": true
            },
            "panels": {
                "graph_panel": [
                    "open",
                    {
                        "score": true,
                        "winrate": true,
                        "rank_est": false
                    }
                ],
                "stats_panel": [
                    "open",
                    {
                        "score": true,
                        "winrate": true,
                        "points": true
                    }
                ],
                "notes_panel": [
                    "open",
                    {
                        "info": true,
                        "info-details": true,
                        "notes": false
                    }
                ]
            }
        }
    }
}

**Comment by sanderland** [comment]
```"ai:p:rank": {
"kyu_rank": -2.0
}```
now if you select calibrated rank, set it to 5k, and save (don't change back to any other ai before saving) - does the config not change to show 5k? it does for me!

**Comment by castal** [comment]
Yes, the config now shows 5k, but the AI strategy is still set to "Score Loss".

.katrain 3: cp config.json config.save
.katrain 4: vi config.json # I didn't make any changes, just looking!
.katrain 5: diff config.json config.save
126c126
<             "kyu_rank": 5.0
---
>             "kyu_rank": -2.0
.katrain 6:

**Comment by castal** [comment]
``

> Yes, the config now shows 5k, but the AI strategy is still set to "Score Loss".
> 
> ## .katrain 3: cp config.json config.save
> .katrain 4: vi config.json # I didn't make any changes, just looking!
> .katrain 5: diff config.json config.save
> 126c126
> < "kyu_rank": 5.0
> > ```
> >         "kyu_rank": -2.0
> > ```
> 
> .katrain 6:
