### ISSUE TITLE
About katago path setting and Japanese input

### ISSUE THREAD

**Issue by hope366** [sanderland/katrain#143]
First of all, thank you for the great tool.
I would like to tell you about two points.
* Regarding the added function of the latest version v1.3.2, it says that if you enter a command between double quotation marks of katago path setting, this specifically refers to where you are. Or?
I couldn't try this well.
* When I enter in the field "Your SGF notes for this position here", I cannot enter in Japanese. Furthermore, if you try to type in Japanese and hit some key, you will not be able to type even if you return to alphabet input.

**Comment by sanderland** [comment]
* See issue #131 - this is still very experimental though.
* I can't really test this, but know in Korean it only shows up a character after you have completed typing it (without any intermediate form showing) see https://github.com/kivy/kivy/issues/6898

**Comment by hope366** [comment]
Thank you for your response.
In case of Japanese input, it seems to be displayed as "□" after the input is completed.
![コメント](https://user-images.githubusercontent.com/63999713/87823561-98b3b400-c8ae-11ea-9385-744f6f850853.jpg)
If you open the saved file with lizzie, it will be displayed in proper Japanese.
![コメントリジー](https://user-images.githubusercontent.com/63999713/87823664-c39e0800-c8ae-11ea-9c90-4cbf522a5947.jpg)
Nothing is displayed when opened with Katrain.
![kコメントリジー](https://user-images.githubusercontent.com/63999713/87823716-e7614e00-c8ae-11ea-8acd-49eefc780574.jpg)

The katago path is a bit difficult, but I'd like to take the time to understand it.
Thank you.

**Comment by sanderland** [comment]
Ah, you have it set to English! Please set it to Japanese and you will be able to type Japanese.

![image](https://user-images.githubusercontent.com/48946947/87825549-9f730480-c877-11ea-90be-be755fd21f3c.png)

**Comment by hope366** [comment]
Oh, this was my mistake.
We're sorry for the inconvenience.

**Comment by sanderland** [comment]
>  This is true even if you type in English. Is there a way to view the saved comments?

Currently there is not, since the analysis and comment are merged into one. The SGF format is a bit limiting for this. I usually just use Sabaki to open files that are already analyzed.

**Comment by hope366** [comment]
If you save it in English mode of Katrain, the analysis result will be displayed when you open it in lizzie or sabaki, but if you save it in Japanese mode, the analysis result does not appear...
It seems that the analysis result is displayed when loading with Katrain.

**Comment by sanderland** [comment]
![image](https://user-images.githubusercontent.com/48946947/87828412-2b3b5f80-c87d-11ea-84ce-30bb0d23ac22.png)

**Comment by hope366** [comment]
No matter how many times I try to load a file saved with Katrain with Sabaki, the analysis results are not displayed.
I finally realized it. It seems that the analysis result is displayed only when you enter some comments by yourself.
Is it all right to understand such specifications?

**Comment by hope366** [comment]
Also, when I tried to enter a comment in Japanese and save it, the following error message appeared.
ERROR: Exception in processing message output-sgf(): 'NoneType' object has no attribute 'candidate_moves'

**Comment by sanderland** [comment]
> 
> 
> No matter how many times I try to load a file saved with Katrain with Sabaki, the analysis results are not displayed.
> I finally realized it. It seems that the analysis result is displayed only when you enter some comments by yourself.
> Is it all right to understand such specifications?

It depends on your teaching settings, whether you have checked to output certain moves (AI, green, etc).

>  ERROR: Exception in processing message output-sgf(): 'NoneType' object has no attribute 'candidate_moves'

This is a bug for the root node, I will fix it

**Comment by hope366** [comment]
By the way, dark green and yellow green were not checked by default. If you check this, the analysis result is displayed in sabaki.
I'm sorry I didn't have enough observation power.

**Comment by hope366** [comment]
I've used sabaki and lizzie most of the time, but recently I'm interested in katrain.
It is convenient to give quick feedback on your moves.
Also, various weakened AIs are interesting.
Thank you very much for your kindly answering my elementary questions.
