### ISSUE TITLE
Teaching Game Settings

### ISSUE THREAD

**Issue by Kostaneda** [sanderland/katrain#147]
Maybe it makes sense to add the ability to control the loss of winrate? This is especially important at the endgame, when losing 0.5 points could be worth winning.

**Comment by sanderland** [comment]
Even high dan players have bigger mistakes to focus on. The program is set up to find those mistakes and work on them.

**Comment by Kostaneda** [comment]
I think it is more useful for weak players like me to keep track of winrate. Imho
