### ISSUE TITLE
Font problem in General & Engine Settings

### ISSUE THREAD

**Issue by kaorahi** [sanderland/katrain#148]
I have a font problem in "General & Engine Settings" (F8) after 333e16e.
![tofu](https://user-images.githubusercontent.com/38910552/88459767-bb5b5380-ced2-11ea-93f6-2a617ba57b82.png)

**Comment by sanderland** [comment]
Should be fixed in the latest commit, seems that button code did something after all!
Also I changed to using the CJK font always, so if should be possible to type/see japanese when it's set to other languages, and there is some IME support in the notes box.

**Comment by kaorahi** [comment]
fixed in d91b223. thx :)

The note box also works fine with Japanese IME even if I set the language to English.
