### ISSUE TITLE
Question: best move shown not always the greenest one

### ISSUE THREAD

**Issue by SylvainNZ** [sanderland/katrain#149]
I am wondering if this is a bug or if I am misinterpreting colours.
Sometimes (about once a game), I will see a circled move but there are 'greener' options shown.

Like here:
![image](https://user-images.githubusercontent.com/25375326/88469653-0794ab00-cf48-11ea-964e-e81b3adb447c.png)

I can sometimes fix it by doing more analysis.

How should I interpret this?

Thank you

**Comment by SylvainNZ** [comment]
another example
![image](https://user-images.githubusercontent.com/25375326/88470598-6bbc6c80-cf52-11ea-9956-d7661c397ad6.png)

**Comment by Cadspen** [comment]
I think this is because the best move from policy isn't always the best result after reading it out, but I'm not sure

**Comment by sanderland** [comment]
The move circled is the top move given by katago _after_ reading, however:

* The default utility is not purely score, so the top move can occasionally be a 'safer' move with minor point loss.
* More commonly, it means there is an actual difference between the score estimate of the current position and the top move. This can happen in the case of:
    * low visits
    * when the move was taken in the game and analyzed more deeply, the parent analysis is then updated. In this case the non-dark green color indicates that kata is somewhat confused in the position.

**Comment by Cadspen** [comment]
You're right.  I forgot that the color of the dots is based on territory lost and not policy/best move from reading

**Comment by SylvainNZ** [comment]
ok, thanks for the explanation.
