### ISSUE TITLE
how to disable pondering?

### ISSUE THREAD

**Issue by cryptpark** [sanderland/katrain#151]
default_gtp.cfg file is missing, how can this be done?

**Comment by sanderland** [comment]
The concept of pondering doesn't apply, katrain uses the analysis engine and not gtp

**Comment by cryptpark** [comment]
I found the reason for the incomprehensible processor load. when gtool2 is working, for some reason the "top moves" and "toggle continuous analysis" are spontaneously are enabled in the KaTrain

**Comment by sanderland** [comment]
Maybe something is giving a [spacebar] input to the program then!

**Comment by cryptpark** [comment]
I really liked this program! thank you very much!
just wondering - and somewhere in the files you can turn off "toggle continuous analysis" completely?

**Comment by sanderland** [comment]
keyboard shortcuts are defined in `katrain/__main__.py`
