### ISSUE TITLE
Feature: load comments from .sgf files into notes field

### ISSUE THREAD

**Issue by ajkenny84** [sanderland/katrain#152]
I cannot see comments using .sgf files from the American go e-newsletter or .sgf files I save myself from within Katrain.

Attached are a few screenshots showing that comments do appear in Sabaki so I believe the files are correctly formatted, as well as the actual .sgf files (renamed .txt so I can attach them here).

![Screen Shot 2020-07-27 at 8 05 18 PM](https://user-images.githubusercontent.com/1944299/88604298-2b89e680-d045-11ea-8b8c-c7f40b7c80d3.png)

![Screen Shot 2020-07-27 at 8 07 15 PM](https://user-images.githubusercontent.com/1944299/88604310-304e9a80-d045-11ea-8663-7a1f4c58a70f.png)

[SDK (B)Anon 1k vs. (W)Anon 1k - Commentary by Kazunari Furuyama 8d 2020-06-23.txt](https://github.com/sanderland/katrain/files/4985286/SDK.B.Anon.1k.vs.W.Anon.1k.-.Commentary.by.Kazunari.Furuyama.8d.2020-06-23.txt)

[katrain_Human (Normal Game) vs Human (Normal Game) 2020-07-27 19 37 31.txt](https://github.com/sanderland/katrain/files/4985287/katrain_Human.Normal.Game.vs.Human.Normal.Game.2020-07-27.19.37.31.txt)

**Comment by sanderland** [comment]
Yes, comments don't have a place to show up. This is mainly because the analysis potentially becomes a giant comment which would then get duplicated.
I can see the functionality of katrain has grown to the point where this may be limiting, however.

TODO:
* insert some marker in analysis comments
* detect marker and fill notes field with all un-marked comments

**Comment by sanderland** [comment]
Played around with it for a bit, but between notes, comments already present and comments generated by the program it's too hard to keep them apart. v1.3.3 just adds the SGF comments to the info field, making them uneditable, but at least visible.
