### ISSUE TITLE
Kanji shape problem

### ISSUE THREAD

**Issue by kaorahi** [sanderland/katrain#153]
The shapes of some kanji characters were changed in 0ac5a47. They look a little strange for JP texts.

before 0ac5a47 (correct JP shape)
![before](https://user-images.githubusercontent.com/38910552/88668267-5d6e7c00-d11d-11ea-8520-c9476e7c58a2.png)

after 0ac5a47
![after](https://user-images.githubusercontent.com/38910552/88668328-70814c00-d11d-11ea-8a0b-a26b6dde9fd0.png)

**Comment by kaorahi** [comment]
ref. https://www.google.com/get/noto/help/cjk/

> Language-specific OpenType/CFF (OTF)
> 
> Each font sets one language as the default. Note that each language-specific font does support all four languages and includes the complete set of glyphs. However, you need an application program that can invoke an OpenType locl GSUB feature (e.g. Adobe InDesign) to access language-specific variants other than the default language.

You can choose "won't fix" if you like. We can still read these characters though they look strange in JP texts. It is not a practical issue but a problem of "look and feel".

**Comment by sanderland** [comment]
Yeah the sc font looked fine for me (no boxes in any language), but I can't read japanese - could restore the japanese font easily enough.

**Comment by kaorahi** [comment]
fixed. thx!
