### ISSUE TITLE
Installation of Katrain on iMac failed

### ISSUE THREAD

**Issue by ForestSounds** [sanderland/katrain#155]
I tried to install Katrain on my iMac (27-inch, Late 2013, macOS Catalina (10.15.6) by using the following commands in Terminal:

/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
brew install python3
brew install katago
pip3 install katrain

The first three seems to go well, but the final command gave error as seen in the attached file.
[katrain_installation_error.txt](https://github.com/sanderland/katrain/files/5026363/katrain_installation_error.txt)

Is there any way to get the installation working for me?

Kind regards,
Gerard Slooven

**Comment by sanderland** [comment]
The link in there suggests SDL is missing and suggests

`` `brew install sdl2 sdl2_gfx sdl2_image sdl2_mixer sdl2_net sdl2_ttf``` 

to get some dependencies.
I am not sure why you seem to need these dependencies as usually a compiled version of the pygame package is used. Are you on a 32 bit system?

**Comment by ForestSounds** [comment]
I tried this, and continued with installing Katrain, with as a result the error messages in the attached file.
[katrain_installation_error_2.txt](https://github.com/sanderland/katrain/files/5027135/katrain_installation_error_2.txt)

**Comment by sanderland** [comment]
Urgh, why is every package broken on mac. Pygame was supposed to bypass other errors. Can you 

* clone/download the repo
* remove the pygame line from requirements.txt
* `pip3 install -r requirements.txt`

**Comment by ForestSounds** [comment]
ehhh... what do you mean by "clone/download the repo"?

**Comment by sanderland** [comment]
`git clone https://github.com/sanderland/katrain/` or download this https://github.com/sanderland/katrain/archive/master.zip

**Comment by ForestSounds** [comment]
OK, downloaded the quatrain-master folder, removed the pyjama line from the requirements file, and ran the pip3 install -r requirements.txt line.
Terminal ca't find the requirements file and I don't know where to place it so it can be found bij terminal.

**Comment by ForestSounds** [comment]
UPDATE: got the pip3 install -r requirements.txt working!
After that, I tried installing Katrain again, but still loads of errors....
Is there a way out of this maze?

**Comment by sanderland** [comment]
if you got the requirements working, then just type `python3 -m katrain` in the folder with requirements.txt

**Comment by ForestSounds** [comment]
Ah! That worked!!!
Thank you VERY much.
With an eye to the future, what do I have to do to update to the newest version?

**Comment by sanderland** [comment]
Just download the source as above and run with `python3 -m katrain`, the requirements shouldn't change.
