### ISSUE TITLE
Feature suggestion -- Indicator for continuous analysis

### ISSUE THREAD

**Issue by simonguoxm** [sanderland/katrain#157]
Sometimes I toggle the continuous analysis, but the info panel doesn't have the number of analysis yet, so I don't know if I have successfully enabled the continuous analysis or not. 

If there is an indicator, that will be very convenient. For example, the icon of "Toggle Continuous Analysis" change to green when it is enabled.

**Comment by simonguoxm** [comment]
![Clipboard01](https://user-images.githubusercontent.com/4695131/89476715-0554fc80-d751-11ea-8d1e-00c4978b52d9.png)

**Comment by sanderland** [comment]
Yes, something that changes the engine 'light' could work. right now it's orange when it's busy with anything.

**Comment by sanderland** [comment]
![ponder](https://user-images.githubusercontent.com/48946947/90547564-009a3a80-e18c-11ea-8d7b-37cdfd8fd428.gif)

Thoughts?

**Comment by sanderland** [comment]
![ponder](https://user-images.githubusercontent.com/48946947/90548266-f9bff780-e18c-11ea-8b94-625c03b1305b.gif)

**Comment by simonguoxm** [comment]
as long as an indicator, it's much better.
