### ISSUE TITLE
DebugKaTrain can't find python37.dll

### ISSUE THREAD

**Issue by andrewbgross** [sanderland/katrain#160]
When I run Katrain.exe, I can't get it to work with the version of katago.exe, my .cfg, and my .bin files specified.  The all work fine with Sabaki.  I get "Engine died unexpectedly without sending output, possibly due to out of memory: status 1"

I did a google search for that error, and found a posting on reddit, where the person reporting the problem was instructed to set debug=1 and run from the console.

So, I downloaded the .zip file, and ran DebugKaTrain from the command line.  It gives the error message:
Error loading Python DLL 'E:\KataGo\python37.dll'.
LoadLibrary: The specified module could not be found.

I'm not willing to download a bunch of extra binaries, or learn about python, just to get a useful error message, so for now I'll keep using Sabaki.  If at some point there is a method for me to figure out why the same files that work with Sabaki are not working with Katrain, that doesn't involve me downloading entire file directories of files, I'll give it another try.

**Comment by sanderland** [comment]
Can not reproduce, and without seeing your settings it's hard to tell why you get that error.
It's very strange that it searches ''E:\KataGo\' at all, which suggests you mixed up some files.

**Comment by andrewbgross** [comment]
Why is it strange that it searches E:\KataGo?  The engine configuration page requires a path for the KataGo model and the KataGo gtp configuration file.  Why is it strange to you that someone might keep them in a directory named KataGo?

**Comment by sanderland** [comment]
analysis engine configuration file, not gtp.  and it's strange that it would search python37.dll there, which suggests that something is really strange. Did you take the .exe out of the zip file and move it?
