### ISSUE TITLE
Logging game results / allowing resignation.

### ISSUE THREAD

**Issue by fireproof** [sanderland/katrain#164]
There is no obvious way to resign a game against an AI.

**Comment by sanderland** [comment]
What would such a feature do? Personally I find Ctrl-N or Alt-F4 to be sufficient for resigning.

**Comment by fireproof** [comment]
Would it not help in training the AI / setting the AI kyu level?

**Comment by sanderland** [comment]
No, that is only set via the OGS bots, the program itself does not communicate any of your data back.

**Comment by MichaelVondung** [comment]
It would properly conclude the game and allow for a "complete" SGF record.

**Comment by sanderland** [comment]
Implemented in v1.5
