### ISSUE TITLE
Auto-adjusting AI strength based on player results.

### ISSUE THREAD

**Issue by bochen85** [sanderland/katrain#175]
Does KaTrain have persistent memory so as I play with it over time it gets more and more accurate feel of my strength (I'm beginner player) and adapts so that it plays at the optimal strength for me to learn from it the most quickly and then as I improve over time it also readjust itself to continuously stimulate me in manner that I can learn the fastest?

**Comment by sanderland** [comment]
No, you'll have to set your own rank. You usually want to set it a lot higher for teaching games, so it's not easy to tell what is best at what time.
