### ISSUE TITLE
Problem displaying Chinese player name / comments and wrong komi value for sgf exported from Fox Go Server

### ISSUE THREAD

**Issue by fuzihang** [sanderland/katrain#177]
![image](https://user-images.githubusercontent.com/12288856/91507147-0554a200-e8a2-11ea-8399-c37aa9041170.png)
I saved a recent game from fox go server and tried to open it with katrain. This is what happens. Looks like katrain has problems with displaying names and comments. Also it reports wrong komi values.

For reference, this is what it looks like when opened in sabaki.
![image](https://user-images.githubusercontent.com/12288856/91507425-ca06a300-e8a2-11ea-8c3c-c40d35cd8cb9.png)

Thanks.

Edit: Here's the sgf.
[[伊凌涛]vs[KeJie]1598514385010001105.zip](https://github.com/sanderland/katrain/files/5141928/vs.KeJie.1598514385010001105.zip)

Edit: Here's some other exported sgfs from foxgo, including 2 Chinese rule games,  2 Japanese rule games and 1 Chinese rule + handicap game.
[saves.zip](https://github.com/sanderland/katrain/files/5143847/saves.zip)

**Comment by sanderland** [comment]
Could you attach the sgf? (may need to zip it)
I know FoxGo generates incorrect SGFs, with weird handicap settings (HA[1]) instead of komi, and incorrect character-set encoding, so you may want to report this to fox and see if they care to fix. The komi erorr is new to me though.

**Comment by fuzihang** [comment]
Thanks for the info. Here's the sgf. I will try reporting this to Fox if I find a way to do so.
[[伊凌涛]vs[KeJie]1598514385010001105.zip](https://github.com/sanderland/katrain/files/5141898/vs.KeJie.1598514385010001105.zip)

**Comment by sanderland** [comment]
The file actually says `KM[375]HA[0]` , which is crazy. What is komi supposed to be in this game, 7.5?

**Comment by fuzihang** [comment]
> The file actually says `KM[375]HA[0]` , which is crazy. What is komi supposed to be in this game, 7.5?

You are right. It seems that Fox go sgfs have problems with komi. I tried exporting other sgfs from Fox and it never got it correct lol. It seems that it's necessary to first change the komi in some sgf editor before opening it in katrain so that katago can function correctly.

**Comment by sanderland** [comment]
fd67ea8 fixes some of these, specifically the player names and crashes, but it would be nice to have komi correct. If you could make me a table of foxgo settings (rules, handicap, komi) to what the SGF says, I could probably add it.

**Comment by fuzihang** [comment]
This is the table. I inspected some exported games (attached as saves.zip in the first post)
 from foxgo and make this table. However, I'm not sure if this is the general case for Foxgo. 
![image](https://user-images.githubusercontent.com/12288856/91607972-b90d6e80-e942-11ea-9ff9-fc8357ccf90a.png)

**Comment by sanderland** [comment]
well the dayline game has KM[0]HA[2] - so i assume that's a 0.5 komi game.

I think I will ignore komi and assume
HA[0]: 6.5/7.5 depending on rules
HA >= 1 : KM[0,5]

**Comment by fuzihang** [comment]
> well the dayline game has KM[0]HA[2] - so i assume that's a 0.5 komi game.
> 
> I think I will ignore komi and assume
> HA[0]: 6.5/7.5 depending on rules
> HA >= 1 : KM[0,5]

This makes sense. Thank you for replying swiftly.

**Comment by sanderland** [comment]
probably fixed in 341d016
