### ISSUE TITLE
Touchpad bug interpreting mouse-movements as stone placements

### ISSUE THREAD

**Issue by Tomptez** [sanderland/katrain#178]
Hello,

I really like this software I just encounter a really weird bug when using my touchpad, which makes it pretty much unusable without an external mouse.

Basically, katrain interprets my touchpad as a small go board and whenever i touch to move my mouse, for example in the upper right corner of my touchpad, my mouse does move, but it also places a stone in the upper right corner. So whenever I move my mouse, I randomly place a stone somewhere on the board, depending on where I touch my mousepad.
With an external mouse I have no problem whatsover.

Hardware: Dell Latitude E7470
Software: Katrain 1.4.0 installed via pip using KDE Plasma on Archlinux (Kernel 5.8.1)

**Comment by sanderland** [comment]
not having a touchpad makes this hard to investigate. if you want to check out the code, i'd suggest checking when the on_* functions in badukpan.py are triggered and if the events can be used to distinguish touch pads from mice in a sensible way.

**Comment by Tomptez** [comment]
Did some digging and this seems to be a [known issue](https://github.com/kivy/kivy/issues/5697) with kivy and libinput on linux.

Workaround suggested there is to edit ~/.kivy/config.ini
and change 

```
[input]
mouse = mouse
%(name)s = probesysfs
```

to 
```
[input]
mouse = mouse
#%(name)s = probesysfs
```

I can confirm this solves the issue. Unfortunately seems like there is no solution to fix that within the app as far as I can see.
