### ISSUE TITLE
Point loss indication on board different than analysis

### ISSUE THREAD

**Issue by Tomptez** [sanderland/katrain#179]
In this game on a 9x9 board it seems like the point loss indication on the board is way off. Visits to all moves are equalized. Almost all moves indicate a 0.0 point loss.

![18_indication](https://user-images.githubusercontent.com/2712721/91657633-ccdfde80-eac2-11ea-863e-3a6988f02d8a.png)

But if I play G6, the "details"-section it indicates a score that is different by 3.5 points. This is confirmed if I play the expected move (G3).

![19_G6](https://user-images.githubusercontent.com/2712721/91657631-cc474800-eac2-11ea-86b6-83987650baa9.png)
![19_G3](https://user-images.githubusercontent.com/2712721/91657630-ca7d8480-eac2-11ea-91b0-77fb0f8c1b2c.png)

**Comment by Tomptez** [comment]
With a bit of trial and error I can say that this is related to the engine settings.
With a wide root noise of 0 this does not occur. In this case I had set the wide root noise to 2.0

**Comment by sanderland** [comment]
wide root noise is between 0 and 1, and values above 0.1 are rather unreasonable. moves that are based on very low visits are more likely to lead to 'surprise' after they are played (higher visits analysis being different)
