### ISSUE TITLE
[Error report] Got an error over 15blocks nets.

### ISSUE THREAD

**Issue by wonsiks** [sanderland/katrain#18]
1) When I tried to use 20b.bin.gz net I met an error.
2) Tried with 15b.bin.gz net then works well.
3) Tried with 40b.bin.gz net and met an error too.
4) Tried with 20b.txt.gz net and met an error too.
I guess bigger than 15 blocks net causes error.
![katrain_err1](https://user-images.githubusercontent.com/37356450/80895754-51903b00-8d23-11ea-8b87-a6bb6f94053c.png)
![katrain_err2](https://user-images.githubusercontent.com/37356450/80895755-53f29500-8d23-11ea-91a0-2348f65a7cec.png)

**Comment by wonsiks** [comment]
The cuda version of KataGo works well regardless of the size of the net.

**Comment by sanderland** [comment]
I only get the error on restarting the engine while running. 
It maybe that the opencl version takes more memory, and because of the bs29 version it doesn't have enough. Maybe bs19 should be standard.

**Comment by wonsiks** [comment]
@sanderland I've tested with bs19 but it makes error too.

**Comment by sanderland** [comment]
very strange, i found a small bug in the swapping of engines while running, but I can swap 30 block for 40 block while running on opencl without problems? what's your gpu?

**Comment by wonsiks** [comment]
@sanderland I'm using GTX1060.
You can see the log from previous pictures.

**Comment by sanderland** [comment]
Then we nearly have the same GPU and setup, including the stupid 원 symbols instead of \. All very strange, I will keep this open and track further reports.

![image](https://user-images.githubusercontent.com/48946947/80915404-6a641500-8d52-11ea-890a-4474c654d43e.png)

**Comment by sanderland** [comment]
Ah, I see you have an on-motherboard graphics device, are you sure it's not trying to use that? (device 0?)

**Comment by wonsiks** [comment]
@sanderland Sure, I've edited analysis_config.cfg file to use device id 2.
It's strange that when I use 15b net there's no error and works well,
but when using 20b or 40b net error occurs right after I make the first move.

**Comment by sanderland** [comment]
can you try setting threads=1?

**Comment by wonsiks** [comment]
@sanderland I've changed numSearchThreads value to 1 and tried and got same error.

**Comment by sanderland** [comment]
I mean in config.json

**Comment by wonsiks** [comment]
@sanderland Tried both thread to 1 and 2, but got same errors.

**Comment by sanderland** [comment]
Can you run the analysis engine and/or gtp engine on the command line, or do they crash as well?

**Comment by wonsiks** [comment]
@sanderland They don't crash during startup. Just crash on the first move.
There was no problem on v0.9 but v1.0 and 1.0.1 make error with 20b net.

**Comment by sanderland** [comment]
can you show how the analysis engine and gtp engine crash?

**Comment by wonsiks** [comment]
@sanderland May this helps?
![20200503_233455](https://user-images.githubusercontent.com/37356450/80916941-cb154100-8d96-11ea-8716-21115136be52.png)

**Comment by sanderland** [comment]
you should replace the ' with " to be proper json

**Comment by wonsiks** [comment]
@sanderland I've got this message.
![20200503_234147](https://user-images.githubusercontent.com/37356450/80917084-c0a77700-8d97-11ea-8d59-06d4f9144a33.png)

**Comment by sanderland** [comment]
aha, replace True by true

**Comment by sanderland** [comment]
and I will change debug output to be json :)

**Comment by wonsiks** [comment]
@sanderland Engine ends without any message
![20200503_235032](https://user-images.githubusercontent.com/37356450/80917368-5b548580-8d99-11ea-8136-aa1238aa7a78.png)

**Comment by sanderland** [comment]
so this is a KataGo issue, please add it to https://github.com/lightvector/KataGo/issues/208
also try the GTP command and see if it does the same
(simply give "genmove black" as the command)

**Comment by wonsiks** [comment]
@sanderland Thanks for taking care of this.
I think there's no problem in gtp engine.
With Lizzie or Sabaki Katago works well with 20b or 40b nets.

**Comment by sanderland** [comment]
I think I am tracking down the cause. Please try decreasing nnMaxBatchSize in the cfg config to 64/32/16/8

**Comment by wonsiks** [comment]
@sanderland Oh, after I change nnMaxBatchSize from 128 to 64 then works well.
Thanks.

**Comment by sanderland** [comment]
@wonsiks alright, I will optimize settings in the next release

**Comment by wonsiks** [comment]
@sanderland Cool. Thanks for your kind work... :)

**Comment by sanderland** [comment]
@wonsiks no problem :) Also if you know anyone who wants to translate the manual into Korean, I am happy to include it on the repository.

**Comment by sanderland** [comment]
@wonsiks new release, hopefully resolves a lot of these issues.

**Comment by wonsiks** [comment]
@sanderland It's cool...  Thanks a lot.
