### ISSUE TITLE
Winrate problem

### ISSUE THREAD

**Issue by ProLeela** [sanderland/katrain#180]
With the empty board, KataGo 1.6.1, with one of the last networks and 6.5 komi, 0H, Sabaki is giving a winrate about 55-56%, Lizzie (is true, with its own Katago/network) 56%, Katrain is giving the 51% for **white**!
I do not understand. Is a serious problem, at least for me, otherwise I would prefer Katrain for its friendly interface and explicit listing of the score.
Any hint pls?

**Comment by sanderland** [comment]
51-53% for white is normal. If sabaki/leela are giving 56% for black, something is wrong there - maybe ask in discord (https://discord.gg/AjTPFpN)
