### ISSUE TITLE
Working after close

### ISSUE THREAD

**Issue by Pestr** [sanderland/katrain#183]
Sometimes (not every time) after closing the application remains hidden and works and uses GPU.
Need to manually close it through the task manager.
Windows 10.

**Comment by sanderland** [comment]
is this for much longer than a minute or two?

**Comment by Pestr** [comment]
yeah. after run game analysis and close process working 1-2 min after close.
katago-<version>.exe

It can be duplicate, if I reopen and close KaTrain many times. And it really freezes system.

**Comment by sanderland** [comment]
related to killing the shell and not kata itself, probably fixed in f7eb7f1
