### ISSUE TITLE
Need to improve a next stone placement color or contrast

### ISSUE THREAD

**Issue by Pestr** [sanderland/katrain#184]
Need to improve a next stone placement color or contrast. It's almost invisible under color circles, especially when they are with enabled score points.

**Comment by sanderland** [comment]
![image](https://user-images.githubusercontent.com/48946947/92267456-fe9cdf00-eee0-11ea-8ab8-bf21e1917846.png)
was actually working on that today, how does this look?

**Comment by Pestr** [comment]
May be better, but not perfect. 
May be so?
![Imgur](https://i.imgur.com/aZnKvTR.jpg)

**Comment by Pestr** [comment]
or may be OGS-style like this
![](https://i.imgur.com/XV7iOp2.jpg)

**Comment by sanderland** [comment]
![image](https://user-images.githubusercontent.com/48946947/92334823-bbce3900-f091-11ea-8933-b14f09a8041f.png)
![image](https://user-images.githubusercontent.com/48946947/92334826-bec92980-f091-11ea-9de3-833ca586fb52.png)
after some iteration with my designer, will be in 1.4.1
