### ISSUE TITLE
PL tag not affecting analysis

### ISSUE THREAD

**Issue by pdeblanc** [sanderland/katrain#185]
I tried loading an sgf file with some stones already set up and white to play on the root node. The moves suggested by katrain made no sense as white moves, but did make sense as black moves (e.g. attachment to a white stone). Clicking on the board did place a white stone as expected, but the strange behavior of the analysis persists in child nodes.

**Comment by sanderland** [comment]
could you include the SGF file? the PL tag is very rare and indeed not interpreted (because genererally there's very little you can do about it for katago). usually handicap games start AB[];W[]

**Comment by sanderland** [comment]
probably fixed in 14dd5d5
