### ISSUE TITLE
Failed to start provided KataGo in v1.4.1x

### ISSUE THREAD

**Issue by kaorahi** [sanderland/katrain#188]
I got this error after f7eb7f1 in #183.

ERROR: Starting KataGo with command '"/home/FOO/BAR/katrain/KataGo/katago" analysis -model "/home/FOO/BAR/katrain/models/g170e-b15c192-s1672170752-d466197061.bin.gz" -config "/home/FOO/BAR/katrain/KataGo/analysis_config.cfg" -analysis-threads 12' failed with error [Errno 2] No such file or directory: '"/home/FOO/BAR/katrain/KataGo/katago" analysis -model "/home/FOO/BAR/katrain/models/g170e-b15c192-s1672170752-d466197061.bin.gz" -config "/home/FOO/BAR/katrain/KataGo/analysis_config.cfg" -analysis-threads 12': '"/home/FOO/BAR/katrain/KataGo/katago" analysis -model "/home/FOO/BAR/katrain/models/g170e-b15c192-s1672170752-d466197061.bin.gz" -config "/home/FOO/BAR/katrain/KataGo/analysis_config.cfg" -analysis-threads 12'.

We need this?

~~~
--- a/katrain/core/engine.py
+++ b/katrain/core/engine.py
@@ -76,7 +76,7 @@ class KataGoEngine:
             elif not os.path.isfile(cfg):
                 self.katrain.log(i18n._("Kata config not found").format(config=cfg), OUTPUT_ERROR)
                 return  # don't start
-            self.command = f'"{exe}" analysis -model "{model}" -config "{cfg}" -analysis-threads {config["threads"]}'
+            self.command = [exe, "analysis", "-model", model, "-config", cfg, "-analysis-threads", f'{config["threads"]}']
         self.start()

     def start(self):
~~~

**Comment by sanderland** [comment]
Ah yes I was going to test this on linux. it's the shlex.split vs shell=True issue again.

**Comment by sanderland** [comment]
please check 2758e93

**Comment by sanderland** [comment]
please check c7c2975

**Comment by kaorahi** [comment]
c7c2975 works fine on Debian GNU/Linux stable (buster). thx!
