### ISSUE TITLE
The KaTrain turns weaker after update from 1.33 to 1.4, when they have the same GPU weight!

### ISSUE THREAD

**Issue by HackYardo** [sanderland/katrain#191]
- I know that **ver1.4** is **only for CPU**, so maybe weaker than before.

- But **ver1.4** have a **new feature to download other weights**. 

- However, when I use the GPU weight **replace** the CPU weight, **its power of Baduk becomes weaker than ver1.33**, whose weight is **the same GPU weight**!

**Comment by sanderland** [comment]
v1.4 is not only for CPU, the defaults have not changed. It only adds an option to easily run on CPU only.
Please specify which weights are used and how you think it is weaker.

**Comment by HackYardo** [comment]
> v1.4 is not only for CPU, the defaults have not changed. It only adds an option to easily run on CPU only. Weights and katago binary are also independent, there is no such thing as 'cpu weights'
> Please specify which weights are used and how you think it is weaker.

![image](https://user-images.githubusercontent.com/57677458/92977965-ffc1a380-f4c0-11ea-9d8b-b5ace520d254.png)

- It's my fault to use wrong words. My meaning is **the same model and GPU KataGo exe**. (Frankly, I'm not sure whether this exe is the same to the ver1.33 default exe) 

- How to know  ver1.4 turns weaker: 
    ver1.33 vs Golaxy-P★★★   
              5  :  0
    ver1.4   vs Golaxy-P★★★
              2  :  3
(P★★★ is the level of Golaxy with 4000 gorating)

**Comment by sanderland** [comment]
v1.4 uses katago 1.6.1 and v1.3.3 uses katago 1.6, the main difference should be memory use in the cpu version.
5 games is a low sample, but I suspect you may have used the 20b network for the 5-0 wins instead of the 15b shown in the screenshot.

**Comment by HackYardo** [comment]
> 
> 
> v1.4 uses katago 1.6.1 and v1.3.3 uses katago 1.6, the main difference should be memory use in the cpu version.
> 5 games is a low sample, but I suspect you may have used the 20b network for the 5-0 wins instead of the 15b shown in the screenshot.

Maybe something wrong in my disk files (config.json?), I find KaTrain takes very little time in playing Baduk, no matter how much time and how many visits I set. And its power of Baduk becomes weaker than Golaxy-P★★★, whose gorating is static 4000.

The reason why my disk files wrong, may caused by I run v1.34 and v1.40 at the same time.

Now I delete c:\users\xxx\\.katrain, unzip Katrain.zip and run it again, it can easily defeat Golaxy-P★★★!
![图片](https://user-images.githubusercontent.com/57677458/93008516-2e667980-f5a8-11ea-8fed-65cfbd69bb26.png)
All is well.
