### ISSUE TITLE
Cannot see refutation in teaching games if "Next Moves" is disabled

### ISSUE THREAD

**Issue by kaorahi** [sanderland/katrain#193]
`msgid "teaching undo message"` says "hover over the move to see expected refutation". But it doesn't work if "Next Moves" (`msgid "analysis:nextmoves"`) is disabled. I was confused until I found this condition.

How about enabling "Next Moves" automatically in teaching games (or adding a message to suggest "q" key)?

**Comment by sanderland** [comment]
I made an improvement yesterday that shows point loss ('e') for undone moves - it seems to help even if 'q' is disabled (4f24e2e)

**Comment by kaorahi** [comment]
Yes. I know it. But I never thought I need to enable "Next Moves" when I want to see the refutation. It may be kind for users to insert something like `(Push q key to enable Next Moves if you cannot see the refutation.)` into `msgid "teaching undo message"`.

I'm only afraid this behavior may be confusing for beginners. It is not a serious problem for me actually. :)

**Comment by sanderland** [comment]
still not sure what you mean, this is what it looks like for me in 1.4.1
![works](https://user-images.githubusercontent.com/48946947/92994609-20f3b580-f4fc-11ea-94fe-0c0896bbde8d.gif)

**Comment by kaorahi** [comment]
Oh, sorry. 4f24e2e works!
