### ISSUE TITLE
Anyone here runs Katrain on a laptop with AMD Cpu ?

### ISSUE THREAD

**Issue by kagami108** [sanderland/katrain#197]
So katrain just won't work on my laptop with AMD athlon 3150u cpu but works fine on my other laptop with an intel i3 Cpu. Other than that the AMD cpu runs other Go ai programs that can run katago like Lizzie, Lizgoban, Sabaki works completely fine, but for some funny reason katago 15b just won't run even though katago 6b,10b and 20b works. 

I have no idea what is going on here but i suspect it has something to do with OpenCL. Is this a known issue where Katrain just doesn't work on AMD cpus ?

**Comment by sanderland** [comment]
katrain just calls the katago analysis engine and should work fine if katago works by itself. it's hard to tell what's going wrong without any details, maybe run with console on and debug level=1 in general settings.

**Comment by kagami108** [comment]
> katrain just calls the katago analysis engine and should work fine if katago works by itself. it's hard to tell what's going wrong without any details, maybe run with console on and debug level=1 in general settings.

Did that and left it running for 30 minutes. Its exactly the same as before, where the engine status is orange and stays that way.

**Comment by sanderland** [comment]
It's the console output on startup that might show problems, and it will also show the command for starting katago, which can be used to test that
