### ISSUE TITLE
Move history during analysis visually breaks out of box

### ISSUE THREAD

**Issue by e00E** [sanderland/katrain#201]
![image](https://user-images.githubusercontent.com/1462179/93609507-3d945f80-f9cc-11ea-8c67-a36b21b7b720.png)

I didn't do anything special to make this happen, just played some moves. I'm on Linux + Wayland.

**Comment by sanderland** [comment]
very strange, have never seen anything like it. what backend is kivy using (should be in the console, at least when debug level is 1-2)

**Comment by e00E** [comment]
It's using sdl2. The bug is gone when I run with `SDL_VIDEODRIVER=x11` so it's probably an issue with sdl2 or kivy and wayland and not something you can fix in katrain. Feel free to close the issue.

**Comment by sanderland** [comment]
Okay, thanks for sharing the fix
