### ISSUE TITLE
When I open the game record file, the analysis remains on

### ISSUE THREAD

**Issue by hope366** [sanderland/katrain#203]
When I open an sgf file in KaTrain v1.5.0, it automatically turns on analysis and I can't turn it off by pressing the spacebar.

**Comment by sanderland** [comment]
This has been the case since forever, all nodes are analyzed at least once and the spacebar being only for additional analysis. When the fast analysis option is checked (or when dragging and dropping) it should be done quickly though.

**Comment by hope366** [comment]
From my personal point of view, it would be easier to use if the user could do the analysis of the whole game or a partial analysis instead of starting the analysis automatically when the file is read. I will.
Thank you.
