### ISSUE TITLE
Small improvement : Refresh directory when loading new game

### ISSUE THREAD

**Issue by Hou-jicha** [sanderland/katrain#208]
Hello, 

I noticed if I download a game from, let's say fox, into my sgf directory, if Katrain is already open when I want to load this game, my sgf directory is not refreshed and the new sgf file does not appear. I need to exit into another directory and then come back to see the game appear. It would be nice to have either Katrain refresh the directory when we click on load game, or to have maybe a refresh button.

Thanks !

**Comment by sanderland** [comment]
Thanks for the suggestion, this should be fixed in the next version!
