### ISSUE TITLE
Error: Engine died unexpectedly. Possibly due to out of memory

### ISSUE THREAD

**Issue by PatricioClark** [sanderland/katrain#21]
Hi,

I tried running KaTrain using Python 3.6.9 on Ubuntu 18.04 on a Lenovo X1 Carbon (so no dedicated GPU). After a couple of moves I got this error message

[INFO   ] [Logger      ] Record log in /home/pato/.kivy/logs/kivy_20-05-05_4.txt
[INFO   ] [Kivy        ] v1.11.1
[INFO   ] [Kivy        ] Installed at "/home/pato/.local/lib/python3.6/site-packages/kivy/__init__.py"
[INFO   ] [Python      ] v3.6.9 (default, Apr 18 2020, 01:56:04) 
[GCC 8.4.0]
[INFO   ] [Python      ] Interpreter at "/usr/bin/python3"
[INFO   ] [Factory     ] 184 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
xclip version 0.12
Copyright (C) 2001-2008 Kim Saunders et al.
Distributed under the terms of the GNU GPL
[INFO   ] [Clipboard   ] Provider: xclip
[INFO   ] [CutBuffer   ] cut buffer support enabled
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Window      ] Provider: sdl2(['window_egl_rpi'] ignored)
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] Backend used <sdl2>
[INFO   ] [GL          ] OpenGL version <b'3.0 Mesa 19.2.8'>
[INFO   ] [GL          ] OpenGL vendor <b'Intel Open Source Technology Center'>
[INFO   ] [GL          ] OpenGL renderer <b'Mesa DRI Intel(R) UHD Graphics 620 (Kabylake GT2) '>
[INFO   ] [GL          ] OpenGL parsed version: 3, 0
[INFO   ] [GL          ] Shading version <b'1.30'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [GL          ] NPOT texture support is available
Using config file /home/pato/codes/katrain/config.json
/home/pato/codes/katrain/img/icon.png
Starting KataGo with ['KataGo/katago-bs', 'analysis', '-model', 'KataGo/models/b15-1.3.2.txt.gz', '-config', 'KataGo/analysis_config.cfg', '-analysis-threads', '8']
Sending query QUERY:1: {"rules": "japanese", "priority": -999999, "analyzeTurns": [0], "maxVisits": 500, "komi": 6.5, "boardXSize": 19, "boardYSize": 19, "includeOwnership": true, "includePolicy": true, "moves": [], "overrideSettings": {"maxTime": 3.0}, "id": "QUERY:1"}
[INFO   ] [ProbeSysfs  ] device match: /dev/input/event4
[INFO   ] [MTD         ] Read event from </dev/input/event4>
[INFO   ] [Base        ] Start application main loop
[WARNING] [MTD         ] Unable to open device "/dev/input/event4". Please ensure you have the appropriate permissions.
2020-05-05 12:19:10-0400: Analysis Engine starting...
2020-05-05 12:19:10-0400: KataGo v1.3.5+bs29 (special board size 29 version)
2020-05-05 12:19:10-0400: nnRandSeed0 = 15025222834647999029
2020-05-05 12:19:10-0400: After dedups: nnModelFile0 = KataGo/models/b15-1.3.2.txt.gz useFP16 auto useNHWC auto
Sending query QUERY:2: {"rules": "japanese", "priority": 1, "analyzeTurns": [1], "maxVisits": 500, "komi": 6.5, "boardXSize": 19, "boardYSize": 19, "includeOwnership": true, "includePolicy": true, "moves": [["B", "Q16"]], "overrideSettings": {"maxTime": 3.0}, "id": "QUERY:2"}
terminate called after throwing an instance of 'StringError'
  what():  OpenCL error at /home/dwugcloud/data/kata/cpp/neuralnet/openclhelpers.cpp, func err, line 188, error CL_PLATFORM_NOT_FOUND_KHR
Sending query QUERY:3: {"rules": "japanese", "priority": 1, "analyzeTurns": [2], "maxVisits": 500, "komi": 6.5, "boardXSize": 19, "boardYSize": 19, "includeOwnership": true, "includePolicy": true, "moves": [["B", "Q16"], ["W", "D4"]], "overrideSettings": {"maxTime": 3.0}, "id": "QUERY:3"}
ERROR: Engine died unexpectedly, possibly due to out of memory: [Errno 32] Broken pipe

Let me know if I'm missing any information. Thanks!!

**Comment by sanderland** [comment]
```
terminate called after throwing an instance of 'StringError'
what(): OpenCL error at /home/dwugcloud/data/kata/cpp/neuralnet/openclhelpers.cpp, func err, line 188, error CL_PLATFORM_NOT_FOUND_KHR
```

is the error, it's in KataGo/OpenCL and I've seen it before. You can try a binary with a board size limit of 19, use the 10b model, or try the cuda version if it's supported for your hardware. As the KataGo readme says though, integrated graphics are a bit hit-and-miss.

**Comment by sanderland** [comment]
actually, this has some drivers you can try: https://www.wst.space/fix-hashcat-cl_platform_not_found_khr/

**Comment by sanderland** [comment]
I think I am tracking down the cause. Please try decreasing nnMaxBatchSize in the cfg config (repeatedly half, all the way down to 1 if needed)

**Comment by PatricioClark** [comment]
Decreasing the batch size and/or changing the model (to b10) did not work. I should just probably try to get  build KataGo myself, but I know about the problems with integrated grahics. Thanks!

**Comment by sanderland** [comment]
Could you try the binary in this branch? https://github.com/sanderland/katrain/pull/22

**Comment by PatricioClark** [comment]
Same problem, even after further decreasing the batch size.

**Comment by kinsho6i7h** [comment]
I have the same issue

**Comment by sG4ZvHrf** [comment]
I also get this error on KaTrain 1.5.0.
```pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
[WARNING] [Deprecated  ] Pygame has been deprecated and will be removed after 1.11.0: Call to deprecated function __init__
ages/kivy/core/__init__.py line 70 by core_select_lib().
[WARNING] [Deprecated  ] Pygame has been deprecated and will be removed after 1.11.0: Call to deprecated function __init__ in /home/<my username>/.local/lib/python3.9/site-packages/kivy/core/image/img_pygame.py line 27.Called from /home/<my username>/.local/lib/python3.9/site-packages/kivy/core/image/__init__.py line 460 by load().
Using user config file /home/<my username>/.katrain/config.json
[WARNING] [Deprecated  ] Pygame has been deprecated and will be removed after 1.11.0: Call to deprecated function __init__ in /home/<my username>/.local/lib/python3.9/site-packages/kivy/core/text/text_pygame.py line 36.Called from /home/<my username>/.local/lib/python3.9/site-packages/kivy/uix/label.py line 349 by _create_label().
[WARNING] [Audio       ] Unable to find a loader for </home/<my username>/.local/lib/python3.9/site-packages/katrain/sounds/stone1.wav>
[WARNING] [Audio       ] Unable to find a loader for </home/<my username>/.local/lib/python3.9/site-packages/katrain/sounds/stone2.wav>
[WARNING] [Audio       ] Unable to find a loader for </home/<my username>/.local/lib/python3.9/site-packages/katrain/sounds/stone3.wav>
[WARNING] [Audio       ] Unable to find a loader for </home/<my username>/.local/lib/python3.9/site-packages/katrain/sounds/stone4.wav>
[WARNING] [Audio       ] Unable to find a loader for </home/<my username>/.local/lib/python3.9/site-packages/katrain/sounds/stone5.wav>
[WARNING] [Audio       ] Unable to find a loader for </home/<my username>/.local/lib/python3.9/site-packages/katrain/sounds/countdownbeep.wav>
[WARNING] [Deprecated  ] Pygame has been deprecated and will be removed after 1.11.0: Call to deprecated function __init__ in /home/<my username>/.local/lib/python3.9/site-packages/kivy/core/text/text_pygame.py line 36.Called from /home/<my username>/.local/lib/python3.9/site-packages/kivy/core/text/markup.py line 94 by __init__().
2020-10-20 13:41:59+0900: Analysis Engine starting...
2020-10-20 13:41:59+0900: KataGo v1.6.1 (Minified version for KaTrain v1.4)
2020-10-20 13:41:59+0900: nnRandSeed0 = 15112041253096541560
2020-10-20 13:41:59+0900: After dedups: nnModelFile0 = /home/<my username>/.local/lib/python3.9/site-packages/katrain/models/g170e-b15c192-s1672170752-d466197061.bin.gz useFP16 auto useNHWC auto
[WARNING] [Deprecated  ] Pygame has been deprecated and will be removed after 1.11.0: Call to deprecated function __init__ in /home/<my username>/.local/lib/python3.9/site-packages/kivy/core/text/text_pygame.py line 36.Called from /home/<my username>/.local/lib/python3.9/site-packages/kivy/uix/textinput.py line 2250 by _get_line_options().
[WARNING] [Deprecated  ] Pygame has been deprecated and will be removed after 1.11.0: Call to deprecated function __init__ in /home/<my username>/.local/lib/python3.9/site-packages/kivy/core/text/text_pygame.py line 36.Called from /home/<my username>/.local/lib/python3.9/site-packages/katrain/gui/kivyutils.py line 574 by draw_text().
terminate called after throwing an instance of 'StringError'
what():  OpenCL error at /app/neuralnet/openclhelpers.cpp, func err, line 263, error CL_PLATFORM_NOT_FOUND_KHR
ERROR: Engine died unexpectedly without sending output, possibly due to out of memory: status -6
```
For reference, my Python version is 3.9.0, I'm using Void Linux with kernel 5.8.16_1.
My hardware is a Ryzen 7 3700X (Zen 2 CPU) and Radeon 5700 XT (Navi 10 GPU).

I have not tried decreasing batch size yet.

**Comment by sG4ZvHrf** [comment]
I figured out I was being dumb and didn't have `mesa-opencl` installed on my system. I am no longer getting the error at
```
what():  OpenCL error at /app/neuralnet/openclhelpers.cpp, func err, line 263, error CL_PLATFORM_NOT_FOUND_KHR
```
but instead at
```
2020-10-20 13:59:07+0900: Done tuning, saved results to /home/<my username>/.katrain/opencltuning/tune8_gpuAMDRadeonRX5700XTNAVI10DRM338058161LLVM1000_x19_y19_c192_mv8.txt
terminate called after throwing an instance of 'OpenCLHelpers::CompileError'
what():  CL_BUILD_PROGRAM_FAILURE
BUILD LOG FOR conv2dNCHWProgram ON DEVICE 0
fatal error: cannot open file '/usr/lib/clc/gfx1010-amdgcn-mesa-mesa3d.bc': No such file or directory


ERROR: Engine died unexpectedly without sending output, possibly due to out of memory: status -6
```

**Comment by peepo** [comment]
on ubuntu 20.04 sudo apt-get install mesa-opencl-icd removed CL_PLATFORM_NOT_FOUND_KHR

however "no OpenCL devices were found.. bugy drivers" remains

**Comment by aahlad0** [comment]
I am seeing this on a mac - Catalina 10.15.7 - complete message is "engine died unexpectedly without sending output: status -6". Also, upon "Download Models", Error: ([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129))

**Comment by deegeebee** [comment]
First let me say I'm sort of happy (in my misery Kata won't start) that it's not only that I'm too stupid to run it.
Just to add another error message (is this of any use??):
ERROR: KataGo Engine Failed: OpenCL error at /home/dwugcloud/data/kata/cpp/neuralnet/openclhelpers.cpp, func err, line 263, error CL_PLATFORM_NOT_FOUND_KHR

Do I get this thread right that this is about hardware and drivers and maybe nothing can be fixed, especialIy not by a future katrain version? :(

**Comment by peepo** [comment]
an FAQ could be good, or troubleshooter page...
in the meantime try: https://github.com/sanderland/katrain/issues/373
x:"
