### ISSUE TITLE
Feature request: move value compared to passing

### ISSUE THREAD

**Issue by pdeblanc** [sanderland/katrain#210]
I'd like to know how many points a move is worth, i.e. how much better it is than passing.

Currently I can do this by adding a pass move, looking at the points lost, and mentally adding it to the value of the move I'm considering. However, it's be nice to see it printed directly on the stone.

Also, I'd like to be able to see a graph of temperature, defined as the point value of the best move on the board.

(Aside: I find the points lost to actually be a slight underestimate, e.g. 13.2 points lost for passing the first move, which should logically be twice komi = 14 points. I can get a more accurate estimate in Lizzie by manually adjusting the komi until the expected score is close to 0.)

**Comment by sanderland** [comment]
Earlier versions were based on temperature, giving your move efficiency in percent (point worth/temperature) -- eventually I moved away from it as it breaks easily in endgame and it was less useful than expected. 
Komi is 6.5, and 13.2 ~ 13 so it seems fine. KataGo does exactly this by the way, scoreLead is the komi adjustment to make the game equal.

**Comment by pdeblanc** [comment]
Sorry, I was referring to Chinese rules with komi of 7. If I repeat the experiment with Japanese rules and a komi of 6.5, a pass is evaluated as losing 12.3 points, which is well short of 13.

Let me explain a use case. When I'm playing a live game, I might be faced with a choice between moves A and B in two different parts of the board. Then if I've previously learned from KataGo that e.g. A is worth 7 points and B is worth 6 points, I would know to play A, even if I've never seen KataGo directly compare these two moves within the same board position. This use case would not have been satisfied by efficiency (point worth/temperature) -- only by knowing the absolute point value of the move.

**Comment by sanderland** [comment]
> Sorry, I was referring to Chinese rules with komi of 7. If I repeat the experiment with Japanese rules and a komi of 6.5, a pass is evaluated as losing 12.3 points, which is well short of 13.

sure, but it also evaluates the empty board as W+0.3

> Let me explain a use case. When I'm playing a live game, I might be faced with a choice between moves A and B in two different parts of the board. Then if I've previously learned from KataGo that e.g. A is worth 7 points and B is worth 6 points, I would know to play A, even if I've never seen KataGo directly compare these two moves within the same board position. This use case would not have been satisfied by efficiency (point worth/temperature) -- only by knowing the absolute point value of the move.

What I found is that temperature is surprisingly constant for most of the opening and early middle game in the absence of fighting, and most reasonable opening moves incur a loss < 0.5 points.
Your imagined scenario, that B is worth 6 points AND optimal (without showing up as "1 point lost") doesn't typicaly seem to happen.

**Comment by pdeblanc** [comment]
Err, I was imagining an endgame scenario where A, valued at 7 points, is the optimal move, and B, valued at 6 points, is a suboptimal move. I'm imagining that I'm playing a live game, without access to KataGo, but I have previously memorized these values (7 and 6 points) because I saw similar moves in other games before, and KataGo taught me those numbers.

**Comment by pdeblanc** [comment]
> sure, but it also evaluates the empty board as W+0.3

That's already included. When I said a pass is losing 12.3 points, I mean Katrain showed `Points Lost B: 12.3`. I was not referring to an estimated score of 12.3.

**Comment by sanderland** [comment]
In any case, the pass query for every move was a major pain in implementation and slows things down, so it's unlikely to come back.
