### ISSUE TITLE
Feature request: darker board

### ISSUE THREAD

**Issue by pdeblanc** [sanderland/katrain#211]
When visualizing expected territory, I find the light-colored squares much less visible than the dark-colored squares, presenting the impression that black has more influence than white. I think a darker wood texture would fix this (although adjusting the square opacity might also be a viable solution).

**Comment by sanderland** [comment]
themes have been requested but are not on my todo list, although you're welcome to PR them.
the idea of checking if white and black could be made visually look similar in strength is interesting, and I'd welcome any results you have on this.
