### ISSUE TITLE
Komi problem

### ISSUE THREAD

**Issue by k8477en** [sanderland/katrain#212]
I've loaded a game I played the other day with komi of 6.5, yet the katrain 1.5 didn't give it a right one and return to 0.0 komi.

Here's the sgf file.  And I hope you can help me fix this.  Thanks!

[FineArt_[rimshoot]vs[刺猬010203]1601019342010001527.zip](https://github.com/sanderland/katrain/files/5301039/FineArt_.rimshoot.vs.010203.1601019342010001527.zip)

**Comment by sanderland** [comment]
It says `KM[0]HA[0]AP[GNU Go:3.8]` right there. This looks like a foxwq game which has been re-saved in gnugo.
FoxWQ produces terribly broken SGF files, for which there are workarounds, but only when the file actually contains AP[foxwq]
