### ISSUE TITLE
Clunky/unresponsive when playing variations

### ISSUE THREAD

**Issue by milescrawford** [sanderland/katrain#214]
The main reason I have not switched to Katrain from Lizzie is that when playing variations in analysis, there is a significant lag before Katrain displays (or subsequently refines) likely territory, suggested moves, etc.

This makes it very unnatural and tedious to play out variations. By contrast, Lizzie instantaneously adjusts its display, and refines smoothly as more visits occur. Playing out variations, backing up, trying new things is snappy and gives good feedback quickly.

I have reduced the max visits/max time settings, but the lag persists. I'm not sure if this is a necessary consequence of using the katago batch analysis protocol rather than the streaming GTP interface or due to some other implementation decision in Katrain, but it is one way in which Katrain could make a great improvement!

**Comment by sanderland** [comment]
This is likely an effect of the analysis engine. There is a PR in KataGo which makes it report back regularly, this is likely to improve things.

**Comment by sanderland** [comment]
fixed in 1.5.1

**Comment by milescrawford** [comment]
I don't seem to have permission to reopen this, but I don't consider this fixed in 1.5.1. I do think things are better, but it's still a much worse experience than playing with other programs using the GTP connection.

**Comment by sanderland** [comment]
If you could record yourself using it and pointing out what specifically seems off that would help. The updates should come in every 0.25s now which seems smooth enough for me. If you have a slow machine and are trying variations, one cause may be that it's still finishing other moves' analyses.
