### ISSUE TITLE
Another criterion of settledness

### ISSUE THREAD

**Issue by kaorahi** [sanderland/katrain#215]
I post this comment since I noticed the new AI strategy "Simple Style" in v1.5.1 branch.

As an indicator of the board atmosphere in lizgoban, I have been using `U = \sum (1 - abs(ownership(i,j)))` over all coordinates (i,j) of "existing stones" on the board. The red dots in the screenshot indicate progress of U through a game. In my impression, this U well matches my feeling of unsettledness.

![unsettled](https://user-images.githubusercontent.com/38910552/95665538-4e2f9400-0b8c-11eb-94cf-d51d7c345924.png)

* It increases from the opening to the middlegame, and decreases in the endgame.
* It increases in large battles, especially in ko fights, and decreases when stones are clearly alive or dead.
* It tends to be large in KataGo's handicap games because of many large Miai.
* It tends to be large in recent professional games and small in old Japanese championships before 1990.

How about using this criterion instead of the current definition of settledness in "Simple Style"? I am also interested in a berserker style that tries to maximize U.

**Comment by sanderland** [comment]
Yes it is very early testing, your idea is interesting, but it doesn't seem like a very 'strong' criterion since if the only effect is on the last stone played, the difference will be quite small.
I may try a few different variants and make a pre-release where people can test them for me.

https://online-go.com/player/768720/katrain-balanced has some experiments with 'berserker' mode and it is scary.

**Comment by sanderland** [comment]
testing in 2bf1846

https://gokibitz.com/kifu/By1MsIePv
https://gokibitz.com/kifu/B1xfoUxPP
https://gokibitz.com/kifu/ByxgfsIewP
https://gokibitz.com/kifu/HJZfoIevw

**Comment by kaorahi** [comment]
thx!

Expecting a berserker or a chaos lover, I built katago b9ce89c3 in the master branch, modified katrain/core/constants.py in 2bf1846 as

~~~
-    "settled_weight": [x / 4 for x in range(0, 17)],
+    "settled_weight": [x / 4 for x in range(-20, 17)],
~~~

and tried ai:settle on settled_weight=-5, opponent_fac=1, attachment_penalty=0, tenuki_penalty=0 with max_points_lost=5, min_visits=3, wide_root_noise=0.1. But AI's moves seemed quite regular. I may need to increase max_time as my machine is slow.

**Comment by sanderland** [comment]
Note that you don't need to edit constants.py to go outside the range, the text box accepts pretty much anything. Low visits could be an issue, yes.

**Comment by sanderland** [comment]
This is what happens for me on those settings: https://gokibitz.com/kifu/ByB0QAWwD

**Comment by sanderland** [comment]
Deprecated due to lack of feedback
