### ISSUE TITLE
Feature Request: Localized Analysis for Local Variations

### ISSUE THREAD

**Issue by Giannechini** [sanderland/katrain#216]
It would be really cool if you could implement a local analysis region on the board, so the AI would only search for moves in the highlighted area. It would be very helpful when looking at local variations where the AI likes to tenuki. I believe the android app 'Lazy Baduk' has this functionality, but I'm not sure how difficult it would be to implement. As always amazing work, I use this program to analyze my games every time I play!

**Comment by sanderland** [comment]
Find alternative moves is sort of meant for this, the first use of that will usually give you a local response.
A specialized option which only does this is possible by just telling kata to avoid all non-local moves. The hardest part is defining 'local'.

**Comment by Giannechini** [comment]
That's a great tip, I'll check that out more closely. Very good point, I
think the app let you drag a box to define the area on the board that you
wanted to let the analysis run on (which I assume would also speed up the
analysis?). But that seems like it could introduce some GUI issues. Anyway,
thank you for the response!

-Lucca

**Comment by hemme** [comment]
Maybe this could be implemented as a semi-automated process where the user draws a selection rectangle on a portion of a board
and the app copy-n-paste the selected stones to a new KaTrain instance.

**Comment by sanderland** [comment]
1.6 has some find local response option, fixed region for now as drawing boxes gets a bit complicated.

**Comment by Giannechini** [comment]
That sounds awesome, looking forward to the release. Thanks for the update!

-Lucca
