### ISSUE TITLE
Dealing with sgf file with No Komi property.

### ISSUE THREAD

**Issue by simonguoxm** [sanderland/katrain#218]
I played a 7x7 game on OGS with AGA rule and Komi is zero. 

When I analysis this game with KaTrain, I found that KaTrain shows komi 6.5 in the beginning. 

I double checked the sgf file, and there is no KM property. 

Looks like KaTrain add a (default) value when analysis a sgf.  

My suggestion is to set it as 0 if no KM property is found.

![image](https://user-images.githubusercontent.com/4695131/96220368-39694c80-0f4e-11eb-9e74-3bd9ca651d25.png)

**Comment by sanderland** [comment]
I tried no komi property on OGS and it uses the most common values (6.5 jp, 7.5 cn) so my defaults don't seem too unusual.
Would being able to edit komi (e.g. through a button in new game which says 'only edit settings') help?

**Comment by simonguoxm** [comment]
yes, definitely can add KM property by my editor.

**Comment by sanderland** [comment]
edit in new game added
