### ISSUE TITLE
Feature request: keyboard shortcuts for fast game navigation

### ISSUE THREAD

**Issue by hemme** [sanderland/katrain#219]
It should be nice if the following keyboard acted as shortcuts for game navigation:

`[Home]` => go to start - gui button: `|<`
`[Page Up]` => rewind 5 moves - gui button:  `<<`
`[Page Down]` => forward 5 moves - gui button:  `>>`
`[End]` => go to end - gui button:  `>| `

**Comment by sanderland** [comment]
these are now under ctrl/alt + right/left, but home and end seem reasonable to add.
