### ISSUE TITLE
Feature Request: Randomize Starting Color

### ISSUE THREAD

**Issue by sG4ZvHrf** [sanderland/katrain#222]
Can there be an option to randomize whether the player starts as black or white?

**Comment by GopherAl** [comment]
Flipping a coin and entering the result in Player Setup works for me.

**Comment by sanderland** [comment]
I don't think it fits in, given how it doesn't really care about there being 1 player and 1 ai to begin with. The coin flip works ;)

**Comment by sG4ZvHrf** [comment]
>it doesn't really care about there being 1 player and 1 ai to begin with

True.

Then, perhaps an option to easily swap the values of the Player type and Game Type/AI Strategy between black and white? Even if a coin flip is used to choose players, setting the values takes an extra 5 seconds or so every time.

**Comment by sanderland** [comment]
-> issue #42
