### ISSUE TITLE
Feature request: Life and death solving

### ISSUE THREAD

**Issue by obwohl** [sanderland/katrain#226]
First: What a great software!

It would be nice to have a companion for solving complicated life and death problems. I don't know it this is more a problem of Katrain or Katago but I think it would be huge to have it.

**Comment by simonguoxm** [comment]
I already use Katrain to do Life and Death problem.

**Comment by obwohl** [comment]
How do you do this?

**Comment by simonguoxm** [comment]
usually I put that L&D problem on a 7x7 or 9x9 board. Then load this sgf in KaTrain.

**Comment by sanderland** [comment]
What @simonguoxm said, otherwise duplicate of #216
