### ISSUE TITLE
installation problem on Debian

### ISSUE THREAD

**Issue by ghistes** [sanderland/katrain#227]
Hi,

I am having problems installing on Debian testing, my python-version (could this be the problem?) is 3.8.2

When trying to install via pip I get this errors:

```> pip3 install katrain
Collecting katrain
  Using cached https://files.pythonhosted.org/packages/9d/17/4e7972925e0cd82542e5feaa0129821133b6a16ac8235ddb41321cfa0431/KaTrain-1.5.0-py3-none-any.whl
Collecting kivy==2.0.0rc2 (from katrain)
  Using cached https://files.pythonhosted.org/packages/01/57/aae0abdf40f89f3535eeb6f9611a8b6efe86a44a785cec7efa92f60b1d85/Kivy-2.0.0rc2.tar.gz
  Installing build dependencies ... error
  Complete output from command /usr/bin/python3 -m pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-u3urvt_8 --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel cython>=0.24,<=0.29.14,!=0.27,!=0.27.2 "kivy_deps.gstreamer_dev~=0.2.0; sys_platform == \"win32\"" "kivy_deps.sdl2_dev~=0.2.0; sys_platform == \"win32\"" "kivy_deps.glew_dev~=0.2.0; sys_platform == \"win32\"" "kivy_deps.gstreamer~=0.2.0; sys_platform == \"win32\"" "kivy_deps.sdl2~=0.2.0; sys_platform == \"win32\"" "kivy_deps.glew~=0.2.0; sys_platform == \"win32\"":
  Ignoring kivy-deps.gstreamer-dev: markers 'sys_platform == "win32"' don't match your environment
  Ignoring kivy-deps.sdl2-dev: markers 'sys_platform == "win32"' don't match your environment
  Ignoring kivy-deps.glew-dev: markers 'sys_platform == "win32"' don't match your environment
  Ignoring kivy-deps.gstreamer: markers 'sys_platform == "win32"' don't match your environment
  Ignoring kivy-deps.sdl2: markers 'sys_platform == "win32"' don't match your environment
  Ignoring kivy-deps.glew: markers 'sys_platform == "win32"' don't match your environment
  Collecting setuptools
    Using cached https://files.pythonhosted.org/packages/6d/38/c21ef5034684ffc0412deefbb07d66678332290c14bb5269c85145fbd55e/setuptools-50.3.2-py3-none-any.whl
  Collecting wheel
    Using cached https://files.pythonhosted.org/packages/a7/00/3df031b3ecd5444d572141321537080b40c1c25e1caa3d86cdd12e5e919c/wheel-0.35.1-py2.py3-none-any.whl
  Collecting cython!=0.27,!=0.27.2,<=0.29.14,>=0.24
    Using cached https://files.pythonhosted.org/packages/fc/38/990d837843c724201ea662ed2994709aee95f53a1226ded0638e71bb46ca/Cython-0.29.14-cp38-cp38-manylinux1_x86_64.whl
  Installing collected packages: setuptools, wheel, cython
  Exception:
  Traceback (most recent call last):
    File "/usr/lib/python3/dist-packages/pip/_internal/cli/base_command.py", line 143, in main
      status = self.run(options, args)
    File "/usr/lib/python3/dist-packages/pip/_internal/commands/install.py", line 377, in run
      installed = install_given_reqs(
    File "/usr/lib/python3/dist-packages/pip/_internal/req/__init__.py", line 45, in install_given_reqs
      requirement.install(
    File "/usr/lib/python3/dist-packages/pip/_internal/req/req_install.py", line 757, in install
      self.move_wheel_files(
    File "/usr/lib/python3/dist-packages/pip/_internal/req/req_install.py", line 374, in move_wheel_files
      move_wheel_files(
    File "/usr/lib/python3/dist-packages/pip/_internal/wheel.py", line 213, in move_wheel_files
      scheme = distutils_scheme(
    File "/usr/lib/python3/dist-packages/pip/_internal/locations.py", line 165, in distutils_scheme
      i.finalize_options()
    File "/usr/lib/python3.8/distutils/command/install.py", line 269, in finalize_options
      raise DistutilsOptionError(
  distutils.errors.DistutilsOptionError: must supply either home or prefix/exec-prefix -- not both

  ----------------------------------------
Command "/usr/bin/python3 -m pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-u3urvt_8 --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel cython>=0.24,<=0.29.14,!=0.27,!=0.27.2 "kivy_deps.gstreamer_dev~=0.2.0; sys_platform == \"win32\"" "kivy_deps.sdl2_dev~=0.2.0; sys_platform == \"win32\"" "kivy_deps.glew_dev~=0.2.0; sys_platform == \"win32\"" "kivy_deps.gstreamer~=0.2.0; sys_platform == \"win32\"" "kivy_deps.sdl2~=0.2.0; sys_platform == \"win32\"" "kivy_deps.glew~=0.2.0; sys_platform == \"win32\""" failed with error code 2 in None
```

So it seems it tries to install kivy but fails (again - is my python to new?), even though I have installed a python3-kivy library via aptitude.

What could be the problem here?

Many thanks!

**Comment by sanderland** [comment]
It looks like your cython and pip clash for some reason, very strange. If you have kivy and kivymd installed you could try cloning the repo and just starting with `python -m katrain` in the directory.

**Comment by ghistes** [comment]
Could you please elaborate a bit more on pip and cython "clashing" (I have no experience at all with cython).

Unfortunately kivymd is not available in the repos and installing it via pip just failed (I may have some depenencies missing).

But I am not 100% sure but I think there once was an issue that kivy would not work with Python 3.8 ...

So could you confirm that kivy and katrain should work with my Python-version?

Many thanks!

**Comment by sanderland** [comment]
I've gotten it to run in a 3.8 venv, I believe the main problem is that there is no wheel so you need `pip3 install --no-binary kivy kivy==2.0.0rc2`
Your error however seems deeper than that, and is on dependencies of dependencies. I can only suggest making a fresh virtual environment and installing in that to not deal with OS packages+python packages clashing.

**Comment by reinierpost** [comment]
I just had similar problems on Ubuntu 18.04. Following the Linux installation instructions is not good enough.
What I did to fix it (not sure if all of these are necessary or even make sense):

- `sudo apt install cython3` as something was complaining about a dependency on cython failing

Now  `pip3 install -U katrain` worked, but  `python3 -m katrain` threw several errors, including one about missing `pygame`, and: _Unable to find any valuable Window provider._

- `sudo apt install python3-kivy`

This didn't fix the problems.

- `pip3 install --no-binary kivy kivy`
Didn't fix the problems.

- `pip3 install kivymd`
- `pip3 install pygame`
After that, Now  `pip3 install -U katrain` started the GUI with no issues except warnings about missing `stone*.wav` files.

**Comment by ghistes** [comment]
I got it to work in a new venv.
I still don't understand what is happening above, but I assume it is some quirk in my environment and not a katrain-issue...

**Comment by munen** [comment]
I'm running Debian bullseye/sid with no special Python setup (no venvs or anything since I'm not a Python developer). I just have the regular Debian packages `python` (2.7.17-2) and `python3` (3.9.0-4) installed with my path defaulting to Python 2. I have `pip` via the `python3-pip` package (20.1.1-2). 

Katrain installed fine as documented in the readme with `pip install katrain`.

I'm assuming this is not a Debian issue, but a more complicated Python setup issue with custom Python versions involved.
