### ISSUE TITLE
Feature request: Simple time delay for AI moves

### ISSUE THREAD

**Issue by tifen1** [sanderland/katrain#229]
It would be nice to set a time delay for AI responses. It could be as simple as being able to select a random response time between a min/max value of seconds.

Psychologically it is a bit unnerving playing against someone who always responds within a second (even if it's an AI).

**Comment by sanderland** [comment]
Believe it or not, there already is an extra small delay before playing the sound of the ai move to reduce the response time a bit.
Delaying the move however is surprisingly difficult without introducing all sorts of nasty edge cases, so will mark this as wont-fix.
