### ISSUE TITLE
dependency on pygame missing

### ISSUE THREAD

**Issue by ghistes** [sanderland/katrain#230]
Hi,

I am using python 3.8.2 on Debian testing and just installed katrain in a new virtual enviroment via "pip3 install katrain".
I then tried to launch it via "python3 -m katrain".
This resulted in an error.

I then installed pygame into this environment and that made katrain work.

So it looks to me (not really knowing much about python) as if the depency on pygame is not properly reflected.

**Comment by sanderland** [comment]
kivy runs on one of several backends, usually SDL2. kivy for py3.7 and pygame for all versions comes with pre-built sdl2 libraries and can help if sdl2 is missing from the system. it's all a bit of a mess, sadly.
