### ISSUE TITLE
Feature request : identify most important mistakes from game

### ISSUE THREAD

**Issue by domeav** [sanderland/katrain#231]
Hi, and thanks for your very useful program!

When reviewing a sgf game, I'm trying to identify my mistakes. I can do it by clicking on the graph, but it is small and hard to get around with accuracy. I would love the following things:

- a configurable quick game overview with clickable "turning point" moves
- every move "teacher settings colours" in the top-right move browser (below the regular BW stones and move numbers for instance)

I hope this feedback is somewhat useful and not discussed to death somewhere else - I did a quick check but I could easily have missed another issue.

I know next to nothing about the UI toolkit you're using but I am quite proficient in python, so I *might* be able to contribute if my suggestions are sound. Let me know!

**Comment by sanderland** [comment]
* An extra > arrow for 'next mistake' has been suggested, just needs some working out re which thresholds to use.
* every move "teacher settings colours" in the top-right move browser (below the regular BW stones and move numbers for instance)  -> this could work, maybe the outline? it should be fairly manageable for you to play around with this in particular.

**Comment by sanderland** [comment]
Implemented the > arrow
![image](https://user-images.githubusercontent.com/48946947/99194716-82950200-2781-11eb-9333-974d1b98bf2d.png)

**Comment by sanderland** [comment]
Released
