### ISSUE TITLE
problem in full-screen mode with tiling window manager

### ISSUE THREAD

**Issue by ghistes** [sanderland/katrain#232]
Hi,

I run katrain on a full-HD monitor with the i3 window-manager.

When I run katrain as a "floating" window (where the application chooses it's size) it works.

However when I run katrain full-screen in it's own workspace (as I usually run programs) it does not work as mouse-click coordinates are off (e.g. when I click on A19 the stone appears on A17).

I have never seen such a behaviour with other programs under i3, so I assume it is not an issue with i3 but with katrain (or the graphical toolkit it uses).

**Comment by sanderland** [comment]
are button clicks off as well? I bet this is a kivy issue.

**Comment by munen** [comment]
I'm running Debian bullseye/sid with i3 version 4.19-1+b1 with Katrain v1.6.1 installed via `pip`. I cannot reproduce this problem, mouse clicks register fine for me in all window modes.

**Comment by bradwood** [comment]
I am having this exact problem on i3 on manjaro -- @ghistes - did you ever find a solution?

:pray:

**Comment by Chewt** [comment]
Adding that this same problem happens with me on hyprland on endeavourOS. The common thread here seems to be tiling window managers.

**Comment by Chewt** [comment]
Adding an update as I seem to have fixed this issue by following advice from another issue https://github.com/sanderland/katrain/issues/178#issuecomment-683319019

> Did some digging and this seems to be a [known issue](https://github.com/kivy/kivy/issues/5697) with kivy and libinput on linux.
> 
> Workaround suggested there is to edit ~/.kivy/config.ini and change
> 
> ```
> [input]
> mouse = mouse
> %(name)s = probesysfs
> ```
> 
> to
> 
> ```
> [input]
> mouse = mouse
> #%(name)s = probesysfs
> ```
> 
> I can confirm this solves the issue. Unfortunately seems like there is no solution to fix that within the app as far as I can see.

Doing this has fixed the issue for me.
