### ISSUE TITLE
show analysis progress

### ISSUE THREAD

**Issue by paulolops** [sanderland/katrain#236]
Hello, 

First, thanks for this awesome program.
Now I would like to raise a problem I encounter with the "deeper full game analysis" feature :
I cannot find a good way to have a feedback whenever the analysis is finished, or just at what point it is advanced in the process.
The orange dot on the bottom indicating the engine status never turns back to green after a full game analysis is finished, there is no percentage of the analysis progress.

Personally I use this feature only to analyse games I load and because the loaded game is being automatically reviewed when you load it, I use this feature to have a more advanced analysis with more visits.

What I would suggest would be to have a status of the analysis either by adding a percentage or fixing the engine status dot.

Also maybe a possibility of having to choose the number of visits directly from the load menu could be an idea since we could save a step and see when the analysis is finished by looking at the graph (what doesn't work much since the graph is already generated when you use "deeper full game analysis" after a load).

Thanks for your work.

**Comment by sanderland** [comment]
https://imgur.com/a/C8eJBMJ

**Comment by paulolops** [comment]
So as far as I understand it, it is a katrain 1.6 feature ?
I only have to wait for it to be realeased then, thanks for the work.

**Comment by sanderland** [comment]
Yep, or checkout the branch and run from source

**Comment by paulolops** [comment]
Okay, thanks for the help
