### ISSUE TITLE
Adjust Info/Details/Notes type size?

### ISSUE THREAD

**Issue by David53bcg** [sanderland/katrain#237]
The type size within Info/Details/Notes panels is so small as to be barely legible on my Windows 10 machine. The panel tabs are perfect. To judge by the sample screens on GitHub, I had expected panel text to be the same size as the tabs. Can one adjust text size, specifically for KaTrain,without changing the general Windows Display settings and perhaps creating issues elsewhere?

Thank you!

**Comment by sanderland** [comment]
Could you include a screenshot and your settings? The font size is fixed there

**Comment by David53bcg** [comment]
Thanks for your swift reply. Here are a couple of self-explanatory screenshots. 

As to the general Windows display/scale setting, it stands at 250%, so that desktop icons are not too small. I just tried reverting to the recommended 200%: the desktop icons duly shrank, and there was no change on KaTrain (I guess you know this, but I thought it correct to try!)

![2020-11-21 (1)](https://user-images.githubusercontent.com/74424585/99876381-3701ae80-2bee-11eb-8ddd-04c5673a73a0.png)
![2020-11-21](https://user-images.githubusercontent.com/74424585/99876382-38cb7200-2bee-11eb-8ee6-94311ba5b093.png)

**Comment by sanderland** [comment]
Maybe fixed in d7aefe2 and ab84358 - if you can run from source to check that'd be great

**Comment by David53bcg** [comment]
Thanks very much. Am certainly not an advanced techie or coder, though some beginner's experience. Will re-educate myself to the extent of own prior knowledge, then (if you'll permit) revert with dumb question(s) to ensure successful run-and-check!

**Comment by sanderland** [comment]
Released
