### ISSUE TITLE
v1.6.0 Fonts not scaling up within Info/Details/Notes panels

### ISSUE THREAD

**Issue by David53bcg** [sanderland/katrain#243]
Following from Issue #237, thanks for addressing the fonts issue so quickly. Unfortunately v1.6.0 doesn't yet scale the panel fonts on my machine. See attached.

Sorry not to have reverted after a run from source you had suggested. To be honest, I had assumed that installation of Python 3 would make it a relatively simple matter to run the source code, then work out how to add your patches (even if I had to seek advice on that last step). However, several YouTube tutorial videos later and very careful reading of various documentation: no such luck! 

By all means let me know if you'd like me to check another patch, though your advice on how to run them would be much appreciated in that case. Happy to make the effort here if it's helpful.

Either way, thanks. Such a great app, but the vital bits sadly still microscopic!
![2020-11-23](https://user-images.githubusercontent.com/74424585/99996528-c99f7a80-2db3-11eb-9598-e1df6630c81c.png)

**Comment by sanderland** [comment]
Running from source usually means downloading the .zip file of the branch and running with `python -m katrain`
Alternatively, pip install <zip file> also works.

I've had a look at https://kivy.org/doc/stable/api-kivy.metrics.html and it certainly claims it scales with operating system font sizes, but I can't see it actually doing so.
It does mention the environment variable `KIVY_METRICS_FONTSCALE=2` which works, you might want to try that in the newly released 1.6

**Comment by David53bcg** [comment]
Please see attached, which came up once I had downloaded and extracted 1.6. Is this evidence of a running or setup error on my part, somewhere/somehow, or something else? For sujre I didn't amend any of the code: just extracted it as downloaded.

Also, assuming this error is something I can fix (not being a coder!), what should I then be doing with the 'KIVY_METRICS ...'? Should I be using Python IDLE find this line and then change the variable value to '=2'? I used IDLE Find, but couldn't locate this variable at all. If this line is something I need to key in, where/how exactly?

Please bear in mind I'm a complete coding novice!

Many thanks.
![2020-11-23 (3)](https://user-images.githubusercontent.com/74424585/100074516-c13c5380-2e36-11eb-9bff-a2a2ac12394c.png)

**Comment by sanderland** [comment]
seems the requirements weren't installed, try "pip install ." 
`KIVY_METRICS_FONTSCALE` goes in your windows env vars, or via "set KIVY_METRICS_FONTSCALE=2" before running

**Comment by David53bcg** [comment]
I seem to have successfully installed v1.6 using pip install (see attached), but simply can't find any clear guidance online how now to run KaTrain from the cmd prompt (assuming the pip install was okay). For one thing I haven't been able to identify a recognizable path to KaTrain from everything listed on the screen post-install. Of course I know how to run a normal .exe file, but this download seems very different.

Understand I should enter 'set KIVY_METRICS_FONTSCALE=2' first, but what should I enter on the next line in the prompt to run the downloaded stuff? Not for want to looking, I just can't find anything clear enough online telling me what to do ...

If my newbie question - or errors - would take too much of your time to address, inappropriate to GitHub, do feel entirely free to suggest a beginners' forum you think better suited, if there is one.

![2020-11-25 (1)](https://user-images.githubusercontent.com/74424585/100266452-bfaf8000-2f49-11eb-9406-1b6718d4aac9.png)
![2020-11-25 (2)](https://user-images.githubusercontent.com/74424585/100266458-c3db9d80-2f49-11eb-9b97-c62b1d196084.png)

Thanks very much.

**Comment by sanderland** [comment]
Did you try running `katrain` ?

**Comment by David53bcg** [comment]
Having completed a pip install of the source code, I was expecting to see a katrain.py file or katrain folder. None of that, just a katrain.exe file in Python scripts folder. All very confusing to the uninitiated. However, setting Kivy ... =2 in CMD (i.e. locally) then discovered that running katrain. exe did solve the problem - as you had expected would be the case. Thank you!! See attached.
![2020-11-26](https://user-images.githubusercontent.com/74424585/100342004-42315180-2fd5-11eb-83f4-cfbd24b77b76.png)


Should I expect to set Kivy in this way for the foreseeble future, or do you expect KaTrain releases to address this issue further at some point?

Do appreciate your time and patience on this.

**Comment by sanderland** [comment]
good to see it works!

pip installs packages somewhere on a scary long internal path, there's where the katrain folder is. 

you can set the variable in your windows environment variables so you don't need to 'set' all the time. 

I might add a FAQ-entry-that-nobody-reads, but since the issue affects only you I don't see what else to do.

**Comment by David53bcg** [comment]
Okay. Understood. Again, thanks for a really good study tool.
