### ISSUE TITLE
About katago.exe and configuration file

### ISSUE THREAD

**Issue by hope366** [sanderland/katrain#244]
Hello.
Perhaps this is a rudimentary question, but thank you.
* "Katago.exe 1,141KB" is used for KaTrain's built-in katago. This seems to be different from the CUDA version, OpenCL version, and CPU version, but is it something special?
* When I set the configuration file to default_gtp.cfg included in katago-v1.7.0, the following error occurred.
The README.md says "Do keep in mind that KaTrain uses the analysis engine of KataGo, and not the GTP engine."
Does this mean that the config file must be "analysis_config.cfg"?
![無題](https://user-images.githubusercontent.com/63999713/100126210-04430900-2ec1-11eb-92c2-84de94223007.png)

**Comment by sanderland** [comment]
Yes, it needs the analysis config. The exe I compiled myself for smaller size and includes only the analysis engine.

**Comment by hope366** [comment]
Thank you.
