### ISSUE TITLE
ui questions

### ISSUE THREAD

**Issue by adzweig** [sanderland/katrain#245]
I enjoy the app very much. It is just great. Congratulations!! I have two questions / suggestions: 

1) the contrast of the coloured spots on the board that indicate the quality of alternative moves is a tad weak for my eyes / screen. Is it possible to add a  colour version that has a little bit more contrast to the board?

2) Is it possible to increase the length of the sequences shown when hovering above one of the teaching spots of interest. At times I would like the engine to show me a sequence of some additional predicted optimal moves.

**Comment by sanderland** [comment]
1. There is a colour blind mode, see teaching settings.
2. The length of these sequences is straight from the engine and is related to the number of visits to that move. Just hitting spacebar and pondering for a while will increase them.

**Comment by adzweig** [comment]
thanks. But even the color blind version is a tad weak. Could you add another version with even more contrast...

**Comment by sanderland** [comment]
If you give me the colours it shouldn't be too difficult to add. A PR would also work.

**Comment by adzweig** [comment]
I am referring to the indications of the top moves - those without point indications on the spots. It is hard for me to see the yellow and the light green dots. I guess it would be enough to just reduce the transparency (of these dots) a tad.

**Comment by sanderland** [comment]
Ahh sure, I get it. Noted.

**Comment by adzweig** [comment]
many thanks !!
