### ISSUE TITLE
sound not working

### ISSUE THREAD

**Issue by adzweig** [sanderland/katrain#247]
I am running katrain under Ubuntu 20.4. All works fine except for the sound. Upon running katrain I obtain the messages : 
-------------------
`Using user config file /home/adrian/.katrain/config.json
[CRITICAL] [AudioSDL2   ] Unable to open mixer: b'No such audio device'
[WARNING] [AudioSDL2   ] Unable to load /home/adrian/.local/lib/python3.8/site-packages/katrain/sounds/stone1.wav: b"Audio device hasn't been opened"
[WARNING] [AudioSDL2   ] Unable to load /home/adrian/.local/lib/python3.8/site-packages/katrain/sounds/stone2.wav: b"Audio device hasn't been opened"
[WARNING] [AudioSDL2   ] Unable to load /home/adrian/.local/lib/python3.8/site-packages/katrain/sounds/stone3.wav: b"Audio device hasn't been opened"
[WARNING] [AudioSDL2   ] Unable to load /home/adrian/.local/lib/python3.8/site-packages/katrain/sounds/stone4.wav: b"Audio device hasn't been opened"
[WARNING] [AudioSDL2   ] Unable to load /home/adrian/.local/lib/python3.8/site-packages/katrain/sounds/stone5.wav: b"Audio device hasn't been opened"
[WARNING] [AudioSDL2   ] Unable to load /home/adrian/.local/lib/python3.8/site-packages/katrain/sounds/countdownbeep.wav: b"Audio device hasn't been opened"
[WARNING] [AudioSDL2   ] Unable to load /home/adrian/.local/lib/python3.8/site-packages/katrain/sounds/boing.wav: b"Audio device hasn't been opened"
2020-11-26 12:01:35+0100: Analysis Engine starting...
2020-11-26 12:01:35+0100: KataGo v1.7.0
2020-11-26`
----------------
The app then runs fine, except for the sound. Do you have an idea how to fix this?

**Comment by sanderland** [comment]
What's your kivy version? #246 reports 2.0.0rc3/rc4 might fix this.

**Comment by adzweig** [comment]
how to find out? I don't know kivy...

**Comment by sanderland** [comment]
pip list

**Comment by adzweig** [comment]
(kivy_venv) adrian@127:~$ pip list
Package     Version
----------- ---------
certifi     2020.11.8
chardet     3.0.4
Cython      0.29.21
docutils    0.16
idna        2.10
Kivy-Garden 0.1.4
Pillow      8.0.1
pip         20.2.4
Pygments    2.7.2
requests    2.25.0
setuptools  50.3.2
urllib3     1.26.2
wheel       0.35.1

**Comment by adzweig** [comment]
when I try to install kivy with:

 pip install kivy

I obtain a long error message: 

Collecting kivy
  Using cached Kivy-1.11.1.tar.gz (23.6 MB)
    ERROR: Command errored out with exit status 1:
     command: /home/adrian/kivy_venv/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-rp9hzxou/kivy/setup.py'"'"'; __file__='"'"'/tmp/pip-install-rp9hzxou/kivy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-ljoafmw0
         cwd: /tmp/pip-install-rp9hzxou/kivy/
    Complete output (667 lines):
    fatal: not a git repository (or any of the parent directories): .git
    WARNING: Skipping page https://github.com/kivy-garden/garden/archive/master.zip because the HEAD request got Content-Type: application/zip.The only supported Content-Type is text/html
............

**Comment by sanderland** [comment]
`pip3 install kivy --pre --extra-index-url https://kivy.org/downloads/simple/`

**Comment by adzweig** [comment]
Kivy installed:

output of "pip3 list"

Package                 Version             
----------------------- --------------------
....
Cython                  0.29.14             
dbus-python             1.2.16              
.....    
KaTrain                 1.6.1               
keyring                 18.0.1              
Kivy                    2.0.0rc4            
Kivy-Garden             0.1.4               
kivymd                  0.104.1             
kiwisolver              1.0.1               
python-apt              2.0.0+ubuntu0.20.4.1
python-dateutil         2.7.3               
python-debian           0.1.36ubuntu1       
....               
wheel                   0.35.1              
xdiagnose               3.8.9               
xkit                    0.0.0  

**BUT, the error prevails:** 

adrian@127:~$ kata
Using user config file /home/adrian/.katrain/config.json
[CRITICAL] [AudioSDL2   ] Unable to open mixer: b'No such audio device'
[WARNING] [AudioSDL2   ] Unable to load /home/adrian/.local/lib/python3.8/site-packages/katrain/sounds/stone1.wav: b"Audio device hasn't been opened"
[WARNING] [AudioSDL2   ] Unable to load /home/adrian/.local/lib/python3.8/site-packages/katrain/sounds/stone2.wav: b"Audio device hasn't been opened"
[WARNING] [AudioSDL2   ] Unable to load /home/adrian/.local/lib/python3.8/site-packages/katrain/sounds/stone3.wav: b"Audio device hasn't been opened"
[WARNING] [AudioSDL2   ] Unable to load /home/adrian/.local/lib/python3.8/site-packages/katrain/sounds/stone4.wav: b"Audio device hasn't been opened"
[WARNING] [AudioSDL2   ] Unable to load /home/adrian/.local/lib/python3.8/site-packages/katrain/sounds/stone5.wav: b"Audio device hasn't been opened"
[WARNING] [AudioSDL2   ] Unable to load /home/adrian/.local/lib/python3.8/site-packages/katrain/sounds/countdownbeep.wav: b"Audio device hasn't been opened"
[WARNING] [AudioSDL2   ] Unable to load /home/adrian/.local/lib/python3.8/site-packages/katrain/sounds/boing.wav: b"Audio device hasn't been opened"
2020-11-26 18:25:43+0100: Analysis Engine starting...
2020-11-26 18:25:43+0100: KataGo v1.7.0
2020-11-26 18:25:43+0100: nnRandSeed0 = 11802862902786428640
....

**Comment by adzweig** [comment]
May be an issue with Ubuntu?
