### ISSUE TITLE
UI suggestion -- Combine Score, Win Rate, Point Gain/Loss into one chart

### ISSUE THREAD

**Issue by simonguoxm** [sanderland/katrain#248]
Maybe the point gain/loss can be represented like the candle and stick chart in the stock market.

(For the saved space, maybe we can make the original chart double height)

![Screenshot 2020-11-27 000044d](https://user-images.githubusercontent.com/4695131/100418585-a17c7980-3048-11eb-8055-1b9d1daabd50.jpg)

**Comment by sanderland** [comment]
I think it becomes too cramped, and I like being able to show only one thing
