### ISSUE TITLE
performance tuning

### ISSUE THREAD

**Issue by adzweig** [sanderland/katrain#249]
I am trying to optimize the usage of my GPU for computation. (How) can I adjust the parameter "-num-analysis-threads" ?
The config file mentions that this can be set as a command line argument. How would I do this?

**Comment by sanderland** [comment]
you can edit the engine/threads setting in ~/.katrain/config.json , but there's a reason this is hidden, the default is fine and I wouldn't expect much performance difference here.

**Comment by adzweig** [comment]
thanks
