### ISSUE TITLE
Error whith JSON

### ISSUE THREAD

**Issue by philbat** [sanderland/katrain#252]
Hello,
With debian and Python 3.7.7, after the game has started, I get quite often this error:
 
 Traceback (most recent call last):
   File "/home/phil/.local/lib/python3.7/site-packages/katrain/core/engine.py", line 187, in _analysis_read_thread
     analysis = json.loads(line)
   File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
     return _default_decoder.decode(s)
   File "/usr/lib/python3.7/json/decoder.py", line 340, in decode
     raise JSONDecodeError("Extra data", s, end)
 json.decoder.JSONDecodeError: Extra data: line 1 column 20 (char 19)

 and katago engine stops.

Best regards and thank you for this software.

**Comment by sanderland** [comment]
Are you using the built-in katago or your own?
Any other output? It's wrapped in a try/except block, so I would expect the line, as in
https://github.com/sanderland/katrain/blob/e4e140fed41a5bb626c695b2d557efb1806cc99e/katrain/core/engine.py#L222

**Comment by philbat** [comment]
I have installed it with:
pip3 install -U katrain
and there in no other output.

**Comment by sanderland** [comment]
That is very very strange. Are you capable of running from a cloned repo?

**Comment by philbat** [comment]
well, 
git clone https://github.com/sanderland/katrain.git 
cd katrain
pip3 install . 
and i run katrain,
no error for now !

**Comment by philbat** [comment]
just finished a first game without error...
but this error occurred at random..

**Comment by sanderland** [comment]
this is all very strange, let's keep an eye on it.

**Comment by philbat** [comment]
I attach an image:
inside a clone repo and with python 3.8, I get the same error.
![capture](https://user-images.githubusercontent.com/39878496/101989103-5d22e780-3c9e-11eb-9128-5587c43f8aa0.png).
Regards

**Comment by sanderland** [comment]
That is bizarre. Could you set debug level=2 in general settings, and restart with `python -m katrain > log.txt` get this error and upload the log.txt?

**Comment by philbat** [comment]
Here is the log file.
I started katrain with python3 -m katrain in my cloned repo.
[log.txt.gz](https://github.com/sanderland/katrain/files/5684346/log.txt.gz)

**Comment by sanderland** [comment]
Thanks @philbat this gets us somewhere.  You are getting a partial line back, which is very strange. 
But the threads show there are two sets of engine threads competing for input, which should not be possible and is likely the problem.

* What exactly are you doing to get this error, loading? new game?
* Are you running on the master or 1.7 branch?

**Comment by philbat** [comment]
I am running on the master branch and I think I get this error when  I play a new game.

**Comment by sanderland** [comment]
Found the bug. It was related to the 'clear cache' box and not correctly saving the thread reference. Without this box checked, the error will not happen, and it's fixed in 1.7.
Thanks for the logs and working with me on this!
