### ISSUE TITLE
Reducing Analysis / Calibrated rank models "context switches"

### ISSUE THREAD

**Issue by mratsim** [sanderland/katrain#253]
Awesome work on katrain, I experimented with it for 2 days and it's very useful.

Regarding the calibrated rank, those are calibrated to the bundled weights `g170e-b15c192-s1672170752-d466197061` however for analysis I and I suppose everyone else would prefer to use the strongest network their hardware allow them, in my case `g170-b40c256x2-s5095420928-d1229425124`.

This means if you play/analyse often you need to switch the weights back and forth in the settings.

I see 2 solutions:

1. Hardcode using the provided weights when using calibrated rank.

2. Provide 2 weight path fields, one for analysis weight and one for play.

**Comment by sanderland** [comment]
20b and 40b are of similar strength at equal time, I use 20b almost exclusively myself. 
The calibrated rank is also perfectly useable with the 20b network.
