### ISSUE TITLE
Theme support

### ISSUE THREAD

**Issue by cristi-neagu** [sanderland/katrain#258]
Hello,

This is a very low priority suggestion, i expect. Would be good if all game color information as well as the textures for the board and the stones were read from external files. That way people could create whatever themes they like, without them having to be hardcoded and subject to the code review process.

Thank you.

**Comment by cristi-neagu** [comment]
That should be a pretty good stop gap solution until (if ever) a proper theme system becomes a priority. It's the best of both worlds.

**Comment by sanderland** [comment]
Implemented in bfa673d

* ~/.katrain/theme.json can be used to override any constants in the Theme class from theme.py
* Any icons will be looked up in ~/.katrain/ before the package.

@cristi-neagu if you are able to test this in the branch, that would be great.
