### ISSUE TITLE
Bug between 1.5.0 and 1.5.1 (incl 1.6.0) - Pressing M, ~ etc doesn't change the UI layout

### ISSUE THREAD

**Issue by blamarche** [sanderland/katrain#259]
I just noticed that the various fullscreen/alternate UI modes no longer seem to toggle when pressing M or tilde in 1.6.0. I installed 1.5.1 and 1.5.0 and it works in 1.5.0 but no later. I'm on a Windows 10, Surface book 2 device.

**Comment by sanderland** [comment]
Yep this was sent to ctrl-~/m by accident. Already fixed in 1.7 :)
