### ISSUE TITLE
Feature request (or GUI fix): mouse wheel in game tree

### ISSUE THREAD

**Issue by bastiaf** [sanderland/katrain#264]
Hello,

first of all, I would like to say: KataGo is fantastic and very useful. Many thanks for that.

But there is a little thing that is annoying: The mouse wheels (horizontal and vertical) in the game tree do two things, scrolling the tree and switching to the previous or next move. I would prefer that the tree cannot be scrolled with the wheel.

In the score or win graph the mouse wheel is interpreted as a mouse click. I think it should also have the next/previous move function there too. Or the move function should only be active above the board, what do you think?

**Comment by sanderland** [comment]
Fixed in de89856
* no mouse wheel in graph
* mouse wheel doesn't scroll move tree (I thought I did this already, but apparently not)
