### ISSUE TITLE
Requesting the feature of analyzing my every fault moves at once

### ISSUE THREAD

**Issue by sr005307** [sanderland/katrain#265]
I used Katrain, and it is excellent.

I'm currently using an old PC, so it takes a too long time to calculate the forward moves.

I hope Katrain has the feature of analyzing my fault moves when starting or at one order.

I need to check 'the next my fault move' and then put 'a' key to analyze it, and it takes a long time and tedious.

=> In summary, please add the feature of analyzing my fault moves at once.

**Comment by sanderland** [comment]
If you can find it's a mistake, there's already some analysis. What level of visits do you use to load vs analyze?

**Comment by sr005307** [comment]
No what I mean is,,,, not putting 'a' key for command.

I mean every fault moves.

For example, If I did bad(red or Orange color) at 15, 33, 101,  analyzing those moves at once.

**Comment by sanderland** [comment]
this seems best as an option for the 'deeper full game analysis', maybe in 1.8

**Comment by sanderland** [comment]
implemented in 03b397c
