### ISSUE TITLE
Program freezes when Human play too fast againt Katago

### ISSUE THREAD

**Issue by Ishinoshita** [sanderland/katrain#266]
Hi,

As mentioned on LZ Discord #gui channel, my KaTrain reproducibly freezes (Windows messsge "Does not respond") when replying too fast to Katago moves (at least my only correlation ...), while the status button is still orange. It also happens that it freezes by itself (Katago White plays first then program freezes).

I'm using binaries for Windows from this github. Window10 pro, GTX960 GPU.

See attached logs

I spotted this error message in the debug logs (two examples of crashes):
[KaTraindebug.txt](https://github.com/sanderland/katrain/files/5696060/KaTraindebug.txt)
[KaTraindebug - After White first move.txt](https://github.com/sanderland/katrain/files/5696063/KaTraindebug.-.After.White.first.move.txt)

 Traceback (most recent call last):
   File "katrain\core\engine.py", line 187, in _analysis_read_thread
   File "json\__init__.py", line 348, in loads
   File "json\decoder.py", line 340, in decode
 json.decoder.JSONDecodeError: Extra data: line 1 column 18 (char 17)
ERROR: Unexpected exception Extra data: line 1 column 15 (char 14) while processing KataGo output

**Comment by sanderland** [comment]
That does look like the same error as in #252 - any way you can test this is fixed in 1.7?

**Comment by Ishinoshita** [comment]
Confirmed ! Sorry, didn't scan previous before reporting.
Thanks a lot
