### ISSUE TITLE
Problem: Can't see top of board on macOS

### ISSUE THREAD

**Issue by tw-space** [sanderland/katrain#270]
See screenshot. This is on my 13" Retina MacBook Pro at default resolution.

<img width="1363" alt="Screen Shot 2020-12-16 at 4 33 52 PM" src="https://user-images.githubusercontent.com/56986410/102422855-81433900-3fbc-11eb-9d2b-d3ea3e38d844.png">

I can't see the top part of the board and UI, and perhaps the right side's cut off as well. Seems to be a zoom or resize issue, like the window size is getting ignored when painting the UI. Trackpad scrolling doesn't move me around the screen either.

**Comment by sanderland** [comment]
Can you try the v1.7 branch / kivy 2.0.0 ?

**Comment by tw-space** [comment]
Works beautifully! 

<img width="1362" alt="Screen Shot 2020-12-17 at 11 54 31 AM" src="https://user-images.githubusercontent.com/56986410/102536646-c28c2500-405e-11eb-8d5b-94ce793831da.png">

For future folks new to pip3 like me, I did:

```
> pip3 uninstall katrain
> pip3 install git+https://github.com/sanderland/katrain@1.7
> katrain
```

Thanks!
