### ISSUE TITLE
In "Fast playout to game end" mode, the sgf node skip steps and go to the end directly 

### ISSUE THREAD

**Issue by simonguoxm** [sanderland/katrain#274]
In my case (see screenshot), after step 94 should be step 95, but it goes the final step directly.

I think all nodes/steps should be saved, even in "Fast playout to game end" mode.

![image](https://user-images.githubusercontent.com/4695131/102699672-19832d00-420c-11eb-8252-423643d443cf.png)

**Comment by sanderland** [comment]
this is on purpose, as it's meant to show you the end without having to deal with a messy move tree.
However, you can right click the gray node and expand it. If this is not clear in the readme, feel free to suggest an improvement.

**Comment by simonguoxm** [comment]
Got it and thanks. 
I did see the "Expand/Collapse" option but I didn't try it yet.
