### ISSUE TITLE
Set Region of Interest + Alternate moves can not be combined

### ISSUE THREAD

**Issue by ph1234k** [sanderland/katrain#276]
This doesn't seem intentional, though I may be incorrect. 

So, if you set a region of interest specifically and then use the analysis option "find alternate moves" - It simply doesn't take region of interest into account, it checks the entire board.

**Comment by sanderland** [comment]
Indeed, this is essentially due to the 'avoid' list being used in both options separately.

**Comment by ph1234k** [comment]
Sounds like this is expected then? -- If that's the case feel free to close, I was not sure on the expected behavior of these together.
