### ISSUE TITLE
player name in new game should be ignored if generated

### ISSUE THREAD

**Issue by sanderland** [sanderland/katrain#277]

**Comment by xiaoyifang** [comment]
the problem still existed in the V1.7.1 verson

**Comment by sanderland** [comment]
even in sgfs generated with v1.7+ ?

**Comment by xiaoyifang** [comment]
load a sgf file ,then create New Game( use menu).  the new game will inheritate the sgf player names ,which i think is wrong.

**Comment by xiaoyifang** [comment]
> even in sgfs generated with v1.7+ ?

yes

**Comment by sanderland** [comment]
please post the exact steps to reproduce, because I don't see this

**Comment by xiaoyifang** [comment]
1. load the below sgf
[test.zip](https://github.com/sanderland/katrain/files/5826265/test.zip)

2. in the menu,  choose New Game.
the new game dialog ,the player name input have  the sgf's player names(which should be wrong).

**Comment by sanderland** [comment]
This bug was about showing "Human (Normal game)" in the top right.
Your issue is more about the fact that the 'edit game' and 'new game' are the same dialog, and there's not a clear choice on whether to show the names here or not.

**Comment by xiaoyifang** [comment]
I got it.

create a new issue for this?

maybe 'edit game' and 'new game ' should use two different dialog  :-)  .
