### ISSUE TITLE
SGF breaks parser

### ISSUE THREAD

**Issue by johanrex** [sanderland/katrain#288]
This game from OGS breaks the SGF parser. Getting error output when reading the file. Unfortunately I don't see a way to copy the error message.

`(;FF[4]
CA[UTF-8]
GM[1]
DT[2020-12-25]
PC[OGS: https://online-go.com/game/29484980]
GN[Friendly Match]
PB[_ThirdEye_]
PW[huw1234]
BR[23k]
WR[?]
TM[60]OT[5x30 byo-yomi]
RE[W+37.5]
SZ[13]
KM[5.5]
RU[Japanese]
C[huw1234: hi
_ThirdEye_: hfhf
]
;B[kd]
C[huw1234: hi
_ThirdEye_: hfhf
]
(;W[dj]
(;B[jk]
(;W[cd]
(;B[ic]
(;W[fd]
(;B[ek]
(;W[dk]
(;B[ej]
(;W[ei]
(;B[fi]
(;W[fh]
(;B[gi]
(;W[gh]
(;B[hi]
(;W[hh]
(;B[ii]
(;W[ih]
(;B[jh]
(;W[jg]
(;B[kh]
(;W[kg]
(;B[di]
(;W[eh]
(;B[ci]
(;W[el]
(;B[fl]
(;W[dl]
(;B[bk]
(;W[bl]
(;B[ck]
(;W[cl]
(;B[al]
(;W[gl]
(;B[fk]
(;W[fm]
(;B[gk]
(;W[hl]
(;B[il]
(;W[hk]
(;B[hj]
(;W[ik]
(;B[jl]
(;W[ji]
(;B[ki]
(;W[gj]
(;B[fj]
(;W[jj]
(;B[hm]
(;W[kj]
(;B[kk]
(;W[lj]
(;B[lk]
(;W[lh]
(;B[cf]
(;W[bf]
(;B[bg]
(;W[be]
(;B[cg]
(;W[hd]
(;B[gb]
(;W[fb]
(;B[gc]
(;W[fc]
(;B[ie]
(;W[gd]
(;B[id]
(;W[ll]
(;B[ml]
(;W[lm]
(;B[im]
(;W[gm]
(;B[em]
(;W[dm]
(;B[km]
(;W[le]
(;B[ld]
(;W[ke]
(;B[ee]
(;W[de]
(;B[df]
(;W[ed]
(;B[ef]
(;W[gf]
(;B[cj]
(;W[hb]
(;B[hc]
(;W[ga]
(;B[ib]
(;W[ha]
(;B[ia]
(;W[fa]
(;B[ce]
(;W[dd]
(;B[af]
(;W[bd]
(;B[dh]
(;W[md]
(;B[mc]
(;W[me]
(;B[kc]
(;W[je]
(;B[jd]
(;W[if]
(;B[he]
(;W[ge]
(;B[eg]
(;W[lb]
(;B[lc]
(;W[hf]
(;B[kb]
(;W[ae]
(;B[mj]
(;W[li]
(;B[mi]
(;W[bm]
(;B[ag]
(;W[am]
(;B[ak]
(;W[mh]
(;B[mk]
(;W[]
(;B[fg]
(;W[gg]
(;B[]
(;W[]
C[_ThirdEye_: thx
]
))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))
`

**Comment by johanrex** [comment]
I see that the formatting doesn't get correct when I paste the markup. The actual file contains of many lines, Each move/tag on its own line. File can be found here: https://online-go.com/game/29484980.

**Comment by sanderland** [comment]
It works for me. Are you sure you are on the latest version?
