### ISSUE TITLE
Update katago version

### ISSUE THREAD

**Issue by xiaoyifang** [sanderland/katrain#289]
when change a new katago weight file,  katrain clash.
![image](https://user-images.githubusercontent.com/105986/103144604-59e02f00-4767-11eb-9c17-50bf55462e48.png)

**Comment by sanderland** [comment]
Can not reproduce this. Could you show the entire console stack trace? (in windows, use debugkatrain.exe in the zip)

**Comment by xiaoyifang** [comment]
https://media.katagotraining.org/uploaded/networks/models/kata1/kata1-b40c256-s5240960768-d1261780066.bin.gz
the network weight file @sanderland

**Comment by sanderland** [comment]
ERROR: KataGo Engine Failed: Uncaught exception: Error loading or parsing model file C:\Users\sande\Downloads\kata1-b40c256-s5240960768-d1261780066.bin.gz: kata1-b40c256-s5240960768-d1261780066: model found unsupported version 10

**Comment by sanderland** [comment]
This is from distributed training, yes? These models are not yet supported by a released katago version. If you compile from sources and use that exe, it should work.
Error message improved in 690ea9a

**Comment by sanderland** [comment]
lightvector says he is planning to release a new version next week, I will update then and release 1.7.1

**Comment by sanderland** [comment]
done
