### ISSUE TITLE
Feature Request: add sgf extention to be opened by katrain . currently not work.

### ISSUE THREAD

**Issue by xiaoyifang** [sanderland/katrain#290]

**Comment by sanderland** [comment]
you mean your uppercase SGF files?fixed in  c5570ad

**Comment by xiaoyifang** [comment]
what i mean is ,in the windows 10 ,right click on the sgf file ,and choose to open by katrain ,
result:
katrain opened ,but sgf was not loaded

**Comment by sanderland** [comment]
I see! I've never tried this actually. Let me see

**Comment by sanderland** [comment]
fixed in the commit linked above :)
