### ISSUE TITLE
bug : sgf file load error 

### ISSUE THREAD

**Issue by xiaoyifang** [sanderland/katrain#292]
the sgf file can be loaded by other sgf viewer.
[GAME-01.zip](https://github.com/sanderland/katrain/files/5742702/GAME-01.zip)

**Comment by xiaoyifang** [comment]
possibly due to the HA[对子]   property ,
in such cases ,should it be ignored and continue to open the sgf.

**Comment by sanderland** [comment]
https://www.red-bean.com/sgf/go.html#properties

```Property:	HA
Propvalue:	number
Propertytype:	game-info
```
This is a bug in the program that generated the SGF, you should report it there.
