### ISSUE TITLE
[bug] katrain guess the next player wrong .

### ISSUE THREAD

**Issue by xiaoyifang** [sanderland/katrain#293]
there are already 4 stones on the board. then player white first to play.

but katrain thought it was black's turn.
[white to play.zip](https://github.com/sanderland/katrain/files/5742732/white.to.play.zip)
![image](https://user-images.githubusercontent.com/105986/103146365-1d223100-4783-11eb-8dd2-9fb8643f20dd.png)

**Comment by sanderland** [comment]
Could you point out which part of the SGF standard suggests it is white to play when mixed placements are present and no PL tag?

**Comment by xiaoyifang** [comment]
in the sgf ,just move to the next move ,in the above screeshot ,the position 1 in the sgf

**Comment by sanderland** [comment]
I see. Using the next player if in the sgf may be ok.
```
(;SZ[19]FF[3]

AB[dd][pp]
AW[pd][dp]

;(B[fc];W[nc])(W[fc];B[nc]))
```
Who is the next player here?
```
(;SZ[19]FF[3]

AB[dd][pp]
AW[pd][dp]

;(W[fc];B[nc])(B[fc];W[nc]))
```
or here?
```
(;SZ[19]FF[3];B[dd])
```
or here?

**Comment by xiaoyifang** [comment]
if there are many branches ,default choose the first branch .later changed when user choose another branch.

> 

> (;SZ[19]FF[3]
> 
> AB[dd][pp]
> AW[pd][dp]
> 
> ;(B[fc];W[nc])(W[fc];B[nc]))
> Who is the next player here?

Black should be the player.

> (;SZ[19]FF[3]
> 
> AB[dd][pp]
> AW[pd][dp]
> 
> ;(W[fc];B[nc])(B[fc];W[nc]))
> or here?

in the first branch is W[fc] ,choose White player.

> (;SZ[19]FF[3];B[dd])

only one branch ,choose the first B[dd] ,black player

**Comment by sanderland** [comment]
That's a reasonable suggestion.  Implemented in 38ddc8e

**Comment by sanderland** [comment]
Actually still has problems due to the fact that katago does not allow setting the next player, only for root.

**Comment by sanderland** [comment]
split it for root vs normal nodes, seems to be ok now. follow up in #300 for later
