### ISSUE TITLE
Flip or rotate the board view

### ISSUE THREAD

**Issue by xiaoyifang** [sanderland/katrain#297]
rotation will also be welcomed :-)

**Comment by sanderland** [comment]
This is too complicated (all the analysis and such will have to be rotated) and has very little use, so I am unlikely to do this.

**Comment by xiaoyifang** [comment]
I think there is an easy way to achieve this.

Solution :
just rotate the board with the coordination with it .

by doing this,nothing have to be changed ,except when display the board.
(Imagine, when a viewer watch a go game,he walk around the board ,but the board has not change a place.)

**Comment by sanderland** [comment]
That's a good idea. Someone who is interested in contributing here should look at the gridpos arrays in badukpan.py
