### ISSUE TITLE
Set maximal time to perform any given analysis

### ISSUE THREAD

**Issue by 8139david** [sanderland/katrain#303]
Be able to set maximal time to perform any given analysis, such as a full game analysis; or fast playout to game end; etc.
Since Katrain knows your hardware it can estimate the number of visits it should perform so as to complete the specified analysis in a given time.

**Comment by sanderland** [comment]
> Since Katrain knows your hardware

It does not. It trusts you have put a reasonable number for max visits / max visits fast / max time in your settings.

**Comment by 8139david** [comment]
OK. Still, it could be able to learn about your hadware.
But there are certainly more urgent things to work on.

**Comment by 8139david** [comment]
Doesn't Katago identify certain characteristics of your hardware the first time it plays? Couldn't this information be used?

**Comment by sanderland** [comment]
This is too complicated for too little game in my opinion
