### ISSUE TITLE
[bug] katrain ,in chinese language,save sgf ,the sgf contain special characters which can not display correctly.

### ISSUE THREAD

**Issue by xiaoyifang** [sanderland/katrain#309]
in the sgf file,  
> PB[人类 (指导棋)(a special invisible character here)​]

[KaTrain_人类 (指导棋) vs AI (参考段位) 2021-01-03 12 14 02.zip](https://github.com/sanderland/katrain/files/5761206/KaTrain_.vs.AI.2021-01-03.12.14.02.zip)

**Comment by sanderland** [comment]
This is deliberate, to mark it as generated and to be ignored on loading.
A minor display bug on loading, #277 is fixed already

**Comment by xiaoyifang** [comment]
when loaded by other sgf viewer ,the player name can not display correctly.
