### ISSUE TITLE
hangs at start with message: Exception no module named 'screen info'

### ISSUE THREAD

**Issue by anonimasusan** [sanderland/katrain#315]
Hi all,
just installed katrain via the latest AUR package in arch. Installs fine, but at lauch, an empty window opens and hangs.
Error message in terminal is: 
Exception no module named 'screen info' while getting screen resolution.
Tried with several options (-f, fixed resolution, etc), tried 3 windows managers (sway, i3, openbox), with same error.

**Comment by sanderland** [comment]
That should just be a warning and not fatal, even if you somehow manage to bypass the installation of requirements. What is the full output?

**Comment by anonimasusan** [comment]
full output is:
Exception No module named 'screeninfo' while getting screen resolution.
Using user config file /home/archie/.katrain/config.json

**Comment by sanderland** [comment]
and if you go to /home/archie/.katrain/config.json and set general / debug_level: 2

**Comment by anonimasusan** [comment]
Exception No module named 'screeninfo' while getting screen resolution.
Using user config file /home/archie/.katrain/config.json
[INFO   ] [Logger      ] Record log in /home/archie/.kivy/logs/kivy_21-01-06_1.txt
[DEBUG  ] [Resource    ] add </usr/share/fonts> in path list
[DEBUG  ] [Resource    ] add </usr/share/fonts/noto> in path list
[DEBUG  ] [Resource    ] add </usr/share/fonts/ubuntu> in path list
[DEBUG  ] [Resource    ] add </usr/share/fonts/TTF> in path list
[DEBUG  ] [Resource    ] add </usr/share/fonts/util> in path list
[DEBUG  ] [Resource    ] add </usr/share/fonts/adobe-source-code-pro> in path list
[DEBUG  ] [Resource    ] add </usr/share/fonts/gnu-free> in path list
[DEBUG  ] [Resource    ] add </usr/share/fonts/liberation> in path list
[DEBUG  ] [Resource    ] add </usr/share/fonts/gsfonts> in path list
[DEBUG  ] [Resource    ] add </usr/share/fonts/100dpi> in path list
[DEBUG  ] [Resource    ] add </usr/share/fonts/cantarell> in path list
[DEBUG  ] [Resource    ] add </usr/share/fonts/encodings> in path list
[DEBUG  ] [Resource    ] add </usr/share/fonts/encodings/large> in path list
[DEBUG  ] [Resource    ] add </usr/share/fonts/75dpi> in path list
[DEBUG  ] [Resource    ] add </usr/lib/python3.9/site-packages/kivy/data/fonts> in path list
[DEBUG  ] [ImageSDL2   ] Load </usr/lib/python3.9/site-packages/katrain/img/ai.png>
[DEBUG  ] [ImageSDL2   ] Load </usr/lib/python3.9/site-packages/katrain/img/play.png>
[DEBUG  ] [ImageSDL2   ] Load </usr/lib/python3.9/site-packages/katrain/img/analysis.png>
[DEBUG  ] [ImageSDL2   ] Load </usr/lib/python3.9/site-packages/katrain/img/Finish.png>
[DEBUG  ] [ImageSDL2   ] Load </usr/lib/python3.9/site-packages/katrain/img/Insert-Move.png>
[DEBUG  ] [ImageSDL2   ] Load </usr/lib/python3.9/site-packages/katrain/img/local.png>
[DEBUG  ] [ImageSDL2   ] Load </usr/lib/python3.9/site-packages/katrain/img/Alternative.png>
[DEBUG  ] [ImageSDL2   ] Load </usr/lib/python3.9/site-packages/katrain/img/Sweep.png>
[DEBUG  ] [ImageSDL2   ] Load </usr/lib/python3.9/site-packages/katrain/img/Equalize.png>
[DEBUG  ] [ImageSDL2   ] Load </usr/lib/python3.9/site-packages/katrain/img/Extra.png>
[DEBUG  ] [ImageSDL2   ] Load </usr/lib/python3.9/site-packages/katrain/img/hamburger.png>
[DEBUG  ] [ImageSDL2   ] Load </usr/lib/python3.9/site-packages/katrain/img/menu.png>
[DEBUG  ] [ImageSDL2   ] Load </usr/lib/python3.9/site-packages/katrain/img/menu.png>

then hangs

**Comment by sanderland** [comment]
And the stack traces after ctrl-c ?

**Comment by anonimasusan** [comment]
ctrl-c hangs

**Comment by sanderland** [comment]
Very strange! 
This seems like another kivy issue to me, could ask at https://kivy.org/doc/stable/contact.html
Also py3.9 is not quite new, could try a 3.7/3.8 pyenv.

**Comment by anonimasusan** [comment]
tried with AUR package kivy-git instead of kivy, this time it crashes immediately with message:
 Traceback (most recent call last):
   File "/usr/bin/katrain", line 33, in <module>
     sys.exit(load_entry_point('KaTrain==1.7.0', 'console_scripts', 'katrain')())
   File "/usr/lib/python3.9/site-packages/katrain/__main__.py", line 713, in run_app
     app.run()
   File "/usr/lib/python3.9/site-packages/kivy/app.py", line 949, in run
     self._run_prepare()
   File "/usr/lib/python3.9/site-packages/kivy/app.py", line 919, in _run_prepare
     root = self.build()
   File "/usr/lib/python3.9/site-packages/katrain/__main__.py", line 655, in build
     self.gui = KaTrainGui()
   File "/usr/lib/python3.9/site-packages/katrain/__main__.py", line 102, in __init__
     super().__init__(**kwargs)
   File "/usr/lib/python3.9/site-packages/kivy/uix/relativelayout.py", line 274, in __init__
     super(RelativeLayout, self).__init__(**kw)
   File "/usr/lib/python3.9/site-packages/kivy/uix/floatlayout.py", line 65, in __init__
     super(FloatLayout, self).__init__(**kwargs)
   File "/usr/lib/python3.9/site-packages/kivy/uix/layout.py", line 76, in __init__
     super(Layout, self).__init__(**kwargs)
   File "/usr/lib/python3.9/site-packages/kivy/uix/widget.py", line 359, in __init__
     self.apply_class_lang_rules(
   File "/usr/lib/python3.9/site-packages/kivy/uix/widget.py", line 463, in apply_class_lang_rules
     Builder.apply(
   File "/usr/lib/python3.9/site-packages/kivy/lang/builder.py", line 541, in apply
     self._apply_rule(
   File "/usr/lib/python3.9/site-packages/kivy/lang/builder.py", line 621, in _apply_rule
     cls = Factory_get(cname)
   File "/usr/lib/python3.9/site-packages/kivy/factory.py", line 146, in __getattr__
     raise FactoryException('Unknown class <%s>' % name)
 kivy.factory.FactoryException: Unknown class <NavigationLayout>

**Comment by sanderland** [comment]
Very very strange indeed. Did the kivy devs have any help?

**Comment by anonimasusan** [comment]
I closed the issue there and here.

**Comment by anonimasusan** [comment]
reason being installing directly using pip works fine. Must be a problem with the AUR package.
