### ISSUE TITLE
Option to show move numbers on stones

### ISSUE THREAD

**Issue by 8139david** [sanderland/katrain#316]
It would be nice to have the option to show move numbers on the stones.
This would be useful to see the order of moves at once.

**Comment by 8139david** [comment]
In fact, the best would be as in Drago: there is an option to show moves numbers for the last N moves.
This yields at least three options: show number for all moves VS the last N moves VS no move.

**Comment by sanderland** [comment]
I think there's no room for them, with the dots and all

**Comment by 8139david** [comment]
I don't see why. The moves that would be numbered would always be past moves with respect to the situation being analyzed.

**Comment by xiaoyifang** [comment]
> I think there's no room for them, with the dots and all

dots and move num can be exclusive
