### ISSUE TITLE
Issues installing katrain on Linux Mint

### ISSUE THREAD

**Issue by carlitador** [sanderland/katrain#318]
Hi,

I tried to install katrain on Linux Mint 19.3. The GUI does start but it seems the engine doesnt respond at all.
Here is the output:
https://termbin.com/3z5s

Thanks for your help

**Comment by sanderland** [comment]
Another mint issue! #314 also had one.
https://stackoverflow.com/questions/62981643/xclip-and-xsel-filenotfounderror-errno-2

**Comment by carlitador** [comment]
Hi, thanks but I didnt solve the issue.
Here is the new output:
https://termbin.com/v9ym

Thanks

**Comment by sanderland** [comment]
Does this happen with all katago versions (general settings->download, try builtin, official opengl, official eigen)

**Comment by carlitador** [comment]
Hi @sanderland,
Thanks for answering
I tried all of the engines, and I am not able to use any of them. You will find the full log here:
https://termbin.com/mzax
Thanks again

**Comment by sanderland** [comment]
Did you try installing the libraries it says you are missing?

**Comment by carlitador** [comment]
I installed libzip-dev but I am not sure its the right one to install. I dont know where to install the specified package (libzip.so.5) ?
Thanks

**Comment by carlitador** [comment]
Ok, I compiled katago myself and it works this way. The engine was compiled with another version of libzip I cant install my distribution
Thanks
