### ISSUE TITLE
The idea about automatic player evaluator

### ISSUE THREAD

**Issue by smolendawid** [sanderland/katrain#319]
Hello

I was wondering about the following idea. It might be possible to:

- Download a number of games from let's say OGS
- Analyse every move in terms of lost point/percentage
- Collect the statistics
- Map the OGS players rank to the moves scores, considering the "outliers" (like maybe the good move that was not seen for a long time by two players or something, we would have to dig into data. Maybe some classifier would be useful)
- Create an evaluation system that says: "you played like 1k OGS!"

Sometimes we win although we shouldn't and vice versa. Sometimes we play good or bad games depending on a lot of circumstances. Sure maybe it's not the most useful thing ever but I think it would be a great feature. Therefore I'd like to discuss the idea. Any thoughts @sanderland?

**Comment by sanderland** [comment]
issue #44  and links therein have some discussion and link to code in the bots repo which could be used to get you started.
An earlier version had a rank estimator based on the current game, but it was way too noisy.
In any case this is not really related to a 'feature' in katrain, more like a separate project. Good luck!

**Comment by smolendawid** [comment]
I'd love to be able to analyze AlphaGo, pros, streamer, and old games like Shusaku. Thanks for the link. Cheers!
