### ISSUE TITLE
when  analysis game ,katrain have great chance to crash the engine 

### ISSUE THREAD

**Issue by xiaoyifang** [sanderland/katrain#322]
the engine status indicator hang on there withot any change ,always orange color.

plus,
when load another sgf, the numbers in the indicator does not change accordingly .seems wrong.

**Comment by sanderland** [comment]
Are you sure this is an issue with the rules, or something subtly wrong with the restart/shutdown logic? I suspect the latter...

**Comment by xiaoyifang** [comment]
[李世石_AlphaGo_第五局_简体.zip](https://github.com/sanderland/katrain/files/5826130/_AlphaGo_._.zip)
if the sgf is have more than 200 moves ,the engine seems  take a lot of time to finish the analysis.

**Comment by sanderland** [comment]
Can not reproduce any crashes.

**Comment by xiaoyifang** [comment]
it is just very slow.

i noticed that ,if the sgf have 200 moves ,katrain will send 200 request to katago engine.

would it be better that just send one request to katago engine with parameter analyzeTurns set to  "analyzeTurns[0,1,2,.....200]"
