### ISSUE TITLE
[feature request] add a seperate edit game dialog

### ISSUE THREAD

**Issue by xiaoyifang** [sanderland/katrain#329]
currently ,'edit game' and 'new game'  in the same dialog.
which would cause trouble when create 'new game'  https://github.com/sanderland/katrain/issues/277#issuecomment-761831203

in the menu ,add an additional entry as 'Edit Game'
in the edit game dialog ,user can change  player ai settings, komi,   player names,  rules , etc.
and will not  change handicap ,  board size

**Comment by sanderland** [comment]
done in 1.8.0

**Comment by xiaoyifang** [comment]
as we have edit game dialog now,  the special character can be removed.
 https://github.com/sanderland/katrain/issues/309

**Comment by sanderland** [comment]
> as we have edit game dialog now, the special character can be removed.
> #309

The special character should only be added to built-in names to remove them on loading, which seems still needed

**Comment by xiaoyifang** [comment]
https://github.com/sanderland/katrain/issues/277#issuecomment-761831203
