### ISSUE TITLE
Using pyinstaller 4.2 leads to antivirus false positives

### ISSUE THREAD

**Issue by ProLeela** [sanderland/katrain#333]
My Antivirus (Avast) says that both Katrain.exe and DebugKatrain.exe from the 1.7.2. release are virused.

See: https://www.virustotal.com/gui/file/b9163b3e5a8ae27721d2fa2c19c472023760d6d0393743970dc71d2ec62fd129/detection (recognized by more than one antivirus)

If it helps somwhow...
All the other instalations till now worked OK.

**Comment by sanderland** [comment]
I am not sure what I can do about false positives from third-party software to third-party libraries

**Comment by sanderland** [comment]
https://github.com/pyinstaller/pyinstaller/issues/5490

**Comment by sanderland** [comment]
tested pyinstaller 4.0: 1 fp, 4.1: 2 fp, 4.2: a bunch. Using 4.1, replaced release exes
