### ISSUE TITLE
Application cannot be closed when analysis is on (no response)

### ISSUE THREAD

**Issue by dinohsu1019** [sanderland/katrain#334]
Hi @sanderland 

This is a frequent issue: application cannot be closed when I am reviewing my game (in my case with remote engine)

Platform: Windows 10 64 bit
Version: v. 1.7.2 
Steps: In the middle of reviewing a game using remote engine for analysis, the user clicks the "x" button at the upper right corner.
Expected result: application is closed.
Actual result: application is not responding, have to hard close. 

Thanks in advance. 

![image](https://user-images.githubusercontent.com/30600848/105620881-82c61380-5e3c-11eb-9604-0392acf08ce7.png)

**Comment by sanderland** [comment]
I suspect whatever application you are running as the connector doesn't respect the termination signal. It's hard to test though.
https://pythontic.com/multiprocessing/process/terminate

**Comment by dinohsu1019** [comment]
I am not sure, this problem exists since my first install, and it happens even when there are no other applications running.

**Comment by sanderland** [comment]
I tested it and it was something else (threads not joining/readline not returning). Fixed in 319ff14
