### ISSUE TITLE
Feature request: add a sound when capture the  stones 

### ISSUE THREAD

**Issue by lv100niko** [sanderland/katrain#338]
Add a sound when capture   stones  ？thank you！

**Comment by sanderland** [comment]
Where would I get such a sound?

**Comment by lv100niko** [comment]
> Where would I get such a sound?

https://drive.google.com/file/d/1m-zLheG291XTWnLz6_TwkVWvZOXy5uht/view?usp=sharing

**Comment by sanderland** [comment]
access denied. also, is this your original work?

**Comment by peepo** [comment]
I would also like a sound file: 'click' when opponent moves

**Comment by sanderland** [comment]
Added in 1.11.1
