### ISSUE TITLE
Feature request: Unlock more calibrated rank bots.

### ISSUE THREAD

**Issue by portkata** [sanderland/katrain#339]
Since the new distributed katago policy is so strong (beaten zen 7 9 dan, cz zero 9 dan, golaxy 9 dan), do you think it would be a good idea to unlock kyu_rank -3 to -8? Right now there is a wide gap between the policy and kyu_rank -2.  If a user didn't like the new bots, they could be free to ignore them. Thanks for the great program!

**Comment by sanderland** [comment]
You mean make the slider go further? I'm afraid it will just lead to confusion. Ranks are calibrated against OGS, so other bots are not so relevant.
Users are free to type in other numbers though, although it's not been tested.
I have a vague plan to use your visit numbers to make calibrated rank have all options to 9d+ by switching strategies around the policy network point.

**Comment by portkata** [comment]
Yeah i just meant to be able to type in other numbers, thanks so much! I'm thinking the accuracy above 3 dan won't bother amateurs anymore since it is getting to the point where none/extremely few will be able to beat the policy. I would be surprised if the U.S., for example, had any amateurs that can still beat the policy network. So even if -8 is really 7 dan OGS, it won’t bother the user. I must have overlooked the feature, will close thread.
