### ISSUE TITLE
Stream/Video suggestions

### ISSUE THREAD

**Issue by munen** [sanderland/katrain#342]
Dear Mr Sander Land

I'd like to answer your email to sponsors from yesterday, but I don't know how, so I resort to this public GH issue. I did try some archeology though: The email I received has a `From: Sander Land <noreply@github.com>` header, your GH profile doesn't show an email and your commit messages show `Author: Sander Land <48946947+sanderland@users.noreply.github.com>`. Those all look like they would not reach you.

If you send us an email via the sponsors updates, I'll answer there. Otherwise I'm happy to continue the discussion here, as well. Until your message, I won't disclose your question in public, though(;

Thank you very much in advance for asking for feedback and I'm very much looking forward to the result :pray:

**Comment by sanderland** [comment]
That's a good point, I'll include my contact info next time! 
I've had some suggestions through discord (Sander#3278) and am following up on one promising lead in particular.

**Comment by munen** [comment]
Thanks and good luck!
