### ISSUE TITLE
[Feature Request] AI assisted play (Local/Global)

### ISSUE THREAD

**Issue by davidhewett** [sanderland/katrain#345]
I realize this sounds vague, so to clarify: There could be the ability for the player to select AI assistance for local or global play. What local play assistance might look like is, the human plays as normal against an opponent, but if the best move is local, the AI plays it instead. This allows the player to exclusively focus on playing big moves and practicing global play. Or alternatively, global play assistance might mean that the AI will play the best moves globally, allowing the player to focus on territorial fighting. I think splitting up these two different modes of gameplay would be incredibly useful for players who are better at one mode of play than the other. For instance, I'm much weaker at global play than I am at local play, and I think it would be more efficient/interesting to practice using this method.

I think there could possibly be more modes of AI assistance/a way to generalize this in some way, but I'm not sure.

**Comment by sanderland** [comment]
Often tenuki and local moves are both reasonable options, so making the AI play based on basically noise-level differences is not something I'd be interested in.
