### ISSUE TITLE
(new install, first run:) ERROR: Engine died unexpectedly without sending output, possibly due to out of memory: status -6

### ISSUE THREAD

**Issue by kylebakerio** [sanderland/katrain#346]
did an install onto my Pop_OS (ubuntu variant) via pip. added appropriate directory to path. See error message in gui, see this in console:

```sh
kyle@t470p-pop:~$ katrain 
[WARNING] [Config      ] Older configuration version detected (0 instead of 21)
[WARNING] [Config      ] Upgrading configuration in progress.
Copied package config to local file /home/kyle/.katrain/config.json
[CRITICAL] [AudioSDL2   ] Unable to open mixer: b'No such audio device'
[WARNING] [AudioSDL2   ] Unable to load /home/kyle/.local/lib/python3.8/site-packages/katrain/sounds/stone1.wav: b"Audio device hasn't been opened"
[WARNING] [AudioSDL2   ] Unable to load /home/kyle/.local/lib/python3.8/site-packages/katrain/sounds/stone2.wav: b"Audio device hasn't been opened"
[WARNING] [AudioSDL2   ] Unable to load /home/kyle/.local/lib/python3.8/site-packages/katrain/sounds/stone3.wav: b"Audio device hasn't been opened"
[WARNING] [AudioSDL2   ] Unable to load /home/kyle/.local/lib/python3.8/site-packages/katrain/sounds/stone4.wav: b"Audio device hasn't been opened"
[WARNING] [AudioSDL2   ] Unable to load /home/kyle/.local/lib/python3.8/site-packages/katrain/sounds/stone5.wav: b"Audio device hasn't been opened"
[WARNING] [AudioSDL2   ] Unable to load /home/kyle/.local/lib/python3.8/site-packages/katrain/sounds/countdownbeep.wav: b"Audio device hasn't been opened"
[WARNING] [AudioSDL2   ] Unable to load /home/kyle/.local/lib/python3.8/site-packages/katrain/sounds/boing.wav: b"Audio device hasn't been opened"
2021-01-29 03:24:36+0100: Analysis Engine starting...
2021-01-29 03:24:36+0100: KataGo 1.7.0+ (Minified version for KaTrain v1.7.1)
2021-01-29 03:24:36+0100: nnRandSeed0 = 14203435071236166885
2021-01-29 03:24:36+0100: After dedups: nnModelFile0 = /home/kyle/.local/lib/python3.8/site-packages/katrain/models/g170e-b15c192-s1672170752-d466197061.bin.gz useFP16 auto useNHWC auto
[WARNING] [MTD         ] Unable to open device "/dev/input/event6". Please ensure you have the appropriate permissions.
[WARNING] [MTD         ] Unable to open device "/dev/input/event7". Please ensure you have the appropriate permissions.
terminate called after throwing an instance of 'StringError'
what():  OpenCL error at /KataGo/neuralnet/openclhelpers.cpp, func err, line 263, error CL_PLATFORM_NOT_FOUND_KHR
ERROR: Engine died unexpectedly without sending output, possibly due to out of memory: status -6
```
On a thinkpad T470p with 940mx.

**Comment by kylebakerio** [comment]
(btw, I have 32 gb of ram and only 9gb utilized right now, so if that's the 'out of memory' referred to, probably incorrect...)

**Comment by kylebakerio** [comment]
fwiw, I just remembered I only have my integrated graphics running. I'll try switching over to nvidia drivers and restarting. derp.

**Comment by sanderland** [comment]
CL_PLATFORM_NOT_FOUND_KHR is a katago/opencl problem. Sometimes a restart helps.
The out of memory refers to GPU memory, this happens for example when running multiple copies.

**Comment by kylebakerio** [comment]
This was indeed fixed by restarting into nvidia graphics mode. In theory could have just been the restart, but probably the mode switching did it.

I'll also try using it in 'compute mode', where I use the intel chip for my desktop by can use the nvidia via the command line for computation, but for now this works. I did get a freeze near the end of a game last night when playing one through, but that could very well be my undervolting or just using the nvidia drivers.

Thanks! I'm about to be getting a laptop with an RTX 2060, looking forward to playing with this. Wanted to try it on the 960M first to have something to compare it to.

**Comment by khlsvr** [comment]
Hey I got a HP 15s-eq1835no laptop computer with Arch Linux. It has AMD Ryzen™ 5 4500U Mobile Processor. A kind of an APU, GTA IV and such games works on it, but it's not powerful as some GPUs. It has 8 GB DDR4 RAM. 

I installed katrain from the AUR and tried running it. I got the `ERROR: Engine died unexpectedly without sending output: status 127` and read here on github someone getting the same error and it was suggested to compile katago from sources and try from that.

So next I did I tried installing aur/katago-opencl. After this I ran the katrain and got an error, went to general settings and set the katago path to /usr/bin/katago as the katago-opencl installed that binary. Now I am getting similar error as in this thread:

```
]$  katrain
Using user config file /home/onla/.katrain/config.json
2021-08-06 13:47:01+0300: Analysis Engine starting...
2021-08-06 13:47:01+0300: KataGo v1.9.1
2021-08-06 13:47:01+0300: nnRandSeed0 = 5634012653331664878
2021-08-06 13:47:01+0300: After dedups: nnModelFile0 = /usr/lib/python3.9/site-packages/katrain/models/g170e-b15c192-s1672170752-d466197061.bin.gz useFP16 auto useNHWC auto
[WARNING] [MTD         ] Unable to open device "/dev/input/event18". Please ensure you have the appropriate permissions.
terminate called after throwing an instance of 'StringError'
ERROR: KataGo Engine Failed: OpenCL error at /home/onla/.cache/yay/katago-opencl/src/katago-opencl/cpp/neuralnet/openclhelpers.cpp, func err, line 263, error CL_PLATFORM_NOT_FOUND_KHR
ERROR: Engine died unexpectedly without sending output:  status -6
```

Should this laptop use something else than katago-opencl? The following packages would be easily available in Arch User Repository:

```
$  yay -Ss katago
aur/lizzie-improve 20210803-1 (+1 0.25) 
    Analysis interface for KataGo/Leela Zero, more features added by yzy
aur/katago-cpu 1.9.1-1 (+1 0.49) 
    Baduk engine with no human-provided knowledge. This package is compiles katago with CPU and AVX2 support.
aur/katrain 1.9.2-2 (+5 1.17) (Installed)
    A tool for analyzing and playing go with AI feedback from KataGo.
aur/katago-opencl 1.9.1-1 (+5 0.49) (Installed)
    Baduk engine with no human-provided knowledge.
    ```

**Comment by kylebakerio** [comment]
This is a closed issue about a very different video card and scenario, I think. You should probably start a new issue.
