### ISSUE TITLE
Plays each move minimum of "X" seconds thinking.

### ISSUE THREAD

**Issue by tunagoakademisi** [sanderland/katrain#348]
Before playing a game, an option " KataGo minimum thinking time for every move: 10 seconds (for instance) " would be really great i think. When i play KataGo it thinks at most  4-5 seconds at most on the strongest distributed model. Are there already an option to adjust it? Sorry for asking if there is one.

**Comment by sanderland** [comment]
There's max visits, setting this higher makes katago think longer, but the time of course depends on your computer, as well as caching.
