### ISSUE TITLE
Better scaling for dialogs

### ISSUE THREAD

**Issue by raspingbard** [sanderland/katrain#359]
The KaTrain go board looks gorgeous on a 4K monitor, but some of the checkboxes, icons, and text are almost too small to see.  There should be better scaling for higher resolution monitors.

![KaTrain](https://user-images.githubusercontent.com/28121941/108264163-6f008b00-7124-11eb-95aa-b43db8d94476.png)

**Comment by sanderland** [comment]
https://kivy.org/doc/stable/api-kivy.metrics.html
are sp(1) and dp(1) both 1?

**Comment by sanderland** [comment]
also how do the settings menus look? Scaling is hard!

**Comment by raspingbard** [comment]
Yes, scaling is hard.  :-(   But, apps looks beautiful on my 4K monitor.  I think these monitors will become more common as the prices drop.

See the attached png files.  The Settings menu is scaled and takes up the full height of the window, so it seems fine.

The Analysis menu and the dialogs are not scaled, and they appear too small.  They are fully functional, however.

Thanks,
-Eric

**Comment by sanderland** [comment]
I think kivy+mac is the main issue, things don't get picked up on. Possible the same as #243 ?

**Comment by raspingbard** [comment]
Yes, sounds like the same issue as #243.

I had partial success by overriding the Kivy env variable in the command line. 

————————————————
set KIVY_METRICS_FONTSCALE=1.8
"C:\Games\Go\KaTrain\KaTrain.exe”
————————————————

 More discussion about it in this thread <https://answers.microsoft.com/en-us/windows/forum/all/how-to-create-permanent-environment-variable-but/cc931c15-1702-4dab-a32c-5846c6ef7121>.  It gives nice control over the font and icon size in KaTrain:



However, the downside is that the small dialogs appear even worse.  Is there a Kiva variable to control the window size?  If not, maybe you could control the size within KaTrain.  Note that the main window also opens up very small initially.



Regards,
-Eric

**Comment by raspingbard** [comment]
Note that I’m using a PC, not a Mac.  I just download the Windows .exe.

-Eric

**Comment by sanderland** [comment]
It's hardcoded to aim for 1300x1000 and shrink when the monitor is too small. It is probably possible to save the last position/size in the config though.

**Comment by sanderland** [comment]
note my own resolution is 2560x1440

**Comment by raspingbard** [comment]
My resolution is 3840 x 2160.  It would be nice if KaTrain remembered the last window size.  You could also allow user control of the dialog size, which might fix the font problem.

**Comment by sanderland** [comment]
Window position/size saving implemented in 2711d5b
Screenshots of poor looking dialogs would help. They're all pretty fixed size now (well, based on the 'display unit', which might be influenced by some OS settings)

**Comment by raspingbard** [comment]
Great.  I won’t be able to test yours changes until the next release.

Do you want screenshots of all the dialogs in my current build or the next build?  What font scaling should I use?  I thought 1.8 looked best.

-Eric

**Comment by sanderland** [comment]
probably take something a bit crowded like analysis/teaching settings at scaling 1 and 1.8 then

**Comment by raspingbard** [comment]
General/Engine settings:

Font scale = 1.8

![General 1 8](https://user-images.githubusercontent.com/28121941/108633599-5b119d80-7432-11eb-824c-167cef7cb3d8.png)

Font scale = 1.0

![General 1 0](https://user-images.githubusercontent.com/28121941/108633604-61077e80-7432-11eb-99ef-73e598d83460.png)

Analysis/Teaching settings:

Font scale = 1.8

![Teaching 1 8](https://user-images.githubusercontent.com/28121941/108633620-6cf34080-7432-11eb-9134-bd4fa517d568.png)

Font scale = 1.0

![Teaching 1 0](https://user-images.githubusercontent.com/28121941/108633632-7b415c80-7432-11eb-9b82-d77d4520fa77.png)

**Comment by sanderland** [comment]
Wow, so basically the dialog size should scale with font size, and not display points or whatever

**Comment by raspingbard** [comment]
I believe so.  There should probably also be an easier way for users to customize the font scale.

**Comment by sanderland** [comment]
try KIVY_METRICS_DENSITY=1.8 as well maybe?

https://kivy.org/doc/stable/api-kivy.metrics.html

> The metrics cannot be changed at runtime.

**Comment by raspingbard** [comment]
Awesome!! The density setting seems to fix everything.  You don't need to set the font scale if you set the density.  With density = 1.6, the dialogs are nicely sized and the font size is just about perfect:

Timer settings:

![image](https://user-images.githubusercontent.com/28121941/108777702-75767480-7521-11eb-92c2-6adc59dca4b4.png)

Teaching settings:

![image](https://user-images.githubusercontent.com/28121941/108777776-8fb05280-7521-11eb-9a40-ca38f5b638b1.png)

AI settings:

![image](https://user-images.githubusercontent.com/28121941/108777801-9ccd4180-7521-11eb-9570-422a4aa9075e.png)

General settings:

![image](https://user-images.githubusercontent.com/28121941/108777878-bff7f100-7521-11eb-9ee0-1f548d4c7c3f.png)

The only slight problem remaining is the initial window size of 1300 x 1000, but if you're now saving the last size this should be solved.

![image](https://user-images.githubusercontent.com/28121941/108778809-2e897e80-7523-11eb-99cf-4516bb3c3511.png)

**Comment by sanderland** [comment]
To update instructions in #250, you can create a shortcut with different scaling using:

*    From Desktop, right-click to create a New>Shortcut.
*    Right-click on the resulting Shortcut and open its Properties.
*    Enter the following in the 'Target' box: C:\Windows\System32\cmd.exe /k set KIVY_METRICS_DENSITY=1.8 & C:[FilePathTo\katrain.exe]
*    The easiest way to find the complete and correct file path for KaTrain, is to right-click on the .exe file, open its Properties, click the Security tab and then copy the full file path you'll see there.
*    Finally, copy this instruction into the 'Start in' box: %HOMEDRIVE%%HOMEPATH%
*    Close the Shortcut - or stick around to change the icon to something nicer than the Shortcut default.

**Comment by Ryan64772** [comment]
How would you change these settings on Mac? I am having the same problem as a mac user.

**Comment by horaceho** [comment]
KaTrain now supports setting KIVY options via command line:
```
% katrain -h                         
Kivy Usage: katrain [KIVY OPTION...] [-- PROGRAM OPTIONS]::

            Options placed after a '-- ' separator, will not be touched by kivy,
            and instead passed to your program.

```
For example, start `katrain` in macOS Terminal:
```
katrain KIVY_METRICS_FONTSCALE=0.75
```
