### ISSUE TITLE
 Time setting does not seem to be powerful

### ISSUE THREAD

**Issue by egBean** [sanderland/katrain#360]

**Comment by sanderland** [comment]
I don't understand. If you use google translate, please include the original text as well so others can help.

**Comment by egBean** [comment]
我在时间设置里配置了最小思考时间。但是下棋时候好像没有效果。

**Comment by sanderland** [comment]
![Uploading thetimerisfine.gif…]()

**Comment by egBean** [comment]
谢谢，我明白了。是设置人类思考时间~我以为配置ai思考时间
