### ISSUE TITLE
Use a specific custom tag to avoid reloading generated playernames instead of zero-width space unicode characters

### ISSUE THREAD

**Issue by xiaoyifang** [sanderland/katrain#368]
1: the sgf saved by katrain, loaded into other sgf tools such as lizzie ,the playname can not display properly.
![Snipaste_2021-02-27_11-19-09](https://user-images.githubusercontent.com/105986/109374428-30bb5680-78f0-11eb-8452-9b8a1e4740b0.png)
2: the sgf saved by katrain ,when loaded into katrain ,the right top play name does not display 
![image](https://user-images.githubusercontent.com/105986/109374484-7f68f080-78f0-11eb-8611-a32b31d12bce.png)
[KaTrain_C vs D 2021-02-27 11 35 30.zip](https://github.com/sanderland/katrain/files/6053666/KaTrain_C.vs.D.2021-02-27.11.35.30.zip)

**Comment by sanderland** [comment]
Fixed in 7949d9f  I think, although this entire player logic could use a major refactor

**Comment by xiaoyifang** [comment]
it look like fixed

**Comment by sanderland** [comment]
Reopened/renamed after a suggestion in #369 to use a custom tag, which is an interesting idea
