### ISSUE TITLE
M1 binary?

### ISSUE THREAD

**Issue by peepo** [sanderland/katrain#370]
please could you clarify:

"Users with the last generation M1 macs with different architecture should download this bundle and then brew install katago and point KaTrain to their own binary in general settings, as the built-in binary is not compatible."

is there an M1 binary? where is it? how to install...

if so, are Linux & OS X both supported?
currently there may be or is an issue with linux & GPU access on mac mini M1

I'd like to buy a mac mini specifically to run 9x9 Go training software at professional level,
if this is possible?

currently 4 dan and struggling to improve at all.

thank you

**Comment by sanderland** [comment]
It should pick up on the correct binary after you run `brew install katago` to compile locally

**Comment by sanderland** [comment]
Any other questions in #331 or discord/gui please :)

**Comment by peepo** [comment]
ah! thanks for the prompt response,

had searched open issues, but missed #331 
possibly due to long title?

maybe rename: All 2020 Mac M1 issues
