### ISSUE TITLE
enhancement: troubleshooting

### ISSUE THREAD

**Issue by peepo** [sanderland/katrain#373]
please add:

in case of: CL_PLATFORM_NOT_FOUND_KHR
use: sudo apt-get install mesa-opencl-icd 

or similar

tx

**Comment by sanderland** [comment]
So you're saying the current advice to use `ocl-icd-opencl-dev` is incorrect?

**Comment by peepo** [comment]
not at all!

on my
ubuntu 20.04 
clover mesa opencl 1.1 20.0.4 OpenCL 2.1
Intel Graphics 4000 IVB GT2

ocl-icd-opencl-dev does not remove error  CL_PLATFORM_NOT_FOUND_KHR
neither does:
mesa-opencl-icd
whereas mesa-opencl-icd does

however there remains a permission issue: unable to open device /dev/input/event17
then
Found OpenCL Platform 0 Clover...kisak-mesa PPA 
Found 0 device(s) on platform 0 with type CPU or GPU or acclerator, skipping

found & installed kisak-mesa rebooted

Found OpenCL Platform 0 Clover...kisak-mesa PPA 
Found 0 device(s) on platform 0 with type CPU or GPU or acclerator, skipping

all efforts result in status -6

best
xx

**Comment by peepo** [comment]
ocl-icd-opencl-dev 

https://github.com/intel/compute-runtime
seems only recent Intel processors are supported 
& Intel Beignet is a whole nother story

tx

**Comment by peepo** [comment]
see #374 
afaict ocl-icd-opencl-dev is for Itel chips only!
so as this is mesa, clearly not going to function.

not clear to me, how to take this forward

**Comment by peepo** [comment]
just to confirm all three additional downloads are needed

**Comment by deegeebee** [comment]
Right now, the Intel Neo download seems to be working on Ubuntu 20.04 for me. (I had to install numpy too, but that's a different issue, if any.)
Now the AI is playing. 

However, I have an error warning in the terminal while it's open, so I'll see if it gets stuck somewhere
[CRITICAL] [Cutbuffer   ] Unable to find any valuable Cutbuffer provider. Please enable debug logging (e.g. add -d if running from the command line, or change the log level in the config) and re-run your app to identify potential causes

...

@peepo I'm wishing you luck, plus myself too!
@sanderland Please keep hanging around

**Comment by deegeebee** [comment]
Quote: The app crashes with an error about "unable to find any valuable cutbuffer provider"

    Install xclip using sudo apt-get install xclip
... rtfm :D

**Comment by peepo** [comment]
Two things to consider,
Please do not just add comments to an irrelevant bug report, open another one...
Your preferred search engine is your friend!

If I can find katrain + CL_PLATFORM_NOT_FOUND_KHR
so can you...
try: https://github.com/sanderland/katrain

The app crashes with an error about "unable to find any valuable cutbuffer provider"
    Install xclip using sudo apt-get install xclip

good luck!

**Comment by deegeebee** [comment]
Sorry, misunderstanding. I commented on my own post that I found just what you suggested by reading the readme.

Sorry for threadjacking too.
