### ISSUE TITLE
Territory Scoring or Area Scoring

### ISSUE THREAD

**Issue by MrFangxuxu** [sanderland/katrain#378]
It could be nice if Katrain can calculate the area or the territory.

**Comment by sanderland** [comment]
You mean at the end of the game, instead of relying on katago? How should it handle dame?

**Comment by MrFangxuxu** [comment]
Just like these.
![image](https://user-images.githubusercontent.com/72303942/110206897-6ac1c500-7ebb-11eb-883e-a5a9cb354b4e.png)
![image](https://user-images.githubusercontent.com/72303942/110206901-72816980-7ebb-11eb-8682-9aa4d3bfafbc.png)
Use Katago to estimate and score.

**Comment by MrFangxuxu** [comment]
> You mean at the end of the game, instead of relying on katago? How should it handle dame?

Just like these.
![image](https://user-images.githubusercontent.com/72303942/111029753-550f4b00-8439-11eb-9b34-ceffa2da5cb4.png)
![image](https://user-images.githubusercontent.com/72303942/111029759-5b052c00-8439-11eb-8343-0e56305f6f8f.png)

Use Katago to estimate and score.

**Comment by sanderland** [comment]
After some consideration, this is such low priority for me that it won't happen
