### ISSUE TITLE
How to change the character-set?

### ISSUE THREAD

**Issue by wonsiks** [sanderland/katrain#38]
I can't write note in Korean language and I can't read Korean character when browsing to open sgf file to analyze.
Is there any setting which I can edit to change program character-set?
![20200521_131036](https://user-images.githubusercontent.com/37356450/82522468-7f1f1600-9b64-11ea-8eef-233630f3a087.png)
![20200521_131117](https://user-images.githubusercontent.com/37356450/82522496-978f3080-9b64-11ea-960b-247d7da80afb.png)

**Comment by sanderland** [comment]
Thanks for the report.
This is a font issue, I will likely fix this in v1.1 when looking into internationalization as well.

**Comment by wonsiks** [comment]
@sanderland Thanks a lot.

**Comment by sanderland** [comment]
marking this as resolved in v1.1
