### ISSUE TITLE
curl cert error when trying to do a distributed run on Windows

### ISSUE THREAD

**Issue by apetresc** [sanderland/katrain#380]
After setting up the new distributed training feature, it immediately errors out with:

![image](https://user-images.githubusercontent.com/14872/110219076-1272cf00-7e8b-11eb-9556-18f1830a103a.png)

My guess is I have a curl compiled against the wrong version of libssl or something. I'm going to try investigating this on my own, but I thought I'd post the issue right away in case someone else has direct experience with this exact problem.

**Comment by apetresc** [comment]
Okay, as suggested by the error, grabbing the Mozilla CA store [from the cURL site](https://curl.se/docs/caextract.html) and dropping it into `~/.katrain/cacert.pem` resolved the problem. Still, I'm not sure why curl wasn't able to find/use a system-wide cert store. Most users probably won't figure this out on their own. Should katrain distribute `cacert.pem`, or is there something else wrong with my copy of curl?

**Comment by sanderland** [comment]
Hmm is this with the default, or one of the other downloaded katago binaries? The latter makes sense, and I can try to fix it with the -cacerts option

**Comment by sanderland** [comment]
should be fixed in a94dcac
