### ISSUE TITLE
Performance throughout the game overview/rating

### ISSUE THREAD

**Issue by sektorate** [sanderland/katrain#388]
Hello, many thanks for this amazing trainer! Feature suggestion: I imagine each move being placed in categories (e.g. blunder, mistake, inaccuracy, okay, excellent, best move) based on the percentage change in winrate it effects. The percentage ranges for these categories could be user definable.
An overall "accuracy" score out of 100 could then be generated for each player based on the percentage of their moves the engine rates as best. These ideas are inspired by the analysis features of chess.com, that give an overall insight into the players' performance in a game; this would supplement analysis of each individual move.
Thanks again for your work, I'd love to hear your thoughts.
![Screenshot (2)](https://user-images.githubusercontent.com/80420199/110680682-33178d80-81d9-11eb-92ca-8c1262c7aef9.png)

**Comment by sanderland** [comment]
Some discussion of this in #340 - it's a bit strange to suggest adding categories when they already exist though :)

**Comment by sektorate** [comment]
You're right, of course!

**Comment by sanderland** [comment]
Some experiments on this in the 1.9 branch, starting with a 2d table of point loss vs policy.
Could have an option for policy <-> ai order as well, but this is simpler for now.
Space for lots more, maybe some summary stats.

@pdeblanc thoughts?

Random dan game:

![image](https://user-images.githubusercontent.com/48946947/114414085-d11ebf00-9bae-11eb-82f1-6bffe4d1bc81.png)

Random ddk game:

![image](https://user-images.githubusercontent.com/48946947/114414648-4be7da00-9baf-11eb-8e95-40b545a34692.png)

**Comment by sanderland** [comment]
1d layout instead of 2d

![image](https://user-images.githubusercontent.com/48946947/114441796-1e5d5980-9bcc-11eb-88c0-dee5ef7d09cb.png)

**Comment by sanderland** [comment]
idea by marcel
![image](https://user-images.githubusercontent.com/48946947/114450994-0212ea00-9bd7-11eb-8055-d352fa6fdb63.png)

**Comment by sektorate** [comment]
On first impression, 1d layout seems more easily readable than 2d. Some questions to aid iteration:

-Is it possible to create an overall performance score? e.g. if every move lost no points/was the AI top move this gives a 100% accuracy, if every move lost more than 12 points/was the AI worst move gives 0%. This would provide extra insights: "did I win because I played well, or because my opponent played terribly?", "I lost even though my performance was good so this loss isn't so bad".

-Is it possible/would it be useful to combine the points lost/AI rank into one overall metric? An overall score of each move would be more concise.

Overall it would be great to give the user control over the level of granularity, i.e. whether 2d or 1d, which stats are shown; whether the moves are shown graded separately by points lost/AI top move or whether these are combined into one metric etc.

I hope these thoughts help, I love this feature already and am excited to use it.

**Comment by raspingbard** [comment]
The Chess.com site really did a nice job with their game report.  However, they probably have 100+ developers working for them.  Here's a simple version of their accuracy report.  It would allow users to customize the category names in the Teaching/Analysis settings.  Instead of a separate Game Report, this could also be just another tab, unless you're planning to add additional information in the future.
  
The accuracy stat would be a weighted average of the categories.  Ideally, this accuracy information would update as users moved through the game tree, not just at the end of the game.
  
Note that all chess apps and sites (that I've seen) use strictly board evaluations for computing mistakes, i.e. top move - actual move.  There's no reporting done on how much a move improves the prior position, i.e. actual move - prior move.  We've discussed this before.
  
P.S.  I don't know how useful the 2D performance table would be.  It seems more like a curiosity rather than helpful information.  But, I guess it might show how well your intuition (policy) is working versus your calculation (tree search).  The accuracy information seems more helpful.

![image](https://user-images.githubusercontent.com/28121941/114624526-148c3280-9c6e-11eb-9f6b-66f8dd529fdf.png)

![image](https://user-images.githubusercontent.com/28121941/114624382-d55de180-9c6d-11eb-8dbb-faf8161a9241.png)

**Comment by sanderland** [comment]
![image](https://user-images.githubusercontent.com/48946947/114740608-4bd01180-9d4a-11eb-97e4-293cf8ecde6d.png)

movecomplexity = sum(policy over candididates) - sum(policy over candididates with point loss <= 0.5)  i.e. what policy % is bad moves the ai thought were worth considering.
complexity = average movecomplexity 
weighted_loss = point loss weighted by min(movecomplexity ,0.25) for dark green moves, or 0.25 for mistakes, i.e. trying to downweigh obvious moves
accuracy = 100 * 0.75**weighted_loss

formulas aren't great yet. but I like the layout and fields

**Comment by sektorate** [comment]
^ this looks great! being able to focus on one stage of the game is an excellent idea.

**Comment by raspingbard** [comment]
Sander, I like it!  Much improved over my version. :-)

I'm working on trying to understand your formulas.  What is the cutoff point for the AI candidates, or is this determined by max_visits?  Wouldn't higher visits skew the complexity rate upwards (more poor moves searched?)

The accuracy formula seems reasonable.  I want to research to see how some of the chess apps do it.

I think the colors on the Teaching/Analysis settings should be re-ordered to match this for consistency.

Good stuff!

**Comment by sanderland** [comment]
it's using all candidate moves returned by the ai, this is of course influenced by visits, root noise, etc. 
the idea is that the sum of policy priors over low-pointloss candidates represents 'obvious good moves' and the remainder 'nice looking but not good moves' and your move should be rewarded if the latter is big.

I am not convinced this is the best approach, but it's the first thing that kind of did something reasonable.

**Comment by sanderland** [comment]
> I think the colors on the Teaching/Analysis settings should be re-ordered to match this for consistency.

c2ca285

**Comment by raspingbard** [comment]
I did some quick research on Go and Chess apps, and the only one that seems to calculate a game accuracy is Chess.com.  They call theirs "Computer Aggregated Precision Score" or CAPS.  It's a proprietary model that incorporates game mistakes and other "pattern of strength" algorithms.  In other words, it is a black box.

There's some controversy in the forums about how well it works.  Apparently, the statistic can vary widely over games, and it does not give a great predictive power into the rank of a player.

Links [here ](https://www.chess.com/article/view/better-than-ratings-chess-com-s-new-caps-system#:~:text=Chess.com%27s%20Computer%20Aggregated%20Precision%20Score%20%28or%20CAPS%29%20is,the%20quality%20of%20moves%20of%20any%20chess%20game.) and [here](https://support.chess.com/article/1135-what-is-accuracy-in-analysis-how-is-it-measured).
 
As for complexity, I think your idea has merit.  I spent some time studying L&D problems earlier trying to understand why some were more complex than others.  The number of reasonable-looking branches in the search tree has mostly to do with it.  Whether you can tease this information out of differences between policy priors and search results will be interesting.

This feature may take lots of thought and testing.  I vote to roll out something simple and get feedback on it. Maybe create a beta version that we can do some testing on.

**Comment by sanderland** [comment]
> This feature may take lots of thought and testing. I vote to roll out something simple and get feedback on it. Maybe create a beta version that we can do some testing on.

I generally don't hide things, it's in branch and anyone can test it. Releasing is a lot of work though, and the last time I released for feedback I got zero comments, soooo

**Comment by sanderland** [comment]
testing another weighting in 3adde54
this time based on the policy-weighted point loss

**Comment by xiaoyifang** [comment]
![image](https://user-images.githubusercontent.com/105986/115676567-4a25cf80-a382-11eb-9cf8-3c2e586b07c3.png)
this part can be replace with a chart like this. more intuitive
![image](https://user-images.githubusercontent.com/105986/115676506-3ed2a400-a382-11eb-9c09-fbb24e452361.png)

**Comment by sanderland** [comment]
want to test this a bit more properly. if someone could help collect a nice test set that would be appreciated:

A variety of around 50-100 sgf games from 15k to 7d. 19x19, at least 200-250 moves played. Should have the BR and WR fields set (as in e.g. ogs)

**Comment by raspingbard** [comment]
I'll commit to scraping 50 games from OGS spread across 15k to 7d.  Does it matter if they're even or handicap?

**Comment by sanderland** [comment]
Shouldn't matter. The idea is to see the numbers by player rank more systematically

**Comment by raspingbard** [comment]
Here are 30 OGS games ranging from 9k to 4d.

[10 OGS games 1d-4d.zip](https://github.com/sanderland/katrain/files/6410151/10.OGS.games.1d-4d.zip)
[10 OGS games 1k-4k.zip](https://github.com/sanderland/katrain/files/6410152/10.OGS.games.1k-4k.zip)
[10 OGS games 5k-9k.zip](https://github.com/sanderland/katrain/files/6410153/10.OGS.games.5k-9k.zip)

**Comment by sanderland** [comment]
code as in dde545b (weighted by complexity ~ expected point loss if playing candidates with p=policy)
40b 7.9G

![image](https://user-images.githubusercontent.com/48946947/116822670-68f54480-ab80-11eb-9673-4117878cf525.png)

data: https://pastebin.com/k44TYjY9

accuracy seems ok, a bit weird on 2 outliers. complexity is a bit all over the place, may just remove it.

**Comment by raspingbard** [comment]
20 more OGS games

[10 OGS games 4d-7d.zip](https://github.com/sanderland/katrain/files/6412723/10.OGS.games.4d-7d.zip)
[10 OGS games 10k-15k.zip](https://github.com/sanderland/katrain/files/6412724/10.OGS.games.10k-15k.zip)

**Comment by sanderland** [comment]
with new games included. r^2 added and added 'ai approved' stat (move in top 5 and pt loss <0.5, could have a better name)
![image](https://user-images.githubusercontent.com/48946947/116872340-fe8ee380-ac15-11eb-89e4-fda3b9220c4a.png)

**Comment by sanderland** [comment]
Flat weights (i.e. not trying to downweigh obvious moves to reduce effect of opening/endgame)
![image](https://user-images.githubusercontent.com/48946947/116875336-04d38e80-ac1b-11eb-9906-51f89ceae0d7.png)

suggests the weighting does something useful at least!

**Comment by sanderland** [comment]
old idea:
```
good_move_policy = sum(d["prior"] for d in filtered_cands if d["pointsLost"] < 0.5)
etc
```
![image](https://user-images.githubusercontent.com/48946947/116878809-24b98100-ac20-11eb-99ed-3aa9139447af.png)

definitely worse

**Comment by sanderland** [comment]
adj_weight = max(0.025, min(1.0, max(weight, points_lost / 5)))
![image](https://user-images.githubusercontent.com/48946947/116896983-1033b380-ac35-11eb-80f6-b1c1b9e5ae9c.png)

worse?

**Comment by sanderland** [comment]
weight = min(1.0, sum([max(d["pointsLost"], 0) * d["prior"] for d in filtered_cands])/sum(d["prior"] for d in filtered_cands))
adj_weight = max(0.05, min(1.0, max(weight, points_lost / 4)))
![image](https://user-images.githubusercontent.com/48946947/116901603-6bb47000-ac3a-11eb-9d12-f7d05356e7bc.png)

no major difference, but makes a little more sense.
keeping this unless there's any bright ideas

**Comment by raspingbard** [comment]
The accuracy stat r^2 is looking pretty good.  The complexity stat will need some more thinking.

>  'ai approved' stat (move in top 5 and pt loss <0.5, could have a better name)

Agree that 'ai approved' is a bit awkward.  If you had category labels for pt loss, you could use the label.  Not sure you need to limit it to top 5, but just the pt loss range seems good enough.

Let me know if you need more games for testing.

**Comment by sanderland** [comment]
> The accuracy stat r^2 is looking pretty good. The complexity stat will need some more thinking.

Will probably just kill the complexity stat.

> > 'ai approved' stat (move in top 5 and pt loss <0.5, could have a better name)
> 
> Agree that 'ai approved' is a bit awkward. If you had category labels for pt loss, you could use the label. Not sure you need to limit it to top 5, but just the pt loss range seems good enough.

The idea is that top 1 is very network dependent, and no limit is very visits dependent, this should be less so (as seen by katago selfplay games ending up at near 100%)

> Let me know if you need more games for testing.

I think this is a very nice data set. If you can figure out what's up with the 1-2 outliers that might help though!

**Comment by raspingbard** [comment]
In the first outlier game (sunny25 vs lyq), both players missed the killing/saving of a group for many moves (163 - 202).  This resulted in 20+ point loss swings for a significant portion of the game.

[33352666-265-sunny25-lyq.zip](https://github.com/sanderland/katrain/files/6418820/33352666-265-sunny25-lyq.zip)

<img src="https://user-images.githubusercontent.com/28121941/116956192-dc1abb80-ac51-11eb-85ac-eba6cbb62341.png" width="500" height="500">

In the second outlier game (silent1 vs sunny25), both players missed a severe cut for many moves (49 - 126).  Then, they missed a double sente endgame sequence for many moves (131 - 187).

[33352369-209-silent1-sunny25.zip](https://github.com/sanderland/katrain/files/6418821/33352369-209-silent1-sunny25.zip)

<img src="https://user-images.githubusercontent.com/28121941/116956082-9cec6a80-ac51-11eb-93b4-c15374f880fc.png" width="500" height="400">

<img src="https://user-images.githubusercontent.com/28121941/116956163-c86f5500-ac51-11eb-8f62-9232acff9d08.png" width="600" height="400">

**Comment by sanderland** [comment]
![image](https://user-images.githubusercontent.com/48946947/117572283-80798380-b0d2-11eb-9f69-d827975793ec.png)

thoughts on comparing the blunder classes to the other player compared to all moves?

**Comment by sanderland** [comment]
Also if someone has/can make a texture that helps make the bars look like bars, that could be nice! (as in transparency mask-only texture)

**Comment by Dontbtme** [comment]
Here's a mockup I made of what I think would be the most useful to review my games.
It shows everything from each player's point of view, so no matter how well or bad White played, if Black played 104 green moves out of his own total of 152 moves, then his percentage bar should be filled about 68%.
Now, if instead we want to share stats between players for some reason (meaning 'Black played 80% of the red mistakes played in the game, which means White played only 20% of them'), then that could be an option toggled in the Teaching/Analysis Settings. That way we could get the best of both worlds.
What do you think?
![Report-Mockup-Proposal](https://user-images.githubusercontent.com/66470440/117627410-6c885d00-b178-11eb-83dd-d5690462ca1e.JPG)

**Comment by sente361** [comment]
Here is a suggestion for a more natural graphic for the Points Lost area:

![image](https://user-images.githubusercontent.com/47664082/117637956-b21f4700-b1c5-11eb-9f92-c0fbd6b5fd3e.png)

**Comment by Dontbtme** [comment]
Even though a pyramid looks more natural from a graphical standpoint, the base may not be always the widest (for a double digit kyu maybe?). And I don't know, do we usually see best moves as "top" moves, visually speaking?
In any case, I came up we another mockup that would combine Points lost seen from 1 player only's perspective as well as from both players'.
How does it look?
![Report-Mockup-Proposal04](https://user-images.githubusercontent.com/66470440/117665906-9c008f00-b1a3-11eb-8ecf-b12be76914fb.JPG)

**Comment by sektorate** [comment]
This version of the panel seems a little cluttered. I'm not sure how useful seeing the proportion of points lost between each player is either, I personally would be interested mostly in the amount/% of my moves that fall into each category. If a user is that interested in the proportion between each player, they can compare the numbers.
Having best moves shown at the top makes sense to me also.

**Comment by raspingbard** [comment]
> This version of the panel seems a little cluttered. I'm not sure how useful seeing the proportion of points lost between each player is either.
> Having best moves shown at the top makes sense to me also.

^^^ Agree.

I think Sander has the cleanest layout.  You don’t want to make it more complicated than this.  The X-axis scale for each item can usually be inferred from the label, which is good.

I think showing the bars for all move classes is fine to achieve consistency. Except, I don’t understand the X-axis scale used in Sander’s version (what are the blunder lengths suppose to be?).  I would think this should be the % of time you played that move class within the game.

**Comment by Dontbtme** [comment]
I'm also only interested in the % of moves that fall into each category (separately for each player).
I only added the % sharing both players' data as a whole because that was what Sander went for initially.
Anyway, you'll see below my last mockup. This one is the closest to what I would go for if it was up to me.
Your thoughts?
![Report-Mockup-Proposal05](https://user-images.githubusercontent.com/66470440/117719805-22d25d80-b1de-11eb-9255-d80c988c6f10.png)

**Comment by sektorate** [comment]
^ This looks great to me.

**Comment by sente361** [comment]
I prefer Sander's latest iteration;  a microsecond glance - "I got mostly green - yippee!" (Coloring the bars makes the data leap out at you.) In the same vein, I would also color the bars in the Key Statistics section; a nice blue would be look good.

**Comment by sente361** [comment]
In my opinion it is simpler and easier to understand if the central "key" of the Points Lost section is presented in this form:

![image](https://user-images.githubusercontent.com/47664082/117897729-c028b100-b306-11eb-8802-ba2ff545f19f.png)

**Comment by Dontbtme** [comment]
In Sander's version I think the middle part should be less prominent and somehow detached from the bars left and right, cause to me it kind of seemed like every color was played a lot no matter what.
I tried two mockups. They're not great but they'll show what I mean
![Report-Mockup210512a](https://user-images.githubusercontent.com/66470440/117926578-450cce00-b2f9-11eb-8f05-f090b7bdf0ea.png)
![Report-Mockup210512c](https://user-images.githubusercontent.com/66470440/117928605-16442700-b2fc-11eb-868e-c8686526a40d.png)

**Comment by sanderland** [comment]
![image](https://user-images.githubusercontent.com/48946947/117942867-d127f100-b30b-11eb-985a-e7287f2b17c1.png)
maybe better blue. 

@Dontbtme sure that looks better, but keep in mind the whole thing is a single grid layout of labels, and the line is the bottom of the header cell. Give it a try and you'll see how difficult simple things can be in kivy ;)

**Comment by Dontbtme** [comment]
Still, as is, any bar looks big is what I meant. Can't you limit the colors in the middle around >0.5 etc. without changing the grid? Since colors in the left and right column are moving around depending on the %, why colors in the midle column have to fill it entirely? Colors in the middle are what's popping up the most in your picture, when we should be focusing on colors from the player's bars. I would even rather not having any colors in the middle colomn if that's too complicated, that way the mistakes's data colors would appear clearly and brightly on each players's column
Anyway, that's only my two cents (although I'm not sure about the dark blue you switched to in the key statistics since the all around UI is already some kind of dark blue...
But anyway, if the above isn't convincing, then maybe that's just a matter of taste.

**Comment by xiaoyifang** [comment]
![image](https://user-images.githubusercontent.com/105986/117986615-5f33c400-b36c-11eb-9bf2-0548fa43dc3a.png)
seems wrong value >100%

**Comment by sanderland** [comment]
> ![image](https://user-images.githubusercontent.com/105986/117986615-5f33c400-b36c-11eb-9bf2-0548fa43dc3a.png)
> seems wrong value >100%
I think this bug was fixed and you have an old commit

**Comment by raspingbard** [comment]
For statistics and the point losses, you could report both the percentage and absolute count where needed together, instead of having separate columns, or not reporting both values.  Also, there would then be no need to put "%" in the labels.

![image](https://user-images.githubusercontent.com/28121941/118011527-5e1f7a00-b30d-11eb-9156-bfe8c376457f.png)

**Comment by xiaoyifang** [comment]
as already there are many suggestions now :-) .
I recommend this
![image](https://user-images.githubusercontent.com/105986/118095727-02cfb380-b403-11eb-971a-689f02f074b7.png)

in the upper area ,the better value have a significant background color (green etc).
the lower part 's bar can be aligned together.

the advantage of this is ,just one glimpse ,you know who does better.and which value is higher .
without the need to read the number.

**Comment by sanderland** [comment]
Closing this as it's soon released, but feel free to continue discussion.
