### ISSUE TITLE
add PV as branch

### ISSUE THREAD

**Issue by adzweig** [sanderland/katrain#389]
Hi,
when I click on a proposed top move, katrain shows the best sequence to the depth analyzed so far. It would be nice to have the option to demand with a key stroke or mouse klick a deeper analysis, i.e. analyse further from the position reached in the sequence shown. 

rgds

Adrian

**Comment by sanderland** [comment]
This has been suggested before, but the latter moves are very uncertain, and I'm not sure how to handle that.
I personally just click through variations or use enter, is this too slow for you?

**Comment by sanderland** [comment]
could be an option when the new scroll wheel thing is used, like click the scroll wheel?

**Comment by sanderland** [comment]
Added in 829a33f67a6acf13341953d875b66feb1573487c
