### ISSUE TITLE
Wish: do not dot KaTrain’s move until I answer it

### ISSUE THREAD

**Issue by PJTraill** [sanderland/katrain#39]
#### Problem
I have noticed that it is a great but undesirable help to see whether KaTrain’s latest move is good or not rather than having to decide that myself, but I can only suppress this by altogether suppressing dots for the AI player. This option is perhaps good when playing a normal game against an AI, but for a teaching game it seems best to me to provide feedback as soon as I have made my decision. The problem does not, of course, arise, when playing a full strength AI, but when playing a weakened AI it is is unfortunate.

#### Proposal
Might I suggest an option (enabled by default) not to put a dot on KaTrain’s move until it is answered by the user?

#### P.S.
I have just successfully upgraded to 1.0.6 and am, being about 7 or 8 kyu, practising with teaching games against **P:Tenuki** and plain games against **P:Pick**. I think this is very useful, but I think Lizzie may be more helpful for analysis.

**Comment by sanderland** [comment]
I usually just disable AI dots for teaching games completely, for this exact reason, but I'll keep it in mind for the 1.1 redesign.
It is hard to handle these edge cases without becoming an incomprehensible pile of hidden interactions or options though!

PS: I can recommend P:Weighted or ScoreLoss, as I am about your level. keep in mind that a single undo is enough to beat human ~1d players in an even game -- it's really a huge advantage!

**Comment by sanderland** [comment]
Closing this as won't do, since the hide AI dots covers this.
