### ISSUE TITLE
Why can't version 1.8.3 Katrain give me the instant response with moves

### ISSUE THREAD

**Issue by Miaoqi-2010** [sanderland/katrain#390]
Hi Guys,
is there anyone who could help me out? my Katrain version is 1.8.3, when I try to give a try of one move, it looks like Katrain is thinking forever without an instant response. (but in previous version1.7.4, after giving a try, the Katrain tend to give me an instant response with many moves options
(I once installed Baduk pack days ago, i don't know if that is a reason causing some issues).
![Screenshot - 2021-03-13 , 15_09_32](https://user-images.githubusercontent.com/80569135/111023105-07cbb300-8412-11eb-89ff-88deb0ed8f30.jpg)
![02](https://user-images.githubusercontent.com/80569135/111023108-0bf7d080-8412-11eb-8187-6b4a723c0bb9.png)

**Comment by sanderland** [comment]
I have no idea what katago version baduk megapack distributes, but try to change the executable back to default/blank?

**Comment by Miaoqi-2010** [comment]
thanks anyway. I tried to change them to default or blank, but it looks there is not good result: Katrain says"can't find config file", I guess this issue could be related to some system enviroment variables which have been changed to different situation...

**Comment by sanderland** [comment]
Try changing config file path back to the default of `katrain/KataGo/analysis_config.cfg`
