### ISSUE TITLE
Analysis mode keyboard shortcuts that make sense

### ISSUE THREAD

**Issue by electricRGB** [sanderland/katrain#392]
It seems to me like the shortcuts for doing stuff, especially analysis, are pretty arbitrary. I'd like to propose a new set of shortcuts that make logical sense and don't require memorization or checking what's what. These are accompanied by some renaming of a few options to make everything really tie together.

Command | Proposed New Name | Current Shortcut | Proposed Shortcut
------------ | ------------- | ------------- | -------------
Next Moves | | q | n
Show Dots | | w | d
Top Moves | | e | t
Policy Moves | | r | p
Expected Territory | | t | shift-t
Deeper Analysis | | a | a
Equalize visits of potential moves | | s | e
Fast analysis of all moves | Quick analysis of all moves| d | q
Find alternative moves | | f | f
Set region of interest | | g | g
Reset analysis|  | h | r
Insert moves | | i | i
Fast playout to game end | Swift playout to game end | l | s

Some of these new shortcuts conflict with other existing shortcuts. Here is a table fixing those.

Conflicting shortcut | Current Shortcut | Proposed Shortcut
------------ | ------------- | -------------
Pass | p | shift-p
As in clicking the forward red arrow | n | m (as in, Mistake)
As in clicking the backward red arrow | shift-n | shift-m

I'm curious to see if these changes are popular and if there's support for getting them made. Ideally, this should be approached from a usability point-of-view, rather than a "I'm already used to these shortcuts and I don't like change" point of view. If there are arguments for why the current shortcuts are better, I'd love to hear them. :)

**Comment by sanderland** [comment]
qwert are at the top and lining up with the UI layout. These are used a lot and make a lot of sense to me.
asd... are the row below and line up with the analysis menu...kind of. More recent options are a bit more ad-hoc and sometimes just running out of keyboard space.

Keep in mind that the program supports 8 languages, so the first letter in English may lead to more arbitary shortcuts for many.

**Comment by electricRGB** [comment]
Ah that's fair.
I use a Dvorak keyboard so the layout made absolutely no sense to me, but this does make sense. Cool.

Ty. I'll close this issue.

**Comment by sanderland** [comment]
ah i had never thought of dvorak, have opened #393 for adding some kind of way of customizing

**Comment by electricRGB** [comment]
Amazing. Tyvm! :D
