### ISSUE TITLE
allow customizing keyboard shortcuts

### ISSUE THREAD

**Issue by sanderland** [sanderland/katrain#393]
maybe in config at first
cf #392

**Comment by sanderland** [comment]
working on this in 1.9 @electricRGB

**Comment by sanderland** [comment]
made an example in 8b68859
If anyone wants to help with this rather tedious task, that would help a lot.

**Comment by electricRGB** [comment]
Heya. I'm happy to help with this, but my schedule is a bit hectic right now. When, ideally, would you like it done by?

**Comment by sanderland** [comment]
translations typically take ~2 weeks, so somewhere by the weekend of 22/23?

**Comment by electricRGB** [comment]
Made a [PR](https://github.com/sanderland/katrain/pull/420)
