### ISSUE TITLE
sound does not work

### ISSUE THREAD

**Issue by adzweig** [sanderland/katrain#395]
I installed version 1.8.3 using pip3. Everything works except the sound. I obtain the error messages 
[CRITICAL] [AudioSDL2   ] Unable to open mixer: b'No such audio device'
[WARNING] [AudioSDL2   ] Unable to load /home/adrian/.local/lib/python3.8/site-packages/katrain/sounds/countdownbeep.wav: b"Audio device

Any idea how I can fix this?
thanks a lot for this great app !!

**Comment by sanderland** [comment]
https://github.com/sanderland/katrain/blob/master/INSTALL.md mentions this and provides a fix - which part of this isn't clear?
