### ISSUE TITLE
How to shut down the calculation of the engine in the background when playing against the points? 

### ISSUE THREAD

**Issue by CKLIA** [sanderland/katrain#398]
Excuse me, 
   Because computer graphics cards are relatively low-end. When I want to close the game with AI, the AI background does not calculate my (human) step. Can it be set? 

 Because it is a low-end graphics card computer that takes a long time to calculate a move, if two moves are calculated at the same time, it will affect the number of simulated moves for the latest move.

**Comment by sanderland** [comment]
No, this is not possible. Just use a lower number of visits.

**Comment by CKLIA** [comment]
Okay, I get it now.

**Comment by CKLIA** [comment]
But when using a small number of visits or a short visit time to play against the Kata jigo mode, what should be done to solve the problem that the AI is too passive to train oneself to improve the chess power effect?

**Comment by CKLIA** [comment]
> 
> 
> 但是，当使用少量访问或较短访问时间来对抗Kata jigo模式时，应该如何解决AI过于被动而无法训练自己以提高象棋力量效果的问题呢？

**Comment by sanderland** [comment]
Please don't open multiple issues. The leela discord is there if you want to chat.
Yes, using lower number of visits will make it less good at finding moves. widerootnoise can compansate for this a bit. But overall, it's your tradeoff to make given the compute resources you have.
Note that even if you turn off calculation for one player, it would be during your own thinking time, so it doesn't help that much.
