### ISSUE TITLE
Poor move shown as best move

### ISSUE THREAD

**Issue by raspingbard** [sanderland/katrain#402]
At white move #52 in the attached game record, KaTrain shows the move (in orange) as the "predicted best move".

![Screen 1](https://user-images.githubusercontent.com/28121941/112905417-99d8ea00-90a7-11eb-953d-24321282ac9e.png)

But if I back up and show Top Moves, the actual best move is clearly shown in green.

![Screen 2](https://user-images.githubusercontent.com/28121941/112905498-c12fb700-90a7-11eb-8856-35b929fd7403.png)

Game record:
[KaTrain_Aaron (AaronP) vs Eric 2021-03-28 15 30 42.zip](https://github.com/sanderland/katrain/files/6224807/KaTrain_Aaron.AaronP.vs.Eric.2021-03-28.15.30.42.zip)

**Comment by sanderland** [comment]
Which model and visits settings were used for this? I just get results like this, with a different blue move
![image](https://user-images.githubusercontent.com/48946947/112964386-95184280-9148-11eb-8046-43f9052d71a5.png)

**Comment by raspingbard** [comment]
I'm using model: g170-b40c256x2-s5095420928-d1229425124.bin.gz

I use Full Analysis (max = 5000).  I get different results when I run it multiple times.  It might be due to Wide Root Noise, or some other randomness in the engine.

![image](https://user-images.githubusercontent.com/28121941/113013199-bf620400-9138-11eb-811e-c0fcfeb54cc0.png)

**Comment by sanderland** [comment]
Interesting. Somehow the order field is wrong, but that just comes from katago and should be fine. Is your katago up to date?
For me it corrects instantly on pondering or resetting.
```
{'moves': {'H12': {'move': 'H12', 'order': 1, 'lcb': 0.05441394373077357, 'prior': 0.5964065790176392, 'pv': ['H12', 'G11', 'F11', 'D9', 'F10', 'D8', 'B7', 'C7', 'C6'], 'scoreLead': -28.145096207597764, 'scoreMean': -28.145096207597764, 'scoreSelfplay': -29.407650928244262, 'scoreStdev': 22.622772528808188, 'utility': -1.0783619258469783, 'utilityLcb': -1.003258288388656, 'visits': 458, 'winrate': 0.027591216067087032}, 'F11': {'move': 'F11', 'order': 0, 'lcb': 0.016906762162440248, 'prior': 0.2618260681629181, 'pv': ['F11', 'H12', 'E10', 'Q8', 'Q18', 'G4', 'F7', 'O16'], 'scoreLead': -15.591908212352974, 'scoreMean': -16.30773759822063, 'scoreSelfplay': -17.637482426624068, 'scoreStdev': 19.04371516695949, 'utility': -0.9760648306444775, 'utilityLcb': -1.0138700332045534, 'visits': 819, 'winrate': 0.03182775035451879}, 'J12': {'move': 'J12', 'order': 2, 'lcb': 0.04269708257755367, 'prior': 0.11113511770963669, 'pv': ['J12', 'F11', 'G11', 'D12', 'H12', 'D13', 'R17', 'Q17', 'Q18'],
```
The random differences can also be due to board rotations on the NN input btw.

**Comment by raspingbard** [comment]
I'm using Katago v1.8, the latest.  Today, I can no longer replicate the exact problem, but a similar one (see below).

Each day after I wake my PC and start KaTrain, it takes a real long time to load.  I assume that KataGo is doing some OpenCL retuning, but why it needs to do this at the start of each day, I don't know.  Could this be causing the different results?

Today, the black move #51 has a similar problem.  I don't know what the algorithm is for determining if a move should be blue, the top one.  Perhaps the other moves have low confidence?

![Screen 4](https://user-images.githubusercontent.com/28121941/113035748-ba10b380-9150-11eb-93e9-c17f3f152459.png)

![Screen 3](https://user-images.githubusercontent.com/28121941/113035776-bed56780-9150-11eb-8d80-665fe5cb62fc.png)

**Comment by raspingbard** [comment]
After waking the PC, once the first load of Katrain is done, I can quit and restart KaTrain very quickly.  I'll experiment with starting KataGo just by itself in the next few days.

Attached is a clean sgf of the game.

[2021-03-17 Eric vs Aaron (AaronP).zip](https://github.com/sanderland/katrain/files/6231859/2021-03-17.Eric.vs.Aaron.AaronP.zip)

**Comment by sanderland** [comment]
Anything in the console when you first start it?

Can't reproduce the bug, but this is amazing! a 5 point difference in value...
![image](https://user-images.githubusercontent.com/48946947/113056225-cece6500-91ab-11eb-883a-3e14cb41d324.png)

**Comment by raspingbard** [comment]
By console, I assume you mean DebugKaTrain output?  Here is the output from this morning.  There was about a 30 second pause between the time the console first appeared, and the time that the output started.  Is there something else to check?

[DebugKaTrain 20-03-31.txt](https://github.com/sanderland/katrain/files/6238157/DebugKaTrain.20-03-31.txt)

**Comment by sanderland** [comment]
That is very strange. Aside from running from source with kivy debug flags it's hard to check more.

**Comment by raspingbard** [comment]
For the difference in point values, have we determined if this is a KaTrain or KataGo issue?

**Comment by sanderland** [comment]
> For the difference in point values, have we determined if this is a KaTrain or KataGo issue?

The -2.2 is not an issue, it's simply valuing winrate more than the few points as it's way ahead.

**Comment by sanderland** [comment]
curious if 1.9 is better, but in any case it seems not so much a katrain issue

**Comment by raspingbard** [comment]
Hi Sander,

I reran the analysis on the game in question and the problem seemed to be cured, at least for this game.

Nice job on the new performance report!  It looks very nice, and I’m sure I’ll get much use out of it.

Regards,
-Eric W
