### ISSUE TITLE
Update documentation to mention Homebrew installation method

### ISSUE THREAD

**Issue by apetresc** [sanderland/katrain#408]
I've [just added](https://github.com/Homebrew/homebrew-cask/pull/103355) KaTrain to Homebrew (as a Cask), so installation on macOS is just a matter of:

```bash
brew install katrain
```

The installation docs should be updated to mention this possibility.

**Comment by sanderland** [comment]
this won't work on m1, right? can brew take care of that?

**Comment by sanderland** [comment]
But presumable you already did a `brew install katago` ?
Non-M1 don't need this, while M1 does, that's why I'm asking if it should be a dependency on M1 (assuming brew does those)

**Comment by apetresc** [comment]
Oh interesting, I had to check Activity Monitor to confirm it, but you're right, KaTrain is using the `/opt/homebrew/Cellar/katago/1.8.1/bin/katago` copy (which is compiled for M1); I hadn't expected that to happen because in KaTrain's settings I left the engine path blank which I thought meant it would only use the embedded KataGo. Is there an exception made for specifically M1 Macs?

Let me uninstall it and confirm what happens... is there a reason why x64 KataGo wouldn't work under Rosetta2?

**Comment by sanderland** [comment]
Yeah the blank path has special logic for M1, since the binary doesn't work under rosetta.
It seems that even when the app itself runs under rosetta, the subprocess.open call does not transfer that. Not having a mac of any kind makes this very hard to check.

**Comment by sanderland** [comment]
Lots of discussion in https://github.com/sanderland/katrain/issues/331 as well

**Comment by apetresc** [comment]
Ah interesting. Yeah, just tried it without brew-provided katago and indeed it doesn't work. I will add a `depends_on formula: katago` clause to the Cask.

In your opinion, should I try to scope that dependency to only M1 Macs? Or would it just be better overall to _always_ have it depend on `katago` and let Homebrew manage its upgrades instead of KaTrain?

**Comment by sanderland** [comment]
Hmm, will leave that up to you, would say it depends on the chance of katago failing to compile.
The .app bundle won't easily find the brewed binary on non-m1 macs unless pointed at it, so benefits maybe a bit limited. If the brew uses a source-based approach though, it's definitely needed (the mac binary is built in github actions).

**Comment by apetresc** [comment]
The Homebrew katago formula is indeed from source, but most people's default Homebrew settings is to use the "bottled" version (which are basically precompiled per-arch binaries that are built and cached by the Homebrew project themselves). You can always force it to compile locally with `brew install -s`.

If the .app only attempts to use the brewed binary on M1 Macs, then I'll definitely make it a conditional dependency.

**Comment by sanderland** [comment]
Documentation updated!

**Comment by sanderland** [comment]
1.8.4 released
is there a way to make the update process better, or will it always involve a patch to homebrew?

**Comment by apetresc** [comment]
It does require a new PR to Homebrew. The best way to automate it would be to set up a [Github Action](https://github.com/marketplace/actions/bump-homebrew-formula) to issue the PR. I can prepare a PR for this if you'd like.

**Comment by sanderland** [comment]
Sure! The action linked seems very tag based, rather than release based, so I'm not sure how to apply it. Assistance would be appreciated :)

**Comment by apetresc** [comment]
Well, releases _are_ tags, Github automatically creates the latter when you create the former.

I'll take a crack at it soon! :)
