### ISSUE TITLE
cannot get katrain to run, ubuntu 20.10

### ISSUE THREAD

**Issue by kylebakerio** [sanderland/katrain#409]
Dell G5 5590, Pop OS 20.10, RTX 2070MQ, i7-9750H.

recently had my OS wiped, can't seem to get katrain installed this time. Has never gotten past the initial load I believe. This is what I see in the terminal when running `katrain`:

```sh
$ sudo katrain
Using user config file /root/.katrain/config.json
[CRITICAL] [AudioSDL2   ] Unable to open mixer: b'No such audio device'
[WARNING] [AudioSDL2   ] Unable to load /usr/local/lib/python3.8/dist-packages/katrain/sounds/countdownbeep.wav: b"Audio device hasn't been opened"
[WARNING] [AudioSDL2   ] Unable to load /usr/local/lib/python3.8/dist-packages/katrain/sounds/boing.wav: b"Audio device hasn't been opened"
/usr/local/lib/python3.8/dist-packages/katrain/KataGo/katago: error while loading shared libraries: libzip.so.5: cannot open shared object file: No such file or directory
ERROR: Engine died unexpectedly without sending output, possibly due to out of memory: status 127
ERROR: Engine died unexpectedly without sending output, possibly due to out of memory: status 127
 Exception in thread Thread-1:
 Traceback (most recent call last):
   File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
 Exception in thread Thread-3:
 Traceback (most recent call last):
   File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
     self.run()
   File "/usr/lib/python3.8/threading.py", line 870, in run
     self.run()
   File "/usr/lib/python3.8/threading.py", line 870, in run
     self._target(*self._args, **self._kwargs)
     self._target(*self._args, **self._kwargs)    self._target(*self._args, **self._kwargs)
   File "/usr/local/lib/python3.8/dist-packages/katrain/core/engine.py", line 245, in _analysis_read_thread
   File "/usr/local/lib/python3.8/dist-packages/katrain/core/engine.py", line 314, in _write_stdin_thread
     self.katago_process.stdin.write((json.dumps(query) + "\n").encode())
     self.katago_process.stdin.write((json.dumps(query) + "\n").encode())    self.check_alive(exception_if_dead=True)
 AttributeError: 'NoneType' object has no attribute 'stdin'
   File "/usr/local/lib/python3.8/dist-packages/katrain/core/engine.py", line 198, in check_alive
     raise EngineDiedException(died_msg)
 katrain.core.engine.EngineDiedException: Engine died unexpectedly without sending output, possibly due to out of memory: status 127


```

**Comment by kylebakerio** [comment]
(I have 32gb of ram and 8gb of vram, btw, with 8% vram utilization and 18% ram utilization)

**Comment by sanderland** [comment]
/usr/local/lib/python3.8/dist-packages/katrain/KataGo/katago: error while loading shared libraries: libzip.so.5: cannot open shared object file: No such file or directory

this is the error. get the right libzip package, or compile katago locally.
you can also try general settings->download katago versions and try some other releases, but afaik they also use libzip5

**Comment by kylebakerio** [comment]
that did indeed fix it (`sudo apt install libzip-dev`), but catching instead of dumping errors, and managing dependencies, would be ideal.

Anyways, for anyone else coming from ubuntu 20.10 in the meantime, this is here.

**Comment by sanderland** [comment]
fix how? if i compile with older libzip versions, it fails on up-to-date os'es, it's the general linux pain of .so files

**Comment by kylebakerio** [comment]
I'm a web dev, so I can only speak as a linux user, not developer. But from my limited knowledge:

(1) catch the error and tell the user to install the needed package? (Or perhaps, in the readme, include a list of dependencies the user should install, perhaps with a `sudo apt install x y z` example).
(2) perhaps consider using an alternative to pip
(3) is this really a version issue? It seems like the issue is just that I didn't have the dependency, not that it was the wrong version, no?
(4) change the error handling to make the key error propagate?

Or none of the above and people can just look up here when they hit the issue. It's not a huge deal, obviously, and I'm just super grateful the library exists.

**Comment by sanderland** [comment]
>  catch the error and tell the user to install the needed package?

The error I get is essentially an executable exit code, which happens for a whole bunch of reasons. I might make an overview and open that on the error.

> Or perhaps, in the readme, include a list of dependencies the user should install, perhaps with a sudo apt install x y z example

https://github.com/sanderland/katrain/blob/master/INSTALL.md

**Comment by kylebakerio** [comment]
> > catch the error and tell the user to install the needed package?
> 
> The error I get is essentially an executable exit code, which happens for a whole bunch of reasons. I might make an overview and open that on the error.
> 
> > Or perhaps, in the readme, include a list of dependencies the user should install, perhaps with a sudo apt install x y z example
> 
> https://github.com/sanderland/katrain/blob/master/INSTALL.md

Not sure what you're pointing to in the readme; I guess you might be referring to the procedure to build from source? I'm just saying `pip install katrain` wasn't quite enough, might include an `sudo apt install pkg1 pkg2` step before. Not sure if that makes sense here or not, but it's something I've seen for other packages before.

**Comment by sanderland** [comment]
Yes, the troubleshooting section, but I see `libzip-dev` is actually missing, since it's only been necessary since the whole distributed thing started.
