### ISSUE TITLE
[feature request] in distribute mode,user can browse  back and review certain move and tried different ways.

### ISSUE THREAD

**Issue by xiaoyifang** [sanderland/katrain#412]
as title ,and when user tried different ways ,the main branch can still continue to grow .

the user's move will not upload when game finished.

**Comment by sanderland** [comment]
There is no way to interact with the distributed katago engine, sorry :(

**Comment by xiaoyifang** [comment]
would it be possible to start a new engine to do the  analysis ,while keep
the distribute engine unchanged.

Sander Land ***@***.***> 于2021年4月12日周一 下午10:58写道：

**Comment by sanderland** [comment]
This is possible, but I think too complicated. For now, the idea is just to have people note what games are interesting and look at the saved sgfs later.
