### ISSUE TITLE
sort by last modified in game loading screen

### ISSUE THREAD

**Issue by hunterpp** [sanderland/katrain#413]
Quite difficult to find my sgf files without this feature

**Comment by sanderland** [comment]
Pretty sure it already does?

**Comment by hunterpp** [comment]
<img width="911" alt="Screen Shot 2021-04-18 at 2 00 02 PM" src="https://user-images.githubusercontent.com/772917/115155524-635f1100-a04e-11eb-828a-9d4d3af640af.png">

**Comment by sanderland** [comment]
A screenshot showing nothing?
https://github.com/sanderland/katrain/blob/ce8a6e31e171a400598075adb66954a6a0d20f08/katrain/gui/widgets/filebrowser.py#L60

**Comment by hunterpp** [comment]
Clearly shows “name” and “size” are only options available to sort.

**Comment by sanderland** [comment]
Neither name nor size are options to sort by. They're just things this particular filebrowser widget shows.

**Comment by hunterpp** [comment]
Ok....but I still have to dig through hundreds of items in my downloads folder to find a game...because this is a real bug.

**Comment by sanderland** [comment]
A screenshot of your downloads folder sorted by modified next to the load screen sorting them differently would help, then.

**Comment by sanderland** [comment]
Also you can drag and drop files on the UI, as well as 'open with' if Mac isn't nicely giving the modified time to python.
