### ISSUE TITLE
SSL certificates not being picked up in pre-built mac app?

### ISSUE THREAD

**Issue by h-unterp** [sanderland/katrain#414]
<img width="355" alt="Screen Shot 2021-04-16 at 2 02 01 PM" src="https://user-images.githubusercontent.com/772917/115065650-632f0c00-9ebc-11eb-9bf9-8765c4aa4acb.png">

**Comment by sanderland** [comment]
https://github.com/sanderland/katrain/blob/master/INSTALL.md

**Comment by hunterpp** [comment]
I followed installation instructions. 1.8.4 Both via homebrew and download of dmg same issue still appears. Not sure why this was closed.

**Comment by sanderland** [comment]
If you encounter SSL errors on downloading model files, you may need to follow these instructions to fix your certificates.

**Comment by hunterpp** [comment]
Did this: https://stackoverflow.com/questions/52805115/certificate-verify-failed-unable-to-get-local-issuer-certificate same error. Not sure which version of python katrain is running from

**Comment by sanderland** [comment]
The .app has it's own python installation. pip etc use the system python.

**Comment by sanderland** [comment]
Can confirm this is an issue now that I have my own mac, have escalated it to the kivy team.

**Comment by sanderland** [comment]
Possible fix here
https://github.com/kivy/kivy/issues/7562#issuecomment-1080780638

**Comment by sanderland** [comment]
Please try this build and report back
https://github.com/sanderland/katrain/actions/runs/2058707157

**Comment by sanderland** [comment]
closed as inactive and potentially fixed

**Comment by minarc** [comment]
Using Katrain 1.14, Sonoma 14.5 it happens again.
