### ISSUE TITLE
Initial winrate problem with 6.5 komi re-visited

### ISSUE THREAD

**Issue by dinohsu1019** [sanderland/katrain#416]
Not only lizzie gives 56% for black with 6.5 komi, but also Ah-Q pro, and the katago engine is the same, so I am not sure why katrain gives 51% to 52%, please look into this issue once again, or users are confused. (My settings: remote engine of katago on  Windows 10)

https://github.com/sanderland/katrain/issues/180

katrain: 
![image](https://user-images.githubusercontent.com/30600848/115145230-1c3f4300-a083-11eb-955e-93ee3b95d26c.png)

sabaki: 
![image](https://user-images.githubusercontent.com/30600848/115149655-a5f90b80-a097-11eb-8155-ea47e2689d44.png)

Ah-Q pro: 
![image](https://user-images.githubusercontent.com/30600848/115145288-5e688480-a083-11eb-94c5-a7668b7821ce.png)

**Comment by sanderland** [comment]
What rule set?

**Comment by sanderland** [comment]
Also you are comparing the move value to the root, which may differ a bit

**Comment by dinohsu1019** [comment]
> Also you are comparing the move value to the root, which may differ a bit

Sorry, I have just fixed that one (sabaki's screenshot)

**Comment by dinohsu1019** [comment]
> Also you are comparing the move value to the root, which may differ a bit

Do you mean this page? (Setup New Game / Edit Game Info and Rules -> Start New Game)

![image](https://user-images.githubusercontent.com/30600848/115149712-efe1f180-a097-11eb-9d74-cc843d281b32.png)

**Comment by dinohsu1019** [comment]
> What rule set?

Do you mean this page? 

![image](https://user-images.githubusercontent.com/30600848/115149772-346d8d00-a098-11eb-99eb-a336e587b275.png)

**Comment by sanderland** [comment]
That, or the SGF specified rules, yes.
Chinese: B 55.5% 
Japanese: W 52%
