### ISSUE TITLE
Usability: add support to "open with" from Windows context menus

### ISSUE THREAD

**Issue by popz73** [sanderland/katrain#417]
Today, in Windows we can't right-click an .sgf file and open it with KaTrain.

Even when we select Katrain.exe in the list of applications
![image](https://user-images.githubusercontent.com/12851952/115794772-dfe74c00-a3ce-11eb-9226-d5d5432e786e.png)
Explorer calls the .exe with the file path as parameter, but the application does nothing with it (i.e. app opens, but doesn't load the SGF from where we opened it).
Both adding a Katrain context menu option for .sgf files (like Sabaki/Pandanet in the example above), and/or at least support the 'open with' parameter, would do a world of good in saving several seconds to each human in our hivemind.

Adding a context menu option would be preferable - it would allow people to continue having a simple editor as the default app + still a quick access to opening with KaTrain when needed.

**Comment by sanderland** [comment]
running `katrain /home/sander/Downloads/test.sgf` definitely works, so not sure where open with goes wrong.
Adding a context menu option is done via the registry I think, and is not something I can do without getting into installers/packaging.

**Comment by sanderland** [comment]
have tested and confirmed that open with works...

**Comment by popz73** [comment]
that's weird, here it doesn't (windows 10.0.19042, katrain 1.7.0) - opens katrain, but without loading the game.

**Comment by sanderland** [comment]
Why are you testing an old version?

**Comment by popz73** [comment]
it's just the one I use.. I see that this was added to 1.8 :) closed!
