### ISSUE TITLE
config.json stores incorrect size and position

### ISSUE THREAD

**Issue by popz73** [sanderland/katrain#422]
By default (fresh install, or when deleting config.json), KaTrain starts with a window size that fits the screen, and a crisp font.

If I just close it and re-open, the size becomes way bigger (bigger than the screen height) and the font sizes get bigger/blurry as well.
Here's a video with a demo of the problem:
https://www.youtube.com/watch?v=W0zoVd9E6dc

**Comment by sanderland** [comment]
What if you re-open it a third time? Does it keep growing?

**Comment by popz73** [comment]
No, third/fourth/etc stays at the same size as the second.

**Comment by sanderland** [comment]
what is ```    "ui_state": {
        "size": [
            1300,
            1000
        ],```
in config.json?

**Comment by popz73** [comment]
my resolution is 1920x1080
when opening and closing, the config.json gets saved with
        "size": [
            1274.0,
            980.0
(...)
        "top": 139,
        "left": 369

These seem to match the 'OK' example size - note that at the first time opening, even though the size is ok and the font is crisp, the bottom is already off-screen. That seems to match the 980 + 139 (slightly bigger than 1080).

On the second time opening, when reading these, it is like some kind of multiplier is applied?

**Comment by popz73** [comment]
yep, that's it - with the scaling at 100% the second opening is the same as the first one. Bottom still off-screen, but a reasonable size)
So it's the scaling that causes the second-opening hike

**Comment by sanderland** [comment]
That is still strange.

on startup:
```
        win_size = self.gui.config("ui_state/size", [])
        if not win_size:
            window_scale_fac = 1
            try:
                from screeninfo import get_monitors

                for m in get_monitors():
                    window_scale_fac = min(window_scale_fac, (m.height - 100) / 1000, (m.width - 100) / 1300)
            except Exception as e:
                window_scale_fac = 0.85
            win_size = [1300 * window_scale_fac, 1000 * window_scale_fac]
        Window.size = (win_size[0], win_size[1])
```

on exit:
```
self.gui._config["ui_state"]["size"] = list(Window._size)
```

I can't see why the second time would be particularly different.
Can you try the 1.9 branch with debug level=1 and look for `Setting window size to ..`

**Comment by romulusmare** [comment]
My install (second time it happens) it start painting the window on secondary monitor and it gets stuck before painting anything else but window itself. Odd is I never moved the KaTrain window on second monitor. Not even sure what to do other then reinstall.

**Comment by sanderland** [comment]
> 
> 
> My install (second time it happens) it start painting the window on secondary monitor and it gets stuck before painting anything else but window itself. Odd is I never moved the KaTrain window on second monitor. Not even sure what to do other then reinstall.

does it work ok when deleting <home folder>/.katrain/config.json ?

**Comment by romulusmare** [comment]
I thought it might and tried, but nope. It still opens, paints the window border and gets stuck.

**Comment by sanderland** [comment]
Added an option to turn off window size restoring, hopefully that should help.

**Comment by romulusmare** [comment]
Thank you. How can I try it, pull and build?
