### ISSUE TITLE
AI vs AI game cannot last for long

### ISSUE THREAD

**Issue by strangeryf** [sanderland/katrain#429]
The AI vs AI game in 1.8.4 finishes within 3 to 10 turns, which CPU or GPU utilization from 100% to 0. But in 1.7.2, this kind of game can run until one side wins.

**Comment by sanderland** [comment]
I cannot reproduce this, for me the latest version just plays to the end as it should

**Comment by strangeryf** [comment]
I just found it's because I clicked the "Analysis“ button which caused the game to stop, and then I clicked the "Play" and the game went on.
