### ISSUE TITLE
counting sounds

### ISSUE THREAD

**Issue by sanderland** [sanderland/katrain#43]
OGS sounds appear to not be freeely available.

**Comment by sanderland** [comment]
basic sounds are in 1.1.2, but higher quality ones would help

**Comment by Dontbtme** [comment]
_ For English vocal counting down from 3 to 1 you have a nice female voice with GNU Free Documentation License on wiktionary.
3: https://commons.wikimedia.org/wiki/File:En-us-three.ogg
2: https://commons.wikimedia.org/wiki/File:En-us-two.ogg
https://commons.wikimedia.org/wiki/File:En-us-one.ogg
_ Before that, you could have a ticking clock starting at say 10 or 5 seconds (or whatever the user sets?) before the end. This one is a public domain 20 seconds file: https://commons.wikimedia.org/wiki/File:Alarm_clock_ticking.ogg
_ finally, you could have an alarm for the timeout, like this one, for example :p : https://commons.wikimedia.org/wiki/File:Alarm_-_Diving_-_H8.ogg
