### ISSUE TITLE
Board Sizes?

### ISSUE THREAD

**Issue by MasterJose21** [sanderland/katrain#431]
Hello!
Is it possible to have the AI work with bigger board sizes? Such as 21x21 or 25x25?
Thank you!
M.J.

**Comment by sanderland** [comment]
Yes, the latest 'bigger board size' executable can be downloaded in general settings and supports up to 29x29.
However, AI has not been trained on this, and the latest version is quite old. You can also compile your own katago with any board size limit, but things get weird around 39x39 and SGF breaks above 52x52
