### ISSUE TITLE
GLIBC_2.29 required by embedded Katago engine but not present on Ubuntu 18.04

### ISSUE THREAD

**Issue by jest** [sanderland/katrain#436]
After upgrading KaTrain to >=1.8.0, the following error occurs on startup

```
/mydir/lib/python3.6/site-packages/katrain/KataGo/katago: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /mydir
/lib/python3.6/site-packages/katrain/KataGo/katago)                     
 Exception in thread Thread-1: 
 Traceback (most recent call last):                        
   File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner        
     self.run()                                                                                                                 
   File "/usr/lib/python3.6/threading.py", line 864, in run                                                             
     self._target(*self._args, **self._kwargs)                                                                        
   File "/mydir/lib/python3.6/site-packages/katrain/core/engine.py", line 245, in _analysis_read_thread
     self.check_alive(exception_if_dead=True)                                                                                     
   File "/mydir/lib/python3.6/site-packages/katrain/core/engine.py", line 198, in check_alive                                                  
     raise EngineDiedException(died_msg)                                                                                                                        
 katrain.core.engine.EngineDiedException: Engine died unexpectedly without sending output, possibly due to out of memory: status 1
```

Version 1.7.6 works fine.

I see a similar (fixed) issue from some time ago, #170 , probably related.

**Comment by sanderland** [comment]
do the official versions work?

**Comment by jest** [comment]
Yes. 1.8.2 starts OK. Also, just looking for the symbol in binaries:

```
strings ./katago | grep ^GLIBC | sort
```

shows for official 1.8.2:

```
GLIBC_2.14
GLIBC_2.15
GLIBC_2.23
GLIBC_2.2.5
GLIBC_2.27
GLIBC_2.3
GLIBC_2.3.2
GLIBC_2.3.4
GLIBC_2.4
GLIBC_2.6
GLIBCXX_3.4
GLIBCXX_3.4.11
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_3.4.20
GLIBCXX_3.4.21
GLIBCXX_3.4.22
GLIBCXX_3.4.9
```

and for KaTrain's embedded:

```
GLIBC_2.14
GLIBC_2.15
GLIBC_2.23
GLIBC_2.2.5
GLIBC_2.27
GLIBC_2.29
GLIBC_2.3
GLIBC_2.3.2
GLIBC_2.3.4
GLIBC_2.4
GLIBC_2.6
GLIBCXX_3.4
GLIBCXX_3.4.11
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_3.4.20
GLIBCXX_3.4.21
GLIBCXX_3.4.22
GLIBCXX_3.4.26
GLIBCXX_3.4.9
```

So the official requires Glibc 2.27 (the same as Ubuntu 18.04), while KaTrain's needs 2.29. Note that also stdc++ is possibly a problem, as Ubuntu 18.04 has 3.4.25, and KaTrain requires 3.4.26.

**Comment by sanderland** [comment]
I see. I'll stick to using the official ones in the future then (with strip to make it smaller) -- the reasons for distributing my own have largely disappeared with the start of the option to contribute to the distributed runs.

**Comment by jest** [comment]
Thank you.

As a workaround, can I now safely specify `Path to KataGo executable` and everything will work as if I were using the embedded binary? I.e. all configs, models, arguments will be passed the same?

**Comment by sanderland** [comment]
> Thank you.
> 
> As a workaround, can I now safely specify `Path to KataGo executable` and everything will work as if I were using the embedded binary? I.e. all configs, models, arguments will be passed the same?

Indeed, this should work just fine.

**Comment by jest** [comment]
@sanderland This situation happened again in Katrain 1.10.1.

The version of `katago` distributed with Katrain has linking problems mentioned in this issue (`GLIBC_2.29` and `GLIBCXX_3.4.26`), whereas official Katago 1.10 does not (works correctly on Ubuntu 18.04).

It is a bit surprising when reading in Katrain's release notes:

> KataGo was upgraded to 1.10.0.
> 
> * The linux executable now includes a self-compiled, statically linked libzip, which should reduce issues with versioning.

and the `katago` is certainly *not* statically compiled:

```
$ ldd path/to/katrain/lib/python3.6/site-packages/katrain/KataGo/katago
path/to/katrain/lib/python3.6/site-packages/katrain/KataGo/katago: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by path/to/katrain/lib/python3.6/site-packages/katrain/KataGo/katago)
path/to/katrain/lib/python3.6/site-packages/katrain/KataGo/katago: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by path/to/katrain/lib/python3.6/site-packages/katrain/KataGo/katago)
	linux-vdso.so.1 (0x00007ffcacdc9000)
	libOpenCL.so.1 => /usr/lib/x86_64-linux-gnu/libOpenCL.so.1 (0x00007f778ff11000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f778fcf4000)
	libssl.so.1.1 => /usr/lib/x86_64-linux-gnu/libssl.so.1.1 (0x00007f778fa67000)
	libcrypto.so.1.1 => /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1 (0x00007f778f59c000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f778f37d000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f778eff4000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f778ec56000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f778ea3e000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f778e64d000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f778e449000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f77905c6000)
```

I am aware of #469, but I assume that currently the distributed version is a custom build, and when the `libzip` problem is solved in katrain's official releases, that binary will be used?

Sorry to be so troublesome with mine old 18.04, but if it is the platform you consider not important to contribute anymore (which is fair) maybe updating README/release notes would suffice to not to surprise users like me?

**Comment by sanderland** [comment]
It is statically linked to libzip in particular, not all libraries.
In general, KataGo's developer seems of the opinion that the libzip versioning conflict is not a problem as such, as people can just compile their own, so I don't expect it to change on that end.

I will update https://github.com/sanderland/katrain/blob/master/ENGINE.md in the next release to recommend compiling your own or trying the official binaries for older linux versions.

If you want to have a go at creating a shell script/Dockerfile which gives a binary with maximal compatibility that would be great, but it seems a game of whack-a-mole.

**Comment by jest** [comment]
If you consider it valuable, I'll be glad to help.

I'm pretty convenient with Docker, so can try to work out some binary; however, I have less experience with compiling OpenCL programs, so if you could share somehow your script that produces the distributed binary `katago`, it would be a helpful starter.

**Comment by sanderland** [comment]
https://github.com/sanderland/KataGo/blob/minikata/Dockerfile has my old dockerfile.

https://github.com/lightvector/KataGo/pull/564 has my compile command for libzip and modification of the CMakefile.

Unfortunately this does not result in a valid distributed binary due to the hash checking, but gets you close. I compiled the currnent binary just locally on my machine and fixed the hash check by making sure my git status was clean between running 'cmake' and 'make'.
