### ISSUE TITLE
Feature requests: More simultanous variation info and mouse wheel hovered variations

### ISSUE THREAD

**Issue by barrtgt** [sanderland/katrain#438]
It would be nice to have an option to display the move visits, score, and winrate all at once. Also if you could make an option to make Katrain allow you to use the mouse wheel to go through the searched variation for the move under the cursor instead of the timed one currently used, and go to the next move in the tree when the cursor isn't over searched moves, that would be pretty cool.

**Comment by sanderland** [comment]
The scroll wheel is an interesting idea that shouldn't be too hard.
More info on a move gets quite tricky with layout logic, although someone else is welcome to contribute this if they are willing to do this fiddly task.

**Comment by sanderland** [comment]
implemented in #442 and merged into 1.9
