### ISSUE TITLE
Error downloading katago

### ISSUE THREAD

**Issue by d7urban** [sanderland/katrain#439]
Clicked "Download KataGo Versions" without changing the dropdown first. 
Got a "Downloading Eigen AVX2 (Modern CPUs) v1,8,1; Error: unknown encoding: idna
It did update from 4 available katago versions to 6, so the other versions downloaded fine.
Clicking Download again updated it to 7, now including the AVX2 version.

Could have been some transient network error?

**Comment by sanderland** [comment]
Sounds just transitional then, indeed
