### ISSUE TITLE
The katrain did not work with extend display

### ISSUE THREAD

**Issue by chucklu** [sanderland/katrain#443]
I have a laptop, and a extend screen.
Currently I set the extend screen as the main display(display 1), and move the katrain to show on laptop(display 2), it's fine.

But when I disconnect the extend screen, the katrain is not able to show on laptop(the main display). It seems the katrain take the laptop as the main display, and try to show on another screen(another display). As I only have one screen this time, the katrain just not show.
It's weird, as other software work fine on my laptop with the extend display. When the extend screen disconnect, they will show on laptop directly.

**Comment by sanderland** [comment]
Please file at http://github.com/kivy/kivy showing screenshots of what is going wrong. Likely it will be some SDL2 issue with no particular place report it though, as often the case with display issues. 
Not much I can do about, sorry!

**Comment by chucklu** [comment]
@sanderland   I am not sure what's the version of kivy, could you help to provide the information? Then I will file an issue on kivy repository. The following info was required by the issue template of kivy.
**Software Versions**
* Python:
* OS:
* Kivy:
* Kivy installation method:

**Comment by chucklu** [comment]
@sanderland  I just filed an issue here https://github.com/kivy/kivy/issues/7584, could you please add the kivy version, and paste the python code you write there?
