### ISSUE TITLE
why kivy model import erro, how use your python version?

### ISSUE THREAD

**Issue by zhouqiw** [sanderland/katrain#446]
![image](https://user-images.githubusercontent.com/22001638/123550404-dea41800-d79f-11eb-97f0-1645842851be.png)

**Comment by sanderland** [comment]
The exe releases should just work. But if you want to run from source, I recommend making a clean environment with conda or whatever you use, then install requirements.txt and then start katrain.

**Comment by sanderland** [comment]
closing due to lack of response.
