### ISSUE TITLE
Katrain crashes

### ISSUE THREAD

**Issue by comiluv** [sanderland/katrain#448]
1. Environment
OS Version: Windows 10 20H2
Katrain version: 1.9.1
Graphics card: NVidia RTX 3090
Graphics card driver: 471.11

2. Description
Katrain crashes randomly.
When crashing, the monitor always turns black entirely and comes back after a second with KaTrain app just disappeared without providing any more useful information

3. Steps to reproduce
Can not reproduce crashes reliably
It may or may not happen while user is doing something below:
- Starting the app (i.e. double clicking on katrain.exe)
- Resizing window
- Providing a keyboard input with alt key, q key, etc.
- Clicking on a menu item

4. Additional info
Would like to know how to post a log file or any kind of console message as KaTrain isn't providing any information when it crashes

**Comment by sanderland** [comment]
Try the DebugKaTrain.exe inside the .zip version, with general settings/F8->debug settings=1 or =2

**Comment by comiluv** [comment]
Tried running DebugKaTrain.exe with debug settings=1, but the console also disappears after the whole screen turns completely black when the program crashes, not giving any information

**Comment by sanderland** [comment]
You could run it in the command line (run->cmd), redirecting output with `DebugKaTrain.exe > out.txt`

**Comment by comiluv** [comment]
This time crash happened while I was alt tabbing between web browser and KaTrain's window.
Here is the text file produced by ```DebugKaTrain.exe > out.txt```
[debuglog.zip](https://github.com/sanderland/katrain/files/6728695/debuglog.zip)
Also I monitored my graphics card temperature because I thought it could be related to GPU overheating or something like that, but the temperature remained stable ~50 degrees Celsius

**Comment by sanderland** [comment]
Is this some kind of ultra high visits selfplay?
Can you check RAM usage?

**Comment by comiluv** [comment]
1. I was trying out teaching game mode against ScoreLoss strategy
Specifically game setup was as follows:
- Teaching game mode, player black
- Against ScoreLoss strategy
- Analysis Options: Toggle continuous analysis on
- Continuously moved back and forth between Play screen and Analysis screen
- Next Moves, Show Dots and Top Moves checked on in Play screen
- Next Moves, Show Dots, Top Moves and Expected territory checked in Analysis screen

2. My system RAM usage while idling sits at 10.7/63.9GB and VRAM is at 0.5/24GB
My VRAM usage since system boot time is 2% at maximum as shown in a screenshot from CPUID HWMonitor below:
<img width="824" alt="2021-06-29 042853" src="https://user-images.githubusercontent.com/19642705/123693167-afba9e80-d892-11eb-8758-cf61f0101a9f.png">

3. Also after experiencing the first crash which took some time, about 30 minutes, simply running ```DebugKaTrain.exe > out.txt``` results in crashes as early as right after running the program, resulting in an empty log file out.txt

4. Crash described in 3 happened while dragging the window, resizing the window, browsing through menu items, etc. without necessarily running KataGo engine.

**Comment by sanderland** [comment]
This is very strange, and unlike anything I've seen. There is no error in the log that indicates a crash, which suggests something extremely violent is happening to the program.
One more thing you could try is running from source, getting python/anaconda installed and running like that.

**Comment by comiluv** [comment]
I'm afraid I'm not at all an expert in Python or Anaconda.
I tried installing a copy of Python 3.9 and even did pip install -U katrain but gave me error message below when I tried to run katrain.exe from python/scripts/katrain.exe
```
[ERROR  ] [Clock       ] Unable to import kivy._clock. Have you perhaps forgotten to compile kivy? Kivy contains Cython code which needs to be compiled. A missing kivy._clock often indicates the Cython code has not been compiled. Please follow the installation instructions and make sure to compile Kivy
 Traceback (most recent call last):
   File "c:\python39\lib\runpy.py", line 197, in _run_module_as_main
     return _run_code(code, main_globals, None,
   File "c:\python39\lib\runpy.py", line 87, in _run_code
     exec(code, run_globals)
   File "C:\Python39\Scripts\katrain.exe\__main__.py", line 4, in <module>
   File "c:\python39\lib\site-packages\katrain\__main__.py", line 36, in <module>
     from kivy.base import ExceptionHandler, ExceptionManager
   File "c:\python39\lib\site-packages\kivy\base.py", line 28, in <module>
     from kivy.clock import Clock
   File "c:\python39\lib\site-packages\kivy\clock.py", line 466, in <module>
     from kivy._clock import CyClockBase, ClockEvent, FreeClockEvent, \
 ModuleNotFoundError: No module named 'kivy._clock'
```

**Comment by sanderland** [comment]
Kivy can be a pain.

Things to try:
Download the source (github main page, download zip file, extract)

* `pip install -r requirements.txt` in the source folder.
* `python -m katrain` in the source folder

**Comment by comiluv** [comment]
I successfully ran KaTrain by ```python -m katrain``` and it crashed producing below crash log while I was trying another game against KataGO
```
 Traceback (most recent call last):
   File "C:\Dev\katrain-master\katrain\core\engine.py", line 266, in _analysis_read_thread
     analysis = json.loads(line)
   File "C:\Python39\lib\json\__init__.py", line 346, in loads
     return _default_decoder.decode(s)
   File "C:\Python39\lib\json\decoder.py", line 337, in decode
     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
   File "C:\Python39\lib\json\decoder.py", line 353, in raw_decode
     obj, end = self.scan_once(s, idx)
 json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 906064 (char 906063)
```

**Comment by sanderland** [comment]
That should have a line above it, and never crash (just print the exception and continue)

**Comment by comiluv** [comment]
There were some logs in the console, but those looked like usual KataGo move logs IIRC.
To more precisely describe the crash, KaTrain window ran from python source code did not just disappear like previous crashes but became unresponsive with circle mouse cursor thing going on for about a minute with that traceback message above.

I'll update more crashes when I have some free time in weekends

**Comment by chucklu** [comment]
There is a new release for KataGo https://github.com/lightvector/KataGo/releases/tag/v1.9.1

> Fixed bug where analysis engine would crash if a query was terminated before the query began analyzing.

**Comment by chucklu** [comment]
> Katrain 1.9.2: Upgrade to KataGo 1.9.1, preventing crashes of the engine.

Just find 1.9.2 version of Katrain used KataGo 1.9.1

**Comment by comiluv** [comment]
Can't reproduce after updating KataGo to 1.9.1
