### ISSUE TITLE
Add support for quiting!

### ISSUE THREAD

**Issue by julianandrews** [sanderland/katrain#449]
Unless I'm missing something obvious, KaTrain doesn't provide any mechanism to quit.

This is fine if you're working with a window manager that adds a 'close' button to every window, but for users of tiling window managers this is pretty obnoxious! Right now, to quit the application I either have to launch KaTrain from a terminal and use Ctrl+c, or open a terminal to kill it directly using `kill` or `killall`.

Ideally the menu would have a quit option somewhere, but I recognize that most users probably don't really need it. I'd be happy even just with a keyboard shortcut to quit! I would vote for Ctrl+q since that's pretty standard across a wide range of platforms and programs, but anything would be good by me!

**Comment by julianandrews** [comment]
Ohh, and to be clear, I'd much rather have a keyboard shortcut than a menu entry (even if I'd vote for both). I think that's probably the case for most tiling window manager users (and I'm guessing we make up the largest group of people seriously affected by this).

**Comment by sanderland** [comment]
I think you may be the first person I've ever met who uses a window manager without a close button and without a default quit shortcut. Alt+F4 doesn't exist?

**Comment by julianandrews** [comment]
Nope! Alt+F4 works for a lot of programs, but only the ones that implement that. It seems to be pretty standard for programs to respond to either ctrl+q or alt+f4 (though I think of alt+f4 as being a windows specific binding). If either of those worked I'd have found it without documentation. KaTrain is the only program I've run into that doesn't provide a keyboard shortcut to exit.

This is likely to affect pretty much anyone using a Tiling Window Manager (like i3 or xmonad). Looking around a little more, I *do* have a keybinding that kills the focused window (mod+shift+c). I set it up years ago, never had to use it, and had forgotten it exists.

So it's not a critical issue, but it seems to be pretty standard for apps to provide quit options - this is literally the only app I've used in 5 years that didn't have one!

**Comment by sanderland** [comment]
Well when I press Alt+F4 it quits, and nicely so. And command-q on mac quits. And I'm pretty sure Alt+F4 on Ubuntu does as well. All properly trigggering the stop mechanism in a way that properly shuts down the engine. I don't really want to be racing with this handling or having it fire twice. Given that you also have a quit shortcut, I'll call this wontfix.

**Comment by julianandrews** [comment]
> I don't really want to be racing with this handling or having it fire twice.

This shouldn't be a problem. As a rule window-manager level keybindings never get to the app. I'd also note that there's currently nothing preventing multiple close events from being sent, though since the Kivy event handler is single threaded, it seems unlikely to be a problem in any scenario.

I'm also a little curious - are you sure command-q works on MacOS for KaTrain? I was looking through the source code, and Kivy seems to handle it explicitly [here](https://github.com/kivy/kivy/blob/master/kivy/core/window/__init__.py#L1752), but then in your `on_request_close` you ignore keyboard requests.

Assuming that the Kivy code for command-q does anything at all there must be users for whom command-q is broken in KaTrain. That feels like an accessibility problem to me!

**Comment by sanderland** [comment]
Yes, command-q works fine. I don't think the kivy code is needed. Their mac support isn't great anyway since none of the current devs appear to have macs.
