### ISSUE TITLE
Question with "set region of interest"

### ISSUE THREAD

**Issue by Quantummmmm** [sanderland/katrain#451]
I like Katrain very much, which is elegantly built and very helpful for improving Go skills. I just have one question: In the "Analysis Options", if I choose  "set region of interest", I can draw a region on the board, but how to remove that region after analysis? I did not find any way to do that, although other analysis options can still be used with that region remained. Thanks.

**Comment by sanderland** [comment]
Just select an empty region by set region->click anywhere.

**Comment by milescrawford** [comment]
This could definitely be made more clear in the UI or documentation.
Perhaps the "set region of interest" menu item/hotkey could become a "clear region of interest" button while one is set?
