### ISSUE TITLE
The KaTrain.exe file without file version

### ISSUE THREAD

**Issue by chucklu** [sanderland/katrain#452]
The file version and production version are both empty.
![image](https://user-images.githubusercontent.com/3004057/124240617-7d889580-db4d-11eb-9072-d97c0d993b85.png)

**Comment by chucklu** [comment]
The zip file for download would be better with a version number.
You might check the release page of another software https://github.com/HearthSim/Hearthstone-Deck-Tracker/releases
The zip file is Hearthstone.Deck.Tracker-v1.14.25.zip
It would be clear if I keep multi version of zip file on local disk

**Comment by chucklu** [comment]
I download the KaTrainWindows.zip from https://github.com/sanderland/katrain/releases/tag/1.9.2.
But when I open KaTrain.exe, the title of software still showed as v1.9.1

**Comment by sanderland** [comment]
fixed on 1.9.2, but pyinstaller does not give an easy way to fill the fields, so won't-do on the former
