### ISSUE TITLE
Proxy setting 

### ISSUE THREAD

**Issue by chucklu** [sanderland/katrain#453]
I am trying to download the models, but got the failed error. 
I would like to configure a proxy for katrain to use, but did not find the option to configure the proxy.
![image](https://user-images.githubusercontent.com/3004057/124248092-140c8500-db55-11eb-9cc5-4b8ec4d26842.png)

**Comment by sanderland** [comment]
there is not, a pr would be welcome

**Comment by sanderland** [comment]
Closed due to clear lack of interest
