### ISSUE TITLE
Multiple AI setting

### ISSUE THREAD

**Issue by chucklu** [sanderland/katrain#454]
Is it possible to support multi AI configuration like sabaki?
When start a new game, I can choose different ai(network weights) for black an white.
![image](https://user-images.githubusercontent.com/3004057/124261082-f8a87680-db62-11eb-81de-da4ab8ce4d20.png)
![image](https://user-images.githubusercontent.com/3004057/124261145-0958ec80-db63-11eb-9901-407e8cb24ec4.png)

**Comment by chucklu** [comment]
Currently, we can only choose AI and Human for black and white.  It would be better, if we can have multi AI choices here.
![image](https://user-images.githubusercontent.com/3004057/124261445-62c11b80-db63-11eb-903a-a4c4dc337be9.png)

**Comment by sanderland** [comment]
It is kind of available in the code, but I considered the benefit of this in the GUI to be too small for the additional complexity, sorry.
