### ISSUE TITLE
Feature Suggestion -- Export Performance Report

### ISSUE THREAD

**Issue by simonguoxm** [sanderland/katrain#456]
"Performance Report" is a great feature.

If we can export this report (for example, a csv file) , then I can save it. Then I can compare my performance at different times and show my improvement. 

Of course I can do it by hand, but it's convenient to export data directly.

**Comment by sanderland** [comment]
I think that will give more confusion than anything, such comparison are hard.
https://github.com/sanderland/katrain/blob/master/test_report.py has code that sort of accidentally ended up in the repo and shows running performance stats on collections of sgf.
