### ISSUE TITLE
Installation instructions for Mac using brew does not work

### ISSUE THREAD

**Issue by benjaminpjones** [sanderland/katrain#457]
I get a 404 error

```
$ brew install katrain
==> Downloading https://github.com/sanderland/katrain/releases/download/1.9.2/Ka
##O#- #                                                                       
curl: (22) The requested URL returned error: 404 
Error: Download failed on Cask 'katrain' with message: Download failed: https://github.com/sanderland/katrain/releases/download/1.9.2/KaTrainOSX.dmg
```

**Comment by sanderland** [comment]
@apetresc oops I broke a thing (1.9.3)

**Comment by apetresc** [comment]
PR should be merged shortly: https://github.com/Homebrew/homebrew-cask/pull/108179

**Comment by benjaminpjones** [comment]
Thanks! I ended up using pip to download and got to try it out. Great application!

**Comment by apetresc** [comment]
1.9.3 updated on Homebrew, and manual testing seems to indicate it works. I think the issue can be closed now.

**Comment by benjaminpjones** [comment]
>🍺  katrain was successfully installed!

Thanks for the fix!
