### ISSUE TITLE
solve Life_and_death problem

### ISSUE THREAD

**Issue by chucklu** [sanderland/katrain#459]
I would like to solve the problem,
https://www.101weiqi.com/4K/238435/

How could I put all the black stones directly, without switch between black and white? Then put all white stones directly.
Then I can set the black stone move first

**Comment by sanderland** [comment]
For basic questions on use, please use discord as there's more people able to help.
You can not do placements at this time, but if you have the problem as an sgf you can just load it.

**Comment by chucklu** [comment]
> You can not do placements at this time, but if you have the problem as an sgf you can just load it.

Thanks, I will try to record the life and death problem to a sgf file by another go GUI. And then load it by katrain.


By the wat, is it possible that we can use  [gitter](https://gitter.im/dotnet/mlnet) as the communication tool? 
As the discord is [not available](https://en.wikipedia.org/wiki/List_of_websites_blocked_in_mainland_China) in mainland China.

Anyway, I will try to access the discord via a proxy.
