### ISSUE TITLE
Option to disable the new variation scrolling feature

### ISSUE THREAD

**Issue by Cadspen** [sanderland/katrain#461]
I actually find this new feature to be really obtrusive when I'm using the scroll wheel to move through the tree and placing stones on the board.  It would be nice if there was a way to disable this feature or a way to make some other keybind move through AI variations.

**Comment by sanderland** [comment]
could you elaborate?

**Comment by Cadspen** [comment]
In the latest version it was made so you can use the scroll wheel to move through AI variations, right? So, I'll be scrolling through the game tree with my mouse hovering over the board then happen to hover over one of the AI moves and start scrolling through the AI variation when I'm expecting to continue through the main tree.  

It could also be an idea to make it so ctrl+scroll wheel moves through the AI variation you're hovering over instead?

**Comment by sanderland** [comment]
I see, I guess I don't hold my mouse over the board when scrolling, or use the arrow keys. Not sure what the best way is, I would like to avoid additional checkboxes or modifiers.
@xiaoyifang thoughts?

**Comment by raspingbard** [comment]
I mainly use the arrow keys for navigating the tree and the "b" key for backing up a variation.  I also use the scroll wheel to move through the AI variations.

What if you enable tree scrolling only when the mouse is outside the board and enable variation scrolling when inside the board?

**Comment by sanderland** [comment]
> I mainly use the arrow keys for navigating the tree and the "b" key for backing up a variation. I also use the scroll wheel to move through the AI variations.
> 
> What if you enable tree scrolling only when the mouse is outside the board and enable variation scrolling when inside the board?

That's something to try, thanks for the suggestion!

**Comment by sanderland** [comment]
Give 0b5bd10 a spin. There's a bit of an edge case on scrolling in the notes/info, but I think this works.
