### ISSUE TITLE
Calibrated Rank Adjustment

### ISSUE THREAD

**Issue by ghost** [sanderland/katrain#462]
As far as I know, the calibrated rank KataGo is based on OGS ranks. A few months ago, OGS adjusted their ranking system, as per the post below.

https://forums.online-go.com/t/2021-rating-and-rank-adjustments/33389

The conversion of old to new ranks is described on this page.

https://forums.online-go.com/t/new-ranks-vs-old-ranks-who-got-what/33822

The old ranks are affected by a volatility bug, and the new ones are much more accurate. Will the calibrated rank KataGo bots be adjusted to fit the new OGS ranks?

**Comment by sanderland** [comment]
probably not without some wholesale recalibration of everything, which may not happen as it's a lot of work.
i consider changing what the ranks mean between versions not worth it for the potential confusion of users who e.g. may not ever have heard of OGS
