### ISSUE TITLE
Is it possible to support custom game rules?

### ISSUE THREAD

**Issue by Jacky-Lin-9487** [sanderland/katrain#465]
Katrain only has a few mandatory rules: chinese, japanese, korean, AGA, Tromp-Taylor, New Zealand, ancient China.

Is it possible to allow users to customize rules?
For example, add chinese-nopass rule, friendlyPassOk is false.
In other words, add chinese-nothreeko rule and set koRule to POSITIONAL.
Or in other words, add the Ing SST rule so that my SGF can identify it smoothly (allowing suicide).

If it is not possible to add custom rules, can I directly use the rules of the cfg file instead of letting Katrain enforce the control rules?

**Comment by sanderland** [comment]
I think there's some limited support for this through the contribute feature, which saves the ruleset as RU[json], but I've not tested how far this goes. Give it a try maybe.
