### ISSUE TITLE
Extract data from KaTrain

### ISSUE THREAD

**Issue by JeremyDeh** [sanderland/katrain#467]
Hi,
Sorry to fill an issue note, for this is more of a question,
Is there a way to extract data analyzed by Katrain (txt, csv, json, or any format)? or make an interraction between Python and Katrain?

I would like to access the "This move was ranked 'x'th " datas, for all the moves, (so not in the interface as it would take forever to write down all the move's ranks one by one

Thank you

**Comment by sanderland** [comment]
You can just include the files and use them, example: https://github.com/sanderland/katrain/blob/master/test_report.py
