### ISSUE TITLE
test_report.py should not reference absolute path to kata weights

### ISSUE THREAD

**Issue by fbergmann** [sanderland/katrain#468]
in line 20 the absolute path is given to the weight: 

https://github.com/sanderland/katrain/blob/master/test_report.py#L20

ideally this would be a parameter to the script. Or if not found the script should just download the corresponding weights from katagotraining.org

**Comment by sanderland** [comment]
Hoi Frank,
This script was committed by accident from personal testing. It's left there in case it's useful, but similar tot the katrain-bots repo is not meant for muggles.
