### ISSUE TITLE
enhancement: Flexible komi value

### ISSUE THREAD

**Issue by peepo** [sanderland/katrain#470]
Please could you arrange for New game/Komi to be text editable, with appropriate backend?

in particular it seems GoQuest 9x9 uses komi = 7

in expectation that this effects the way katago predicts moves?

thanks

https://tanase.github.io/questhelp/android_help_go9.html

**Comment by sanderland** [comment]
It is

**Comment by peepo** [comment]
arghh, requires double click on this box!

tx

**Comment by peepo** [comment]
perhaps morph to single click request?

maybe I'm just slow...

**Comment by psygo** [comment]
It could be a bit more intuitive where that option is though. I think splitting <kbd>New Game</kbd> and <kbd>Edit Game Info</kbd> into separate menu items makes much more sense.
