### ISSUE TITLE
android version / katago compiling

### ISSUE THREAD

**Issue by Fly143** [sanderland/katrain#472]
Would katrain consider releasing an Android version?Katrain features I like, I hope Android can also have.

**Comment by sanderland** [comment]
Compiling katago for android is the hardest part, the available versions with analysis engine are quite old. If you want to look into ndk compiling that'd be a big help here.

**Comment by Fly143** [comment]
> Compiling katago for android is the hardest part, the available versions with analysis engine are quite old. If you want to look into ndk compiling that'd be a big help here.

AlthoughI would like to help with this, I am not a relevant person and do not know the relevant knowledge. But I know that the author of badukaai has compiled the relevant data. Maybe you can try to communicate with him, but I don't know if he will be willing to provide it.

https://github.com/aki65/aki65.github.io
@sanderland

**Comment by Fly143** [comment]
I know part of the situation. It seems that you have communicated with him before, but he is not willing to provide it. I got a compiled copy of katago engine 1.9.1 from someone else. I took out his[.so] file. The author says it can be used directly.
[arm64-v8a.zip](https://github.com/sanderland/katrain/files/7109127/arm64-v8a.zip)
[armeabi-v7a.zip](https://github.com/sanderland/katrain/files/7109128/armeabi-v7a.zip)

**Comment by Fly143** [comment]
He wanted me to ask.He wanted me to ask if he could use katrain's UI? Because his UI is not very beautiful.

**Comment by Fly143** [comment]
He wanted me to ask.He wanted me to ask if he could use katrain's UI? Because his UI is not very beautiful.

**Comment by sanderland** [comment]
> 
> 
> I know part of the situation. It seems that you have communicated with him before, but he is not willing to provide it. I got a compiled copy of katago engine 1.9.1 from someone else. I took out his[.so] file. The author says it can be used directly.
> [arm64-v8a.zip](https://github.com/sanderland/katrain/files/7109127/arm64-v8a.zip)
> [armeabi-v7a.zip](https://github.com/sanderland/katrain/files/7109128/armeabi-v7a.zip)

Is this from aki65 or someone else? I think the former are without the analysis engine.

**Comment by Fly143** [comment]
> > I know part of the situation. It seems that you have communicated with him before, but he is not willing to provide it. I got a compiled copy of katago engine 1.9.1 from someone else. I took out his[.so] file. The author says it can be used directly.
> > [arm64-v8a.zip](https://github.com/sanderland/katrain/files/7109127/arm64-v8a.zip)
> > [armeabi-v7a.zip](https://github.com/sanderland/katrain/files/7109128/armeabi-v7a.zip)
> 
> Is this from aki65 or someone else? I think the former are without the analysis engine.

This belongs to someone else, a friend of mine.

**Comment by Fly143** [comment]
Doesn't belong to aki65.

**Comment by Fly143** [comment]
This is an important piece of information. Just now, my friend told me that his version of katago engei 1.9.1 can only load weights like aki65. Cannot load normal weights.

**Comment by sanderland** [comment]
> This is an important piece of information. Just now, my friend told me that his version of katago engei 1.9.1 can only load weights like aki65. Cannot load normal weights.

That is certainly remarkable. They independently made the same modifications to the engine? Can they come here and comment?

**Comment by Fly143** [comment]
> > This is an important piece of information. Just now, my friend told me that his version of katago engei 1.9.1 can only load weights like aki65. Cannot load normal weights.
> 
> That is certainly remarkable. They independently made the same modifications to the engine? Can they come here and comment?

I already told him, and he said he would send you a private message at discord later. Please watch your chat list.

**Comment by joseki3691** [comment]
> > This is an important piece of information. Just now, my friend told me that his version of katago engei 1.9.1 can only load weights like aki65. Cannot load normal weights.
> 
> That is certainly remarkable. They independently made the same modifications to the engine? Can they come here and comment?

@sanderland Hi Sander, would you like to discuss it on discord? I've sent you a PM :)

**Comment by sanderland** [comment]
Just an update on this. Between buildozer being a bit outdated and android studio being not easy to work with (hard crashes and emulators not starting), I've not managed to get it working yet.

**Comment by Fly143** [comment]
Is there any new progress now?

**Comment by sanderland** [comment]
> Is there any new progress now?

I never got a reply from anyone here, or on discord, to the model issue.

**Comment by Fly143** [comment]
> 

This is not good news.I'd love to help you too, but I don't have any knowledge of this at all

**Comment by Fly143** [comment]
Are there any new developments now? Is the research still ongoing?

**Comment by sanderland** [comment]
No, the probability of this ever happening is very low.
