### ISSUE TITLE
Questions about using this software to study the life and death problems of Go

### ISSUE THREAD

**Issue by jiangshuichongpei** [sanderland/katrain#476]
Hello, I am a user from mainland China. When using this software, I tried to use the "select part (**shortcut key g**)" function to help me answer the **life and death questions** of Go, but the box selection seems to have no effect, there are still many  The selected point is outside the box, is there any solution?

**Comment by jiangshuichongpei** [comment]
https://www.101weiqi.com/
我摘录死活题的网站

**Comment by sanderland** [comment]
As answered on youtube, there is a low-visit whole board evaluation done anyway, which is not a problem and takes <0.1 second
