### ISSUE TITLE
ERROR: Engine died unexpectedly without sending output:  status 127

### ISSUE THREAD

**Issue by philbat** [sanderland/katrain#479]
Hello,
I just downloaded KaTrain v 1.9.3 on a debian bookworm:
pip3 install -U katrain.
I get:
Starting KataGo with ['/home/phil/.local/lib/python3.9/site-packages/katrain/KataGo/katago', 'analysis', '-model', '/home/phil/.local/lib/python3.9/site-packages/katrain/models/g170e-b15c192-s1672170752-d466197061.bin.gz', '-config', '/home/phil/.local/lib/python3.9/site-packages/katrain/KataGo/analysis_config.cfg', '-analysis-threads', '12', '-override-config', 'homeDataDir=/home/phil/.katrain']
ERROR: Engine died unexpectedly without sending output:  status 127

thanks for your attention

**Comment by philbat** [comment]
Thanks for your answer!
Yes I checked ENGINE.md:
root@debian:~# apt install libzip-dev
...
libzip-dev  version (1.7.3-1).


root@debian:~# sudo apt-get install python3-pip build-essential git python3 python3-dev ffmpeg libsdl2-dev libsdl2-image-dev\
    libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev zlib1g-dev\
    libgstreamer1.0 gstreamer1.0-plugins-base gstreamer1.0-plugins-good libpulse\
    pkg-config libgl-dev opencl-headers ocl-icd-opencl-dev libzip-dev
     
E: package libpulse is not found (my translation :-)
libpulse does not exist on debian. 

And it seems katago does not detect my nvidia card.
(I have a katrain version  1.7.6 which is running fine on the same system (different partition) and it detects my card.)

Well, that is all I know :-)

**Comment by sanderland** [comment]
This is likely still a libzip issue, katago changed what it links to around the 1.8 or 1.9 version, and the katago that ships with katrain is just the official binary stripped of debug info. See #469

You can confirm this by starting katago manually. Unfortunately there is no easy fix I am aware of, and the most reliable way to get a working binary on linux is to compile it yourself.

**Comment by philbat** [comment]
I have compiled,too: same error

**Comment by sanderland** [comment]
it appears there was some change that makes it hard crash on not accessing the log file. Also, both the quotes and the home dir are not supported, so it never really worked.
In the next version, I am commenting out the log file line in the cfg, which resolves it.

**Comment by sanderland** [comment]
This has now been fixed upstream (the log file issue that is) and katago handles broken log file paths again.
