### ISSUE TITLE
version numbers damaged on macOS

### ISSUE THREAD

**Issue by core-code** [sanderland/katrain#480]
i've downloaded version 1.9.3 but after downloading it claims to be version 2.1.0.dev0

the CFBundleVersion and CFBundleShortVersionString entries in the Info.plist file are damaged
<img width="256" alt="Screenshot 2021-10-14 at 16 41 59" src="https://user-images.githubusercontent.com/1261954/137340786-532f612e-3c77-444d-9b6d-ff5b3099336e.png">

**Comment by sanderland** [comment]
> hm where is this '`fix-bundle-metadata.sh`' it is referring to located or documented?

https://github.com/kivy/kivy-sdk-packager/

**Comment by sanderland** [comment]
@core-code Does this artifact work better? https://github.com/sanderland/katrain/actions/runs/1345512441
