### ISSUE TITLE
Ubuntu 21.04 Engine died 

### ISSUE THREAD

**Issue by joe42** [sanderland/katrain#482]
I got this when installing with pip on Ubuntu 21.04.
I followed the troubleshooting section with no success.
When installing katrain from the source and running it directly with `python -m katrain` it finally gave me a bit more information - libzip 5 is missing. 
This library version is not available on my system. I had to install it from source, following:
https://noknow.info/it/os/install_libzip_from_source

The last part would be useful troubleshooting info for Ubuntu. Or maybe it's possible to use the previous version somehow?

Thanks for maintaining the project! Looking forward to using it :)

**Comment by kylebakerio** [comment]
man, how am I still running into this issue with 1.12 in an ubuntu 22.04 flavor?

**Comment by procraste** [comment]
Same thing  here on  Ubuntu 22.04.2 LTS ... Running i3 as window manager.

```
/usr/local/lib/python3.10/dist-packages/katrain/KataGo/katago: error while loading shared libraries: libzip.so.5: cannot open shared object file: No such file or directory
ERROR: Le moteur de jeu est tombé en panne:  status 127
```

Thanks
