### ISSUE TITLE
Feature request: Store PV and/or top N variations in SGF file

### ISSUE THREAD

**Issue by fishcu** [sanderland/katrain#486]
Katrain already has a very good system for storing analysis results in the SGF file, using what seems to be a compressed format.

For compatibility with other SGF viewers, it would be nice to have an option to store the principal variation(s) in the SGF file in a native format.

**Comment by sanderland** [comment]
The comment already shows the PV in a way sabaki handles nicely.
You mean add a branch for every move? This seems very messy.

**Comment by fishcu** [comment]
My use case is analyzing in Katrain, then uploading to OGS or KGS for collaborative review. OGS even complains that the .sgf files that store the full analysis are too big.

IIRC, some bots on OGS already do similar annotations automatically if you play against them.

If you think it's too messy, a good idea would be to limit such "explicit" branch storage to mistakes (point losses), for example.

**Comment by sanderland** [comment]
If it's too big, just turn this off
![image](https://user-images.githubusercontent.com/48946947/140779073-bfb95340-ed86-4d90-bdb9-f580bbf276aa.png)

I think that combined with the new option to add pv's on middle click should be enough.
