### ISSUE TITLE
Cleaner territory estimate display

### ISSUE THREAD

**Issue by milescrawford** [sanderland/katrain#487]
The dots-on-top view of estimated territory adds lots of unnecessary visual noise to the display. In addition, Katrain puts numbers and dots and other things on top of the stones, which are not compatible with this style. I suggest a contiguous shaded, underneath-stones display, as used by some other analysis programs.

Compare:
![Screen Shot 2021-11-10 at 4 53 38 PM](https://user-images.githubusercontent.com/11055723/141217893-512b02db-acab-4af7-8e0e-e34e8fb3f28e.png)
![Screen Shot 2021-11-10 at 4 53 23 PM](https://user-images.githubusercontent.com/11055723/141217897-c07deab4-7c97-4ac7-814b-9d468f7cf6d6.png)

**Comment by sente361** [comment]
This is a feature that I also greatly desire.  In my opinion the territory display in Katrain is a major defect. I really like the shading used in LizGoban which also gives the option to display the certainty of territory possession on a scale of 0 - 10.

![image](https://user-images.githubusercontent.com/47664082/141221721-cbd8f0f3-2ed9-4721-9398-63765a0d314e.png)

![image](https://user-images.githubusercontent.com/47664082/141221800-18bea445-db44-448c-8d40-5074cedb5f98.png)

**Comment by xiaoyifang** [comment]
> This is a feature that I also greatly desire. In my opinion the territory display in Katrain is a major defect. I really like the shading used in LizGoban which also gives the option to display the certainty of territory possession on a scal

In my opinion ,the display in LizGoban really a disaster,

**Comment by sanderland** [comment]
> It would be best to give users the option of selecting either territory display mode since it seems that different people have opposing opinions on the merits of these two options.

This is definitely not going to happen, as I think there's already so many options it's confusing.

@milescrawford  The clean, shaded view seems potentially better, and it's true I've not revisited this since the very early versions. Do you want to have a go at a PR?

**Comment by milescrawford** [comment]
I will take a look at the code, but it's a long way from my usual area of
expertise 🙂

**Comment by milescrawford** [comment]
I have something working, but I'm having trouble figuring out how to paint the squares underneath the stones - even when I flip the `draw_stone` calls after the ownership calls, the transparent ownership boxes are drawn on top, dimming the white stones and other markings instead of just the board below.  Still trying to learn how kivy manages z-index...

**Comment by sente361** [comment]
@milescrawford Thanks for doing this Miles! (Perhaps you can draw on the LizGoban repository or @kaorahi may help.)

**Comment by milescrawford** [comment]
After my patch, territory and teaching display look like the attached images. If this looks good to people, I can clean things up, run tests (are there docs on how to run the tests?) and submit a PR.
![Screen Shot 2021-11-11 at 11 43 48 PM](https://user-images.githubusercontent.com/11055723/141429431-e271edcb-9696-4479-b3f9-535886c43691.png)
![Screen Shot 2021-11-11 at 11 41 18 PM](https://user-images.githubusercontent.com/11055723/141429436-d6e74061-e126-4702-8544-001e46df5858.png)

**Comment by sente361** [comment]
It looks great to me. Well done Miles!

**Comment by milescrawford** [comment]
Okay, a PR's up for folks to discuss/amend. Thanks!

**Comment by sanderland** [comment]
![image](https://user-images.githubusercontent.com/48946947/141469691-50aa8e93-a8bc-47d2-9326-a68cf7d88434.png)
Maybe a little intense?

Themable, default 0.7

![image](https://user-images.githubusercontent.com/48946947/141470217-a2bb37c9-3e8f-47f4-aad7-ac627b596366.png)

**Comment by sente361** [comment]
@sanderland, has this PR been released? I can't find it in v1.10.1 and it isn't referred to in the manual or amongst the themes.

**Comment by sanderland** [comment]
> @sanderland, has this PR been released? I can't find it in v1.10.1 and it isn't referred to in the manual or amongst the themes.

It has not, it's only in the 1.11 branch. I see it's been quite a while and will release this month.

**Comment by sente361** [comment]
Many thanks @sanderland! I know there've been quite a few enhancements made since the last release. Many thanks for your great product!!!

**Comment by rooklift** [comment]
@milescrawford What app is your original screenshot from? I'm gonna use this style myself and should probably have a note acknowledging its origins... thanks.

**Comment by milescrawford** [comment]
I believe it's one of the display options in Lizzie:
https://github.com/featurecat/lizzie

**Comment by Carton** [comment]
Is there an option to switch to the original "dots-on-top view of estimated territory" view? In my opinion, "captured stones" are shown much in a much cleaner way in this "dots-on-top view".

Also, personally I think the new view seems to have more "noise" that I have to turn it off by default.

**Comment by fishcu** [comment]
Thirded. Furthermore, I don't see an option to tone down the opacity of the dark / light territory overlay.

**Comment by dutchsnowden** [comment]
I fully agree with @Carton, the new style is hard to see for me.

**Comment by milescrawford** [comment]
The opacity is already configurable in themes. It seems possible that the display style could also be made themeable. I would love to review a PR that added this if someone wants to try.

**Comment by milescrawford** [comment]
Also, it appears that this is all getting reworked in #555 - for better or worse.
