### ISSUE TITLE
Move tree: prune branch / remember last track

### ISSUE THREAD

**Issue by akk99** [sanderland/katrain#490]
Hi 
This project is godsend literally, as you know. Many thanks for that. 

I have two ideas that might make post-game analysis even more productive.

1. Crop node. When you come up with a very rewarding scenario, you may by then have dozens of nodes already in place, and depending on how you progress, you may want just keep this best streak as a foundation for further research - and have the rest erased. I came up with this idea when I deleted the wrong node by mistake.  "Crop the node" would do the trick, ie. remove all other nodes, and could come in two flavours: 
a. crop until the selected move, so that any moves and forks on the currently selected streak beyond the selected move would stay.
b. crop all - keep only the current node and only until the selected move.

2. App to remember the nodes you are traversing with left/right arrow. When the game is already advanced, it may help to move back and forth quickly to do instant checks of what led to the current outcome - and to get back to this same place, rather than end up elsewhere. 

So when you move back, with left arrow, game regresses beautifully, but right arrow held as you move forward again will get you to the very first of scenarios unless you watch the track. 
Letting Katrain stay on its rails as you move back and forth - unless you decide to side track with up/down arros - would make quick analysis possible without switching to Analysis mode, which helps if you want to keep an eye on the score rather than mind the forks so that you don't get lost. 

I hope it helps. I would love to see these changes and am sure they would bring the app's quick analysis to another level. I hope they fit into the concept. 

All the best. 
Tom

**Comment by sanderland** [comment]
1. Prune branch up to here is something I've wanted myself, and is straightforward, will probably add it.
2. Is harder, due to there being so many ways to navigate. Typically I just make a branch the primary one if I want to investigate it.  I would accept a PR that is done well, but probably find you many edge cases.

**Comment by akk99** [comment]
1.       Glad to hear that :)

2.       Happy to think through a PR. Meantime, just to let you know a friend has found out Sabaki has this staying on track implemented. Additionally, when tree view is on and several scenarios are in action, one thread is always highlighted – quite elegant. 

 

As I further look at it, right clicking on the tree in Sabaki reveals some further useful functionality. This, combined with what you have already implemented in KaTrain (score, winrate chart and figures, top moves etc ) would make it a monster.

Two more things, it would help if both the move tree and scores could be seen at a time. Today, I found a breakthrough move half into an already finished game while moving along the quite overgrown move tree. Luckily, the score view was on, and suddenly, I saw a huge leap to score on the chart. Further analysis showed that accidentally, I had made a good move but overlooked the chance. Alternatively, move tree nodes could be colour coded, with full red meaning loss and full green being total win. 

 

Okay, enough great ideas – always easier said than done. Please let me know if a PR for staying track will be of use for you.

**Comment by sanderland** [comment]
> 1. Glad to hear that :) 2. Happy to think through a PR. Meantime, just to let you know a friend has found out Sabaki has this staying on track implemented. Additionally, when tree view is on and several scenarios are in action, one thread is always highlighted – quite elegant. 

I like the highlight idea, as long as it's subtle. 

> As I further look at it, right clicking on the tree in Sabaki reveals some further useful functionality. This, combined with what you have already implemented in KaTrain (score, winrate chart and figures, top moves etc ) would make it a monster. 

What functionality? Keep in mind that Sabaki is far more focused (and has a better UI framework). In general I find KaTrain is already quite complex so am hesitant to add more functionality that is hard to find or use.

> Two more things, it would help if both the move tree and scores could be seen at a time. Today, I found a breakthrough move half into an already finished game while moving along the quite overgrown move tree. Luckily, the score view was on, and suddenly, I saw a huge leap to score on the chart. 

Aren't they already? Of course it always takes the top path now and this would reasonable change.

> Alternatively, move tree nodes could be colour coded, with full red meaning loss and full green being total win.

Definite no on this, I think it would make the move tree way too messy, and it already has quite a lot in a small area.

**Comment by sanderland** [comment]
prune branch done in 07839ac

**Comment by akk99** [comment]
Great news about prune :)

 

1.       Tree branch highlighting – as I looked again KT does have move highlighted, so the added value would be very slight.

2.       Sabaki right click functionality, I think you are right KaTrain has a workflow of its own, so adding new stuff needs caution.

3.       Score and tree at the same time – ah, sorry. In analysis view, the score and and winrate were off. Clicking these got them activated. Very useful to see both.

 

Some new ones for your consideration. 

 

Move tree quick glimpse

4.       Click and hold on a move in the tree for momentary position and score overview; release to get back where you were  – this is a known generic functionality in many apps & systems, and it could provide an elegant, bookmark-free way to compare outcomes of two different scenarios. 

5.       A subvariant, ctrl+click to peek at any place on the tree for a quick glance and until ctrl is released, cursor keys navigate that space locally. 

 

 

Cursor key navigation

6.       Jump to previously seen. If you left click on a move in a tree, this can teleport you to a completely different place. For example, nearing the end of the game, you want to see the beginning, click on move 5, do a bit of navigation there, then alt+left several times gets you back to the end game. Still a few things to check? Alt+right gets you back to the beginning. 

7.       Alt+click on a stone on the board gets you to the time the move was made. Hover with alt without a click could make it momentary. 

 

 

Engine for analysis 

8.       set to “as white” by default or set separately. Just a loose thought, I wonder if this would not be useful to use uber-pro KataGo for analysis even if you play against some less advanced bots.

 

Cheers.

**Comment by sanderland** [comment]
> 7. Alt+click on a stone on the board gets you to the time the move was made. Hover with alt without a click could make it momentary.

Double clicking a move does this.

> 8. I wonder if this would not be useful to use uber-pro KataGo for analysis even if you play against some less advanced bots.

Analysis is always full KataGo, regardless of the AI option.

**Comment by sanderland** [comment]
Closed as inactive
