### ISSUE TITLE
Feature request: random target score for AI position setup

### ISSUE THREAD

**Issue by nrobinaubertin** [sanderland/katrain#493]
Hi,

Thanks for making this wonderful tool.  
I would like to train my counting and thought that I could generate positions with the AI that I should evaluate. Unfortunately, we have to decide for a target score for black in the "set up position" menu. Could it be possible to add an option to let katrain choose a value at random in a target range ?

I understand that this may be a really niche usage so it may be not worth the trouble.

**Comment by sanderland** [comment]
Too niche, and I also don't think the positions it generates are particularly suitable for counting. Perhaps use "fast play out until end" and go back a suitable number of steps?

**Comment by nrobinaubertin** [comment]
You're right, I can stop the moves being played by hitting the escape key. That'll do it.  
With this trick in mind, I can just tell the calibrated AI to play against itself (instead of using the "set up position" feature) to have something more "natural".

Thanks
