### ISSUE TITLE
Allow configuration of "jump to mistake" threshold

### ISSUE THREAD

**Issue by milescrawford** [sanderland/katrain#494]
It would be fantastic if there were one more row of checkboxes on this screen, "Jump to mistake stops here" or "Include in jump to mistake" or something similar:

![Screen Shot 2021-11-29 at 12 42 01 PM](https://user-images.githubusercontent.com/11055723/143939974-d8723014-d9e1-4ae6-a15b-179dc31c162d.png)

When reviewing my kyu games, jump to mistake stops much too often, not allowing me to inspect my really impactful mistakes. It would be great if, just like the dots, it was up to the user how serious to consider each mistake.

**Comment by sanderland** [comment]
Isn't a change in point threshold sufficient?

**Comment by milescrawford** [comment]
Yes, that would be fine also. It just seemed like there was already config
for levels of errors and how they were displayed, so my first idea was to
use the existing one.

But I guess a separate field is better, since you really only need one
threshold.

**Comment by sanderland** [comment]
I mean you can change the first column, thereby making it stop less often

**Comment by milescrawford** [comment]
I'm sorry, I don't understand. Is one of the boxes in the first column used
for the stopping threshold? Which one? That is not indicated anywhere in
the UI.

**Comment by sanderland** [comment]
Orange is the mistakes threshold. You're right that this is not in the readme.

**Comment by milescrawford** [comment]
This seems like a nice quick way to indicate this clearly in the UI, so it's not a feature hidden in the manual. I don't know how to get kivy to insert a row like this, though.

![143939974-d8723014-d9e1-4ae6-a15b-179dc31c162d](https://user-images.githubusercontent.com/11055723/144328687-c8c823bc-f751-4bc1-a6d2-4a4cf4639dd7.png)

**Comment by sanderland** [comment]
That's the fun part, kivy gridlayout doesn't have a colspan thing like css

**Comment by sanderland** [comment]
Closing as it's low priority and doesn't seem like it will happen, although not opposed to a PR in principle
