### ISSUE TITLE
[feature request] add a panel to display all the availabe shortcuts

### ISSUE THREAD

**Issue by xiaoyifang** [sanderland/katrain#495]
for example, press key ?  then display a popup dialog ,list all the available shortcuts.
maybe not show all the shortcuts,but only show the most common used shortcuts.such as https://github.com/sanderland/katrain#-keyboard-and-mouse-shortcuts

**Comment by sanderland** [comment]
Doesn't the app already link to the github help?
Overall, too much hassle with translations and not very interesting to implement.
