### ISSUE TITLE
Hot-key to show best variation

### ISSUE THREAD

**Issue by Eric-Wainwright** [sanderland/katrain#497]
When analyzing a game, I usually just have Show Dots turned on.  Then, when I’ve made a sub-optimal move (e.g. a lemon, lime, or apple), I back up using the left arrow, turn on Show Top Moves, hold my mouse over the blue move, view the best variation, turn off Show Top Moves, then go forward using the right arrow.

Instead, it would be great (!) if I could accomplish this with just a single hot-key press (maybe ‘m’).  Pressing the hot-key again (or escape) would return to the previous state.

**Comment by sanderland** [comment]
Clicking on the offending move does this, no?

**Comment by raspingbard** [comment]
Actually, it would be great if you could turn all the number keys into hot-keys that would show the top 9 or 10 variations.  The number keys are also conveniently placed near the QWERT hot-keys which I use all the time.

**Comment by sanderland** [comment]
Hmm, the problem with hotkeys for PVs is that cancelling them is quite linked to mouse movement.

**Comment by raspingbard** [comment]
I'm not sure I understand.  A mouse movement could cancel a PV, yes, but so could another press of the same hot-key, or a different hot-key.

**Comment by sanderland** [comment]
Just saying it's a little trickier. How would you imagine the user would intuit which PV belongs to which hotkey? Ordering moves by internal visit count-but-not-the-ones-from-explored-moves is not very intuitive

**Comment by raspingbard** [comment]
I would order the PVs by points lost, or by whatever method you're using in the Performance Report to find the "AI Top 5 Match %".  You could just map keys "1" thru "5" to those moves if you want.

**Comment by sanderland** [comment]
Closed among inactive issues as a general cleanup
