### ISSUE TITLE
Tsumego frame for life/death problems

### ISSUE THREAD

**Issue by kaorahi** [sanderland/katrain#498]
I imported "tsumego frame" from lizgoban as an exercise of python. It helps AI to solve life/death problems slightly better than mere use of "smaller board" or "region of interest". Does anyone want to use this feature seriously?

(black to play: from https://www.h-eba.com/heba/tumego/eba.html)

![tsumego_frame](https://user-images.githubusercontent.com/38910552/148642920-dc6f88cd-cf8e-4ea3-8361-8515d23f8035.png)

* Fill the rest of the board evenly so that katago concentrates on the problem.
* Set ko threats only for the opponent so that katago finds unconditional solutions (not ko solutions). This seems important in my experiences.

(tentative usage)

1. Put a problem on the 19x19 board.
2. Hit `u` key to copy tsumego frame to clipboard. (`shift`+`u` for ko problem)
3. Hit `ctrl`+`v` to paste it.
4. Set region of interest manually from Analysis Options if you like more efficient search.

I dare to require `ctrl`+`v` to avoid unintentional loss of the current board by an accidental hit of `u`.

https://github.com/kaorahi/katrain/tree/tsumego_frame

**Comment by sanderland** [comment]
Will have a look later

**Comment by kaorahi** [comment]
Thanks for the revision!

**Comment by sanderland** [comment]
Menus + analysis region setting added and merged into 1.11 at https://github.com/sanderland/katrain/pull/506  , please test :)

**Comment by kaorahi** [comment]
It seems to work well in brief tests. :)

**Comment by kaorahi** [comment]
The default margin 5 may be too large? It destroys ko threats in large size problems.

**Comment by sanderland** [comment]
Can you give an example?

**Comment by kaorahi** [comment]
If I allow ko in this problem, no room is left for B's ko threats.

![broken_ko_threat](https://user-images.githubusercontent.com/38910552/157053862-7e0d1b66-d505-40a0-ab53-f4b33d579e5d.png)

(The third problem in https://www.h-eba.com/heba/tumego/eba.html)

**Comment by sanderland** [comment]
it's a tough balance, but i've set it to 4 now

**Comment by sanderland** [comment]
Closing as it's released

**Comment by xiaoyifang** [comment]
katrain support arbitary board size ,which means ,you can do this.
![image](https://github.com/sanderland/katrain/assets/105986/094b12a6-11aa-48be-bdf1-67d1f9e6fd4d)
