### ISSUE TITLE
Crash/freeze

### ISSUE THREAD

**Issue by peepo** [sanderland/katrain#501]
macbook pro 2015 running Ubuntu 20.04, katrain v1.10.1, analysing 9x9 game played on GoQuest
recently, possibly last 7 days katrain has started crashing whole system:
cursor moves, but click do not function.
reboot...

possibly due to recent Ubuntu updates.
this box is near vanilla install, only used for web browsing, email & katrain,
nothing else installed or used.
had been running fine for a few weeks previously, getting a little hot on occasion,
nothing too ridiculous afaict.

**Comment by sanderland** [comment]
This sounds like a hardware problem
