### ISSUE TITLE
When i exit katrain process remains for several minutes.

### ISSUE THREAD

**Issue by kotenok2000** [sanderland/katrain#503]
Microsoft Windows [Version 10.0.22000.434]
katrain version is 1.10.1

**Comment by sanderland** [comment]
What happens when you use the "Debug" exe with command line?

**Comment by kotenok2000** [comment]
No errors.

**Comment by kotenok2000** [comment]
0, ntoskrnl.exe!KiDeliverApc+0x1b6
1, ntoskrnl.exe!KiSwapThread+0x936
2, ntoskrnl.exe!KiCommitThreadWait+0x159
3, ntoskrnl.exe!KeDelayExecutionThread+0x416
4, ntoskrnl.exe!IoCancelThreadIo+0x1378b2
5, ntoskrnl.exe!PspExitThread+0x2c3
6, ntoskrnl.exe!NtTerminateProcess+0xf1
7, ntoskrnl.exe!KiSystemServiceCopyEnd+0x25
8, ntdll.dll!NtTerminateProcess+0x14
9, ntdll.dll!RtlExitUserProcess+0xb8
10, kernel32.dll!ExitProcessImplementation+0xb
11, DebugKaTrain.exe+0x12258
12, DebugKaTrain.exe+0x121f4
13, DebugKaTrain.exe+0x86bb
14, kernel32.dll!BaseThreadInitThunk+0x10
15, ntdll.dll!RtlUserThreadStart+0x2b

**Comment by sanderland** [comment]
> No errors, but sitll slow

I can not reproduce this. What happens when you ctrl-c during this time, with debug=2 on in general settings? you should get stack traces of threads
