### ISSUE TITLE
zsh bad interpreter error - python3.7 path

### ISSUE THREAD

**Issue by evolvingwild** [sanderland/katrain#512]
MacOS Monterey. A few weeks ago I installed katrain through homebrew and had no problems. Everything worked fine. Recently, I ran a brew upgrade, which upgraded Python (I believe) to 3.9. I am now getting the following error when attempting to launch katrain from the terminal: 

`zsh: /usr/local/bin/katrain: bad interpreter: /usr/local/opt/python/bin/python3.7: no such file or directory`

After I saw this, I reinstalled katrain, katago, and python3.7 hoping it may fix this issue, but it did not. From what I can tell, it appears katrain is looking for python3.7, but with the upgrade this is no longer available in the `/usr/local/opt/python/bin/` directory. Based on some searching, it appears I may just be able to `cp` python3.7 to this location, but before I do this I wanted to make sure I'm not doing something wrong. I'm also not entirely sure how to go about that either. Any ideas?

**Comment by evolvingwild** [comment]
Looking into this more, I tried uninstalling the brew install of katrain and reinstalling via`pip3` as described in the [command install guide](https://github.com/sanderland/katrain/blob/master/INSTALL.md#command-line-install-guide). After this, I was able to get katrain to open without issues via the terminal. I assume this was an issue with the upgrade to python 3.9 via brew that didn't update a symlink somewhere. I'm going to leave this open for the time being since this may still be an issue? Please let me know if this is a problem on my end only, and I'll close the issue.

**Comment by sanderland** [comment]
I've linked it in the main monterey thread. Hopefully the next release should fix some.
