### ISSUE TITLE
Missing options ?

### ISSUE THREAD

**Issue by Meeeds** [sanderland/katrain#513]
Hello, 

I am sorry but after looking a lot I cannot find these options, how can I : 

1. Display the absolute value of point on the board instead of the relative gain/loss ?
2. Turn off the computation of the graph when I load a sgf, indeed my computer is really slow and it takes way too much time when I just want to analyse moves ?

**Comment by sanderland** [comment]
1. It is in teaching/analysis settings
2. Hitting Esc stops all queries.

**Comment by Meeeds** [comment]
Thank you very much !
