### ISSUE TITLE
Generate an .exe on Win 10 from source codes 

### ISSUE THREAD

**Issue by chengkun-wu** [sanderland/katrain#518]
Hi, I added some features to the Katrain code like loading SGF files directly from online Go platforms. Then I tried to generate an .exe from the source code on Win 10 using pyinstaller and auto-py-to-exe. However, I failed to make it work. Can you please help me with the .exe generation procedure? Thanks!

Chengkun

**Comment by sanderland** [comment]
https://github.com/sanderland/katrain/blob/master/spec/KaTrain.spec

**Comment by chengkun-wu** [comment]
Thanks a lot!
