### ISSUE TITLE
UI breaks over Google Desktop if laptop lid is closed

### ISSUE THREAD

**Issue by aahlad0** [sanderland/katrain#519]
Running on Windows 11. Laptop configured to remain on with lid closed and accessed via Google Remote Desktop. KaTrain is the only program with UI issues when lid is closed - paints a white rectangle and stops. All is well with the lid open.

**Comment by sanderland** [comment]
Sounds like a kivy issue, and one unlikely to be fixed unless you are willing to investigate and develop one yourself.
