### ISSUE TITLE
how to change use katago with cuda and tensorrt ?

### ISSUE THREAD

**Issue by tanguofu** [sanderland/katrain#524]
it is will hangup  when i just replace with  katago-v1.11.0-trt8.2-cuda11.2-windows-x64.zip , 

so it there some extras configure to setup  katago with cuda and tensorrt?

many thanks

**Comment by sanderland** [comment]
Read the KataGo manual and try to get it to work by itself before using it in KaTrain. This is not a forum for help with KataGo, use the discord for technical help.
