### ISSUE TITLE
libssl1.1 dependency Ubuntu 22.04 Jammy Jellyfish

### ISSUE THREAD

**Issue by peepo** [sanderland/katrain#529]
unfortunately my excellent katrain setup is now broken '127' the obvious error is: libssl1.1 cannot find shared object file
Ubuntu 22.04 now using libssl3

did not find workaround as yet...

any pointers appreciated!

tx

**Comment by peepo** [comment]
wfm: not recommended, but...
download:
http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1-1ubuntu2.1~18.04.15_amd64.deb
be sure to install the version that suits your setup!
sudo dpkg -i libssl1.1_1.1.1-1ubuntu2.1~18.04.15_amd64.deb
tx

**Comment by kylebakerio** [comment]
just came here with this issue.

That link is now dead. :(

**Comment by kylebakerio** [comment]
new link, this answer worked for me: https://askubuntu.com/a/1410366/422405
