### ISSUE TITLE
Eric-Lizzie theme still shows variations

### ISSUE THREAD

**Issue by milescrawford** [sanderland/katrain#530]
Setting the scale to 0 in the theme suppresses the display of the low-confidence hints, but not their functionality - so moving the mouse around the board triggers the animation of suggested sequences when no visible target is under the mouse. Confusing.

**Comment by sanderland** [comment]
Should be fixed in [8e91f23](https://github.com/sanderland/katrain/pull/550/commits/8e91f23e0b9b829a6ed97d50da53aa9c73bc5562)
