### ISSUE TITLE
won't start says something about OPENGL 2.0 doesn't exists (not opencl)

### ISSUE THREAD

**Issue by bxc2739** [sanderland/katrain#533]
won't start says something about OPENGL 2.0 doesn't exists (not opencl)

**Comment by bxc2739** [comment]
This not worky

![image](https://user-images.githubusercontent.com/101810221/171652141-2e8641c3-2d3a-460c-93d9-20c1df62717c.png)

**Comment by bxc2739** [comment]
![image](https://user-images.githubusercontent.com/101810221/171652295-b6a70f70-fdf7-4eeb-9c17-ac380bc98469.png)

**Comment by sanderland** [comment]
Does not appear to be a katrain issue
