### ISSUE TITLE
katrain windows version 1.11.1 can not run

### ISSUE THREAD

**Issue by xiaoyifang** [sanderland/katrain#534]
katrain.exe from https://github.com/sanderland/katrain/releases/tag/v1.11.1
can not open on Windows.
throw error "Failed to execute script __main__"

![image](https://user-images.githubusercontent.com/105986/175435920-37092e7d-2211-451e-97fe-814e762df954.png)

**Comment by sanderland** [comment]
Fixed with 1.11.2
