### ISSUE TITLE
SGF Picker inconvenient for large folders

### ISSUE THREAD

**Issue by pdeblanc** [sanderland/katrain#535]
When loading SGFs from a folder containing many SGF files, it takes a while to find the right one.

I haven't done any research into this yet, but if it's possible to use a native file picker, or else some existing file picker widget, that may be a good path forward. Otherwise, I have a few specific suggestions:

1. Do some kind of speed optimization (e.g. just loading the file list from `GoGoD/Database-2020-2021/2021`, a database of pro games, takes a second or two currently; that's about 1,700 files)
2. Allow the list to be sorted by file name
3. Provide a draggable scroll bar, or some other way of scrolling faster

**Comment by sanderland** [comment]
I might look into #2, but kivy widgets are all kind of from scratch
