### ISSUE TITLE
The program runs on macOS with no effect.

### ISSUE THREAD

**Issue by xsw0** [sanderland/katrain#539]
No windows or programs pop up, and there is no process named katrain in the background
device version: MacBook Pro (13-inch, 2019, Two Thunderbolt 3 ports)
system version: macOS Big Sur 11.6.7
katrain version: 1.10 & 1.11 file install and brew install

**Comment by sanderland** [comment]
Please use the discord for technical help. Issues are mainly for when you have details of the cause, such as stack traces and console logs.
