### ISSUE TITLE
[Feature Request] Delayed Top/Policy moves

### ISSUE THREAD

**Issue by dustinlacewell** [sanderland/katrain#540]
This is just a feature suggestion that came to mind recently, feel free to close if it's not interesting.

I would like some way to delay showing the top/policy moves while I am playing games against the AI. This way I can have a chance to read the board myself for a few moments, before seeing what the AI thinks. Preferably, the delay would be configurable.

As I imagine it, this will be a much nicer training workflow for me rather than constantly toggling top/policy moves on and off over and over.

**Comment by sanderland** [comment]
The intended use is something like: have top moves etc off, use teaching game. If a move is undone and you really can't figure it out and all you have are game ending mistakes, maybe then peek.
With the keyboard shortcuts this should be pretty easy anyway.
