### ISSUE TITLE
Wrong OpenGL version in Windows .zip (2.0 demanded, 1.1 included it says)

### ISSUE THREAD

**Issue by deegeebee** [sanderland/katrain#542]
After encountering problems with the Linux install, I'm trying Katrain on a native Windows 10 VM. I've just downloaded and unpacked the .zip but I'm getting a fatal error (attached). I assume OpenGL 2.0 should be inside the .zip? Since I can't find its location, I don't know where to update it (to).
I hope this information will help to fix this.
![Kivy FE](https://user-images.githubusercontent.com/41020108/182022538-b7e36f22-08c4-4840-a203-aced772f14a7.png)

Windows download .zip on 08/31/22 ; Windows 10 VM on Virtualbox 6.1_6 with GuestAddons

**Comment by deegeebee** [comment]
My mistake. Sorry, misunderstood what OpenGL was. I'll try updating my VM.

**Comment by trunterzx** [comment]
Hi @deegeebee how did you resolve this issue? I'm also experiencing the same thing

**Comment by deegeebee** [comment]
@trunterzx While I got the impression it had to do with my (virtual) graphic card/driver, I didn't solve it but got katrain running on Linux. Please ask the katrain discord community, they are very helpful (and prefer to answer questions there, my mistake to ask here). Good luck, it's a great program!

**Comment by trunterzx** [comment]
@deegeebee I see. By discord are you referring to the computer go community discord channel?
