### ISSUE TITLE
On macbook air M2, katrain won't do "show all dots"

### ISSUE THREAD

**Issue by yuffington** [sanderland/katrain#543]
Is there an issue with this running on mac?  or specifically M2 architecture macs?

When I toggle show dots, it only goes between showing none and showing the last 3 (per the setting).

Running v1.11.2fixes-for-osx.

Any help appreciated, and if I'm missing something obvious, sorry for the trouble.

**Comment by yuffington** [comment]
Sorry, it seems I'm running the latest version - v1.11.2fixes-for-osx

**Comment by yuffington** [comment]
It seems this feature was removed at some point.   I'll close this.  Thanks.

**Comment by sanderland** [comment]
Updated the readme, thanks for reporting :)
