### ISSUE TITLE
Request: Additional Help / documentation how to set up katrain AI correctly; plus where to ask questions :)

### ISSUE THREAD

**Issue by deegeebee** [sanderland/katrain#545]
Hi,
since the Discord seems not that alive and I didn't want to clutter a "general computer go" server with katrain questions, I hope you don't mind too much if I ask a question / documentation feature request:

What I want to do:
I am a beginner (so I'm 30kyu or close), and I would like to play Katrain Graded Rank AI (since I assume it won't make 'stupid' mistakes on purpose like other bots) so I learn without immediately hitting a dan strength AI.
Plus I thought 'a teaching game' is good.

What I did:
Settings: Human; AI Katrain 15k, Teaching game.
I thought this meant "Teach me how to play like a 15 kyu, that's complicated enough for now".

What happened:
Settings 'Show Top Moves" on - "+1.2", #1 move according to policy - I play there - dark red circle - the "Teacher" removed the stone because it lost too many points (6.9).
'Try something else.'
'WTF, I only did what you suggested?!'

I assume my settings are wrong - is the Kyu AI calculating the 'Top Moves' I often follow while the 'teaching game' AI is still the full dan AI which criticizes the Graded Rank kyu for doing a bad job? 
So, can I either play human against graded rank, or have a teaching game with the pro teacher AI, but not be trained to be a DDK player for the time being?
I wanted to avoid that because I think the moves of dan players will be above my head. 

Would you be so kind and explain this to me and maybe consider adding it to the docs?
Thanks a lot!

Plus, if possible in any way, is there a place to ask katrain-related questions without cluttering programmers' spaces?
Thanks!

**Comment by sanderland** [comment]
> Plus, if possible in any way, is there a place to ask katrain-related questions without cluttering programmers' spaces?

Use discord, the gui channel is intended for katrain/lizzie/ogatak/.. discussions and help. This right here however, is a programmer's space intended for bug reports and contributions.
