### ISSUE TITLE
FAQ request: how to update? python/pip?

### ISSUE THREAD

**Issue by peepo** [sanderland/katrain#547]
as mentioned in various places: troubleshooting/FAQ info would be useful.

I can find no information on 'updating'

~$ pip install -U katrain

Defaulting to user installation because normal site-packages is not writable....

similarly:

~$ python3.10 -m pip install katrain
or
~$ pip3 install -U katrain

I believe this is something to do with python, but as I do not use python, not much idea of how to resolve....

any guidance would be appreciated

xx

./local/bin/katrain wfm
ubuntu 22.04, python 3.10, pip 22.0.2 trying to update katrain1.10 to latest:

**Comment by HackYardo** [comment]
Do you mean update automatically or update by hand? By hand way is simple: just download the new one and over write the old one.

**Comment by HackYardo** [comment]
Do you mean update automatically or update by hand? By hand way is simple: just download the new one and overlap the old one.

**Comment by peepo** [comment]
Is that is the 'official' way to upgrade?
which folders need to be replace by overlap?
xx

**Comment by sanderland** [comment]
If you installed using pip, the upgrade command you post is correct. The warning is irrelevant unless you previously used sudo to install system-wide.
If you download and run the source code, @HackYardo's way is correct.

**Comment by peepo** [comment]
okay thanks for the sudo comment:
sudo pip3 install -U katrain
downloaded katrain-1.10.1...
is this correct? (my previous version was 1.10.0)
ie to get 1.11 does one have to download sources at this time?
tx

**Comment by sanderland** [comment]
<4 was changed to <3.10 due to #499
If you want to force it, try adding --ignore-requires-python

**Comment by peepo** [comment]
okay tried -ignore-requires-python, had to install numpy, else crashes
now has libzip5 dependency:
libzip.so.5: cannot open shared object....
latest ubuntu seems to be libzip4
tried sudo apt-get install libzip5
"unable to locate package libzip5" universal depository is enabled.
engine died unexpectedly: status 127

**Comment by peepo** [comment]
found:
https://github.com/lightvector/KataGo/issues/312

**Comment by peepo** [comment]
seems libzip issue has arisen once again see
https://github.com/lightvector/KataGo/issues/479

1.10.1 or certainly 1.10.0 was working fine...

without resolution, how to revert to previous version??

**Comment by peepo** [comment]
built katago takes 5 minutes, F8 and link to build....

txx
