### ISSUE TITLE
iPadOS M1 support

### ISSUE THREAD

**Issue by peepo** [sanderland/katrain#548]
katrain for ipad0S M1 would be very welcome indeed

if this is not going to happen (understandable)
is there any app for katago that runs on iPadOS M1 chip? apologies, slightly off-topic:

 [Master of Go](https://apps.apple.com/us/app/id1442035374) uses katago, but  development seems patchy....
have raised [issue](https://github.com/new3Rs/a_master_of_go/issues/108) & emailed developer regarding M1 support
developer Yuji san confirmed M1 support as of 5 days ago (email)

also interface seems less attractive than katrain....

thanks again

GoQuest on my iPad2 died today, looking for alternatives!!

**Comment by sanderland** [comment]
No.
