### ISSUE TITLE
Feature request: Let katago think about the position without showing top moves

### ISSUE THREAD

**Issue by bryancheny** [sanderland/katrain#549]
I would love if pressing space for continuous analysis wouldn't forcefully show the top moves. Pressing deeper analysis (the key a) also reveals the top moves. I want to think about the position myself while letting katago also run in the background. This lets me analyze the position and think about the best move without the engine feeding answers to me. Would greatly appreciate this feature!

**Comment by sanderland** [comment]
Will look into making it less aggressive.

**Comment by sanderland** [comment]
Have a look at [01e487b](https://github.com/sanderland/katrain/pull/538/commits/01e487b6e3cf8ab20f234da97ec0e0e76d6a709a)
- Only space forces hints on, and it can be turned off
- Shift-space bypasses the hints on

**Comment by bryancheny** [comment]
It works perfectly! Thank you!
