### ISSUE TITLE
Add Version # to Executable File Metadata (Windows)

### ISSUE THREAD

**Issue by ulty4life** [sanderland/katrain#551]
In the Windows build, add the build version number to the executable file's metadata, so the version number can be read by examining the .exe metadata.

**Comment by sanderland** [comment]
Seems nice, feel free to PR to https://github.com/sanderland/katrain/blob/master/spec/KaTrain.spec to make this happen

**Comment by ulty4life** [comment]
Reference links:

https://pyinstaller.org/en/stable/usage.html#capturing-windows-version-data

https://stackoverflow.com/questions/56806489/set-product-version-number-metadata-on-exe-file-with-pyinstaller

**Comment by ulty4life** [comment]
> Seems nice, feel free to PR to https://github.com/sanderland/katrain/blob/master/spec/KaTrain.spec to make this happen

@sanderland this is complete, where do you want the pull request to go? 1.11.3 branch, master, new branch? Changes are enitrely in 1 new file + KaTrain.spec

**Comment by sanderland** [comment]
1.11.3 will do, thank you
