### ISSUE TITLE
UI Bug (?): (Windows) KaTrain Stuck on Second Monitor after Monitor Disconnected

### ISSUE THREAD

**Issue by ulty4life** [sanderland/katrain#552]
Windows 10, KaTrain versions 1.10 and 1.11.2

KaTrain was last run on a second monitor. Now with the second monitor disconnected, every time KaTrain is started it appears on the non-existent second screen with no way to access or move it.

Most Windows applications can be moved via keyboard commands by selecting the application, using ALT+Space to bring up the application's window menu, and pressing the "M" key to activate the "Move" command. This window menu is not present in KaTrain, and so cannot be moved.

Windows can also usually be moved by using the Windows Key+[Arrow Key] command to minimize, maximize, restore, and dock the application window to the left or right half of the screen. This also does not work.

I'm stuck not being able to use KaTrain until I can connect an external monitor as a second screen and extended desktop to be able to access it (and move it back to the main monitor).

**Comment by ulty4life** [comment]
I'm guessing the KaTrain UI is built entirely as a graphics display, and thus doesn't have any of the default Windows window commands. I noticed there is a config file with a UI section. Are there any config values that can be added to specify the window position?

**Comment by ulty4life** [comment]
Was finally able to connect an external monitor and move KaTrain back to the main display.

KaTrain DOES have a window menu, but the Windows shortcut of ALT+Space to activate this menu with the keyboard is used by KaTrain to toggle other options, blocking the menu from being opened.

**Comment by sanderland** [comment]
I do not see the windows menu open with alt-space even when all keyboard hooks are disabled. Perhaps investigate and file upstream with the kivy devs?
