### ISSUE TITLE
Restrict Deeper Analysis To A Move Range [Feature Suggestion]

### ISSUE THREAD

**Issue by JackWarren98** [sanderland/katrain#562]
Sometimes people don't want to analyse the entire game. It would be good to allow users the option to analyse only certain ranges moves. For example, 0-90 means analyse only first 90 moves.

This idea can be taken further by allowing the user to choose number of visits for different parts of the game. Like, 5000 visits for the moves 20-60, 2000 visits for the moves 61-90 and no analysis for the rest of the moves.

**Comment by sanderland** [comment]
> Sometimes people don't want to analyse the entire game. It would be good to allow users the option to analyse only certain ranges moves. For example, 0-90 means analyse only first 90 moves.

Happy to accept this as a PR, e.g. two int inputs with 0 and 999 for starting/ending move.

> This idea can be taken further by allowing the user to choose number of visits for different parts of the game. Like, 5000 visits for the moves 20-60, 2000 visits for the moves 61-90 and no analysis for the rest of the moves.

I think this is going too far, and could be easily done by opening the dialog twice if a move range is added

**Comment by jacobm-tech** [comment]
I liked the idea and took a crack at it, see pull request. This is work in progress for now, the pull request is to get an initial review.

* Need to work some more on interface - I would like the start move and end move to be visibly greyed out or even disappear when the checkbox for move range is not selected. I don't know how to do that, right now I disable these fields when the checkbox is off, but they are visually present and confusing.
* I would like to have a subscript or superscript labels saying "start" and "end" for the fields, but I don't know how to do that with Kivy.
* There are several i18n items, e.g. the string "performing full game analysis with %d visits" is not appropriate. For now, I just display an English string.

**Comment by sanderland** [comment]
Completed via #563
