### ISSUE TITLE
Teaching mode doesn't work correctly

### ISSUE THREAD

**Issue by Nick-Zhao-Engr** [sanderland/katrain#565]
Hi, teaching mode seems to not work correctly on my MacBook M1 Pro. I have correctly installed katago, and analysis tool works fine. But when I tries to start a teaching game, the software can't undo my lousy move (with red or yellow dots shown on the stone, as shown in the following image). I have set number of undos to be 1 for point loss greater than 3.
Actually, I don't quite know how to correctly start a teaching game. In the official tutorial (https://www.youtube.com/watch?v=wFl4Bab_eGM), It seems that it will enter teaching mode and undo my bad moves automatically once I configure teaching settings.
<img width="1092" alt="image" src="https://user-images.githubusercontent.com/62821851/196128532-5eaf9eaa-02bc-4e64-9fc6-e86b3e7254e1.png">

**Comment by sanderland** [comment]
Teaching mode is activated by setting the human player to this mode. You set it to 'normal game' now.

**Comment by Nick-Zhao-Engr** [comment]
I didn't notice this teaching/normal game option when starting new game 😂. Thank you for solving my issue and sharing this wonderful teaching tool with us. Good luck!
