### ISSUE TITLE
Observe & Analyse IGS games

### ISSUE THREAD

**Issue by DonMathi** [sanderland/katrain#567]
It would be a great feature if KaTrain could connect to IGS and observe a game, and run analysis of the game, while the moves are arriving. 
Joining up in communities on Discord and discuss games from tournaments played on Pandanet/IGS, could then be assisted with KaTrain receiving the moves directly from the server. 
A single person could then share the analysis with the others on Discord.

**Comment by sanderland** [comment]
This is way out of scope on what the program does, and is even unlikely to be accepted as a feature if you would do all the (many) hours of work to implement it yourself, sorry.
