### ISSUE TITLE
Uncertainty measure

### ISSUE THREAD

**Issue by phdsmhong** [sanderland/katrain#568]
Hello Sanderland, thank you so much for creating Katrain. I have benefited a lot. 

I heard that Katago evaluates uncertainty of its value network output. Can we check this uncertainty measure in Katrain? or do you know where I can easily check this measure? I thought this will be a super useful feature to analyze a game. 

For instance, I am referring to the %win uncertainty and score uncertainty you can find in the link.
https://katagobooks.org/book7tt/root/root.html

**Comment by sanderland** [comment]
I've never seen anyone use this to good effect, keep in mind it is very hard to interpret due usually being much higher than you would expect.

> Win% Uncertainty: Measure of uncertainty in Win%. **Does NOT correspond to any standard well-defined statistical metric, this is purely a heuristic indicator.** 

So I think it won't be useful, but a lot of people will be confused. If the scaling is ever resolved and it is easier to interpret, it would not be too difficult to add as one of the two stats you can pick on a move though

**Comment by phdsmhong** [comment]
Thank you so much for your reply! I thought that the uncertainty measure is still useful to quantatatively classify players' styles although being a heuristic indicator. :)
