### ISSUE TITLE
Eliminate numpy from KaTrain

### ISSUE THREAD

**Issue by jacobm-tech** [sanderland/katrain#569]
KaTrain currently imports numpy, with the only non-trivial use being 

```
self.gridpos = np.rot90(self.gridpos, -1, (0, 1))
```
for board rotation. It is possible to use 
```
self.gridpos = list(list(x) for x in zip(*self.gridpos[::-1]))
```
(adapted from [here](https://stackoverflow.com/questions/8421337/rotating-a-two-dimensional-array-in-python)), and just use list of lists everywhere instead of a numpy array. This also means that `self.gridpos[x, y, 0]` becomes `self.gridpos[x][y][0]` everywhere. I made a version like this locally, it seems to work fine with rotations. 

I think that unless there are bigger plans for numpy, it's worth getting rid of it, since it does take up a lot of the space in binaries, and also has a startup time. Also, all the code except board rotations uses the list of lists style. Please let me know if I should submit a PR.

**Comment by sanderland** [comment]
Agreed, I only noticed what a pain it gave to binaries (intel mkl argh) after accepting the pr and haven't gotten around to removing it.

**Comment by jacobm-tech** [comment]
I did not get rid of numpy in setup.py. Is it enough to get erase that line there? I am not familiar with setuptools.

**Comment by sanderland** [comment]
there is probably something in the pyinstaller spec as well, I remember struggling with those changes to get numpy in and will have to have a look at how it was before

**Comment by sanderland** [comment]
All done
