### ISSUE TITLE
Consider adding TensorRT and CUDA versions of KataGo for warp speed!

### ISSUE THREAD

**Issue by jacobm-tech** [sanderland/katrain#573]
KaTrain currently offers Eigen, AVX2, and OpenCL versions of KataGo in the settings menu. In the last couple of releases, since October 2021 it looks like, KataGo added a TensorRT backend, and a CUDA backend was added some time before. Out of curiosity, I decided to install these versions myself, and got this:

OpenCL:

```
numSearchThreads =  8: 10 / 10 positions, visits/s = 81.85 nnEvals/s = 67.48 nnBatches/s = 17.02 avgBatchSize = 3.96 (98.6 secs) (EloDiff +64)
```

CUDA:

```
numSearchThreads = 10: 10 / 10 positions, visits/s = 139.88 nnEvals/s = 118.83 nnBatches/s = 24.04 avgBatchSize = 4.94 (57.8 secs) (EloDiff +90)
```

CUDA + TensorRT:
```
numSearchThreads = 12: 10 / 10 positions, visits/s = 245.07 nnEvals/s = 204.81 nnBatches/s = 34.58 avgBatchSize = 5.92 (33.1 secs) (EloDiff +38)
```

TensorRT is 3 times faster than OpenCL! Did not expect this much difference. This is on my laptop's GPU. As a bonus, the laptop works fine while running the TensorRT version, while OpenCL makes it crawl.

I've been missing out! All this time, I could have had KaTrain telling me "a blind sheep could have played better than you in this corner" with even more speed and authority.

Installing the TensorRT version on Windows was just a little bit of trouble - you need to download the enormous CUDA toolkit, set up paths, and compile a zlib library. I wonder if we can help people get this version by including it in the menus, and possibly adding some pointers in the documentation about installing CUDA/TensorRT.

**Comment by jacobm-tech** [comment]
The numbers above are for the latest 60-block network. For the more typical 20-block, it's a smaller difference, but TensorRT is still around twice as fast. The GPU is the 3050 Ti mobile.

**Comment by sanderland** [comment]
I'd be happy to have a guide with instructions up as an .md to link to, but I think the sheer amount of questions and failures something like this will generate as an in-program feature just is a huge drain on my time. This is also why I avoid the cuda version (on top of it being slower for me than opencl anyway).

**Comment by HackYardo** [comment]
I suggest to add a sentence into readme.md with a link to KataGo's, 
e.g.

KaTrain offers Eigen, AVX2, and OpenCL versions of KataGo in the settings menu. For often much better performance on NVIDIA GPUs, try TensorRT, but you may need to install CUDA+CUDNN+TensorRT from Nvidia, [more details](https://github.com/lightvector/KataGo#opencl-vs-cuda-vs-tensorrt-vs-eigen).

**Comment by sanderland** [comment]
Added to readme
