### ISSUE TITLE
Idea: show difference in territory between the last move v.s. the average of possible green moves from the last position

### ISSUE THREAD

**Issue by ChristopherKing42** [sanderland/katrain#574]
Being able to tell what you gained or lost would be useful. I propose a feature where it compares it to the average of the green moves.

More precisely, after making move 14 (for example), it would compare the ownership in the current board state v.s. the average ownership if you made a random green move for move 14 instead

I think this is better than comparing to the perfect move because:

- if you do make the perfect move, it wouldn't show any gains or losses. By comparing to the other green moves, you can get a sense for what parts of the board you could have affected while still making a good move
- for other moves, comparing to the perfect move could be biased against where that move was. comparing to an average of multiple alternatives should smooth it out more

**Comment by sanderland** [comment]
I have not found ownership differences to visualize well except for large mistakes, which is already implemented in teaching games.
I don't think averaging over top moves would make much of a difference, and it would have issues with low confidence predictions, but if you are able to show it does with some examples, I may reconsider.

**Comment by ChristopherKing42** [comment]
> I have not found ownership differences to visualize well except for large mistakes

Hmm, what if it compares the move you made to passing then. Passing is almost always a big mistake, so it should be useful to see how that compares to the move you made, right? For example, if you save a group, it would show that in green since passing wouldn't save the group.

**Comment by sanderland** [comment]
You're welcome to try different things and post screenshots of the results and mockups in this issue.
