### ISSUE TITLE
Correction based on win probability rather than loss of points

### ISSUE THREAD

**Issue by jesse794** [sanderland/katrain#576]
First, thank you for working on Katrain.  I've been a casual player for years, and no other method has helped me improve as much as Katrain.  One suggestion:  It would be helpful if there were an option for Katrain to only undo/correct moves if they significantly decrease the win probability, not if they just cost you points.  I'm about 12kyu, and if I play against a calibrated rank of 11kyu, my goal is to win even if only by a small margin.  However, if I'm ahead by a few points and have a high win percentage, Katrain will often tell me to play away from a current battle because it knows that I can hold my existing territory even if I play elsewhere for a turn.  The problem is that one needs to be a much stronger player than I am in order to make that play elsewhere and then come back and defend my existing territory.  So if I follow Katrain's advice, I then have to have it guide me step-by-step for how to come back and hold the previous area.  Basically it pushes the game to a level that's beyond where I am right now.  For me, if I can gain the upper hand in overall score against an equal-level opponent, I need to hold that advantage by securing my territory rather than adding complexity beyond my level and digging a hole that only a dan-level player could get out of. Thanks for considering this request.

**Comment by sanderland** [comment]
That would undo every move in a close endgame, which is not a great user experience. I'd advise you to just give play the move anyway, or give yourself an undo by going back when you feel like it.

**Comment by jesse794** [comment]
Thank you for the very quick reply.  In a close endgame, I think that it would actually be the correct response from Katrain to point out tiny errors.  If i'm up by 0.5 pt with just a few moves left, then I do want it to show me those tiny errors, since they would result in a big shift in win percentage.  I guess my point is that at my level, when playing against an equal opponent, I just try to win.  I don't want to risk losing by trying to win by a larger number of points.

Of course Katrain is still excellent as it is.  I just think it would be even better if it didn't push me into playing situations that I don't have the skills to get out of.

**Comment by sanderland** [comment]
Sorry, but I think you have the wrong impression of what a winrate based undo would do, and this isn't going to happen.
