### ISSUE TITLE
Engine died unexpectedly during training

### ISSUE THREAD

**Issue by subspacefield** [sanderland/katrain#577]
KaTrain 1.11.2
OS: Win 10 22H2 19045.2251

During training receiving the message: Engine died unexpectedly without sending output: status 3221226505. This has happened with 2 different training sessions.

Are there logs or anything else I can do to investigate this issue?

**Comment by sanderland** [comment]
You can use debugkatrain.exe or run in a shell, but it's probably a gpu memory issue. does this happen even when setting # games to 1?

**Comment by subspacefield** [comment]
It also happens when # games = 1. Attached log messages from debug console.
[debugkatrain.txt](https://github.com/sanderland/katrain/files/9980354/debugkatrain.txt)

**Comment by sanderland** [comment]
Not much there. It might just be that training is heavier (or you usually don't run a 60b model)
Only last thing I can suggest is running without ownership visualization

**Comment by subspacefield** [comment]
In the training settings I changed KataGo version to OpenCL (not bigger boards) and it started working.
