### ISSUE TITLE
UI Font (Size) Configuration?

### ISSUE THREAD

**Issue by josswright** [sanderland/katrain#58]
It seems trivial alongside the core of the program, but is there any possibilty of having the fonts (or at least font sizes) configurable?

I opened this on a large monitor, and the fonts are coming up fairly huge and distracting. I can see that they're being resized on the fly as the window resizes, but in most situations I'd much prefer a consistent size even if the window is resized. Ideally, it would be really useful to be able to set at least the font size, and preferably the fonts themselves, for the UI.

**Comment by sanderland** [comment]
The popups with settings should have fairly fixed sizes, the rest of the UI scales. I find scaling to be a major challenge since users have such a huge range of platforms/monitors.
One thing that would help is showing which text shows up as too large, by including some screen shots.
