### ISSUE TITLE
Space Repetition and Katrain

### ISSUE THREAD

**Issue by jcguu95** [sanderland/katrain#580]
I wish to train myself with space repetition and Katrain. Is it possible?
More concretely, I am looking for an option to do the following.

1. Maintain a list of wrong moves/nodes I made throughout my life.
2. For each such move, a keypress messages katrain to show that node.
3. (Bonus) Katrain shows 4~5 spots for me to choose, and rate my answer. Even better it may start to recognize my weak spots by ranking the nodes which suggest how often I should review this node.

I can read and write python. So if it's possible but currently unavailable, pointing me to the relevant source code would be helpful! Thank you.

**Comment by sanderland** [comment]
This has been asked for, but is way out of scope of the program. Also, I don't think spaced repetition for go is useful if only the top move is rated as correct.

**Comment by jcguu95** [comment]
@sanderland Thanks for your response. I understand it is out of scope of the program. But I think it'd be helpful for technical user to instruct the program in a more programmatic way (either by userscripts, sending messages, or direct hacking). Would you mind pointing where I should start from hacking for the features I personally want?

> Also, I don't think spaced repetition for go is useful if only the top move is rated as correct.
We don't have to make it so strict. For example, we can make it let the users pass as long as the winrate doesn't drop by more than 5%. (The crux that prevents me from beating a higher dan is that I made often make 3 moves that cut down winrate by 10%.. I need a more systematic way to fix this.. and I believe this is useful for many people.)

**Comment by sanderland** [comment]
katrain-bots is probably a good example, but getting a bit out of date

I just pushed this branch which contains some recent hackery on getting the bot to run again https://github.com/sanderland/katrain-bots/tree/fix-1
