### ISSUE TITLE
How to show winrate change on baduk pan?

### ISSUE THREAD

**Issue by jcguu95** [sanderland/katrain#582]
**Description**

By default, with analysis turned on, average points loss are shown on the baduk pan. Is there any way to show winrate change instead? 

**Why is it useful?**

Often times, there could be moves that both lose `0.1` point, but with one losing `6%` winrate, while the other losing `2%` winrate. It'd be beneficial if we can see how much winrate a move loses on the board directly.

**Comment by sanderland** [comment]
Yes, teaching and analysis settings allow you to pick any two things to show on the move.
However, keep in mind that in your example, the small difference is likely just statistical noise unless you have an extreme amount of visits.
