### ISSUE TITLE
Fix territory display in teaching games

### ISSUE THREAD

**Issue by jacobm-tech** [sanderland/katrain#583]
Currently, there is a breakage because the lines 

```        if Theme.TERRITORY_DISPLAY == "marks":
            self.draw_territory_marks(grid, loss_color=None)
        else:
            self.draw_territory_color(grid, loss_color=None)
```
are wrong and should not have the `None`, which got copied from the function declaration and prevents the loss color from ever being displayed. I, uh, have no idea who might have done that.

In addition to this fix, I'd like to test out the teaching functionality and see if the loss shading needs to be tuned. I think it is currently overly saturated when a group dies, because loss is up to 2 points per intersection, but the shading was designed to work with ownership, which only goes to 1.

**Comment by milescrawford** [comment]
https://user-images.githubusercontent.com/11055723/205393164-6fd5450c-03a9-49de-a8dd-41cf36daad80.png

**Comment by jacobm-tech** [comment]
I am currently testing out my fixes for this. Just removing the incorrect `None` and letting the loss be drawn produces this:

<img src="https://user-images.githubusercontent.com/35696962/205455677-a8a5ce66-9f9a-4d8f-98c1-63011ed55236.png" width=250/>

The red color is too saturated because point loss per intersection can exceed 1, this also leads to a very large red mark on the stone. I reduced the alpha of the red color, and for any intersections where point loss exceeds 1, I use the purple color, resulting in this:

<img src="https://user-images.githubusercontent.com/35696962/205455422-704beb25-68ac-4da1-aedd-080c40aadf64.png" width = 250/>

I still have some work to clean up and test the code before submitting the pull request.

**Comment by sanderland** [comment]
I would be inclined not to introduce a new color, but just decrease the magnitude (scale/clip, whatever looks nice)

**Comment by jacobm-tech** [comment]
Submitted a PR. The second-level coloring is gone, although I think that rivulets of purple where you got massacred looked snazzy. I used HINTS_ALPHA for the maximal loss shading, could introduce a new variable if anybody may want to tune these separately.
