### ISSUE TITLE
Feature Request: Hide moves in "Policy Moves" mode which fall under a specificed percentage/certain colors

### ISSUE THREAD

**Issue by BombBurperZ** [sanderland/katrain#585]
Instead of showing a color for every single point on the board there should be an option to hide every move that falls under 5% or something or even turning off all the non-green moves, making it so that it would appear less cluttered and more similar to "top moves"

**Comment by milescrawford** [comment]
I like this idea, or possibly just a "display best X moves" option.

**Comment by sanderland** [comment]
I think it's fine for what it is, a toggle to occasionally use when you are very interested in what kind of order-of-magnitude the policy of various moves is.
