### ISSUE TITLE
download models

### ISSUE THREAD

**Issue by sanderland** [sanderland/katrain#59]
idea: set folder for models instead of path
within that path, have a dropdown of available models and option to download others.

**Comment by hope366** [comment]
Download KaTrain-v1.1.2, unzip it, and then run KaTrain.exe and The following error occurs
![無題](https://user-images.githubusercontent.com/63999713/83949295-ea076700-a85d-11ea-92b7-c88ddeaea0ed.jpg)
I know this is probably an elementary error, but I'd appreciate any advice.
