### ISSUE TITLE
Error: SSL Certificate & No binaries available for MacOS?

### ISSUE THREAD

**Issue by psygo** [sanderland/katrain#590]
Is this expected??? Is there a quick solution? (I'm using MacOS Big Sur 11.7.2, the latest there is.)

![Screen Shot 2022-12-28 at 10 21 33](https://user-images.githubusercontent.com/11823725/209818823-48511c4f-67db-4a3d-8298-d6533288cb5e.png)

**Comment by sanderland** [comment]
Binaries are not made available for mac (other than the one included in katrain, or installable through brew). If you want a cpu-only version, you have to compile it.
The certificate issue is also mentioned in #414 with some possible fixes, but it's rather a mess.
