### ISSUE TITLE
stone is placed outside the board

### ISSUE THREAD

**Issue by xiaoyifang** [sanderland/katrain#591]
![image](https://user-images.githubusercontent.com/105986/211442476-858c2174-9a2f-40c5-9293-899bbb70ee78.png)

move 34,

[KaTrain_Human (Normal Game) vs AI (KataGo) 2023-01-10 09 20 26.zip](https://github.com/sanderland/katrain/files/10378230/KaTrain_Human.Normal.Game.vs.AI.KataGo.2023-01-10.09.20.26.zip)

katrain version:  v1.21.1
katago version , 1.12.0-opencl

**Comment by sanderland** [comment]
Network and visits?

**Comment by xiaoyifang** [comment]
default visits 
network is kata1-b40c256-s11840935168-d2898845681.bin.gz
