### ISSUE TITLE
KaTrainDebug triggers Windows Defender

### ISSUE THREAD

**Issue by apetresc** [sanderland/katrain#592]
Not sure if this is just a resurfacing of #333 with a newer PyInstaller or something else, but Windows Defender again has an issue with KaTrainDebug as of release 1.12.1 (it didn't happen on my system with the previous November release):

<img width="409" alt="image" src="https://user-images.githubusercontent.com/14872/211630506-f8aae1bc-cb42-4151-82ee-7404d592d93e.png">

Not sure if there's anything you can do about it, but thought I'd bring it to your attention.

**Comment by sanderland** [comment]
yeah not much I can do about this.
