### ISSUE TITLE
1.12.1 version throw an exception of kivy

### ISSUE THREAD

**Issue by xiaoyifang** [sanderland/katrain#594]
![image](https://user-images.githubusercontent.com/105986/211800668-d6682aa4-fb6d-4937-821a-b20b69801a63.png)

**Comment by xiaoyifang** [comment]
maybe my computer's problem , it works before and suddenly crashed.

**Comment by trunterzx** [comment]
@xiaoyifang  How was it resolved? I'm having the same issue too

**Comment by xiaoyifang** [comment]
reinstall gpu driver , `windows update` seems like to downgrade the gpu driver occasionaly.
