### ISSUE TITLE
Why arent the AI settings preserved between invocations of KaTrain.exe?

### ISSUE THREAD

**Issue by metaperl** [sanderland/katrain#595]
I changed the AI settings from calibrated rank to simple style and then click "Update AI settings" and then exit KaTrain.

I then restart it and the AI settings have returned to calibrated rank.

**Comment by sanderland** [comment]
* Set calibrated rank to 3k in settings
* Restart
* Check settings, it's still 3k

You may be confusing selecting an AI to play against (which is done in the rightmost player dropdown) with configuring it

**Comment by metaperl** [comment]
Here is an example of attempting to set the type of AI to do analysis with and expecting it to persist between invocations of KaTrain.
