### ISSUE TITLE
Where will the path to katago config file and katago model file resolve to?

### ISSUE THREAD

**Issue by metaperl** [sanderland/katrain#596]
The paths to the katago config file and model file are relative paths, as this screenshot shows. But are these paths correct? And where do they resolve to?

<img width="627" alt="KaTrain_(1)_LhzH73TAWp" src="https://user-images.githubusercontent.com/21293/211828457-8c103532-8bb7-423c-920e-06f9bb27fb3c.png">

**Comment by sanderland** [comment]
katrain/ is a magical prefix that resolves to files shipped with the program
