### ISSUE TITLE
Why does pressing enter in Analysis mode choose a less-than-optimal move? And why would such a move be called *the* AI move?

### ISSUE THREAD

**Issue by metaperl** [sanderland/katrain#597]
The README states:

> [enter] AI move. Makes the AI move for the current player regardless of current player selection.

but what is **the** AI move? and why did the AI select a yellow move instead of a the green move with the highest gain?

Before and after screenshots attached.

<img width="551" alt="KaTrain_(1)_rG4sXtTYlt" src="https://user-images.githubusercontent.com/21293/211841612-177db165-79f2-4e74-a15e-c2010205868e.png">

<img width="555" alt="KaTrain_(1)_IlpfVANIcb" src="https://user-images.githubusercontent.com/21293/211842488-86eb0dfb-1082-4d90-947e-46ee9cf77a8a.png">

As you can see, it played `D2` which is a yellow move, not the best move.

**Comment by sanderland** [comment]
Moves are ordered by katago based on lcb, but the above really is some weird output. Do you have an sgf + settings?

**Comment by metaperl** [comment]
what does `lcb` stand for?

**Comment by metaperl** [comment]
> Do you have an sgf + settings?

How do I export my settings from KaTrain?

**Comment by sanderland** [comment]
> what does `lcb` stand for?

https://github.com/lightvector/KataGo/blob/master/docs/Analysis_Engine.md

> The SGF for the game is attached.

That does not seem to be the game.

> How do I export my settings from KaTrain?
Just saying what network is used helps
