### ISSUE TITLE
Bundled katago version is not enabled for distributed.

### ISSUE THREAD

**Issue by kotenok2000** [sanderland/katrain#601]
# I have a bug report

Please include details of the settings you use, steps to reproduce the problem, and console output.
Using https://github.com/sanderland/katrain/releases/tag/v1.12.1
ERROR: task loop loop thread failed: Server returned error 400: This version of KataGo is not enabled for distributed. If this exact version was working previously, then changes in the run require a newer version - please update KataGo to the latest version or release. But if this is already the official newest version of KataGo, or you think that not enabling this version is an oversight, please ask server admins to enable the following version hash: 773e329a0c1ecd9ec16c7bb3d4719a4f1dcd1133-opencl

**Comment by sanderland** [comment]
Apparently another katago release was removed, updated release. Thanks for reporting

**Comment by kotenok2000** [comment]
Dis this happen before?
