### ISSUE TITLE
UI-Panel ordering moves by size of mistake.

### ISSUE THREAD

**Issue by DeFlow** [sanderland/katrain#604]
# I have a feature request

In reviewing games, we try to take away a couple of things from every game to improve. KaTrain could help with this by having an overview of move number and mistake size. As such, it is easy to jump around in the game to the different mistakes, and quicker to improve from reviewing.

**Comment by sanderland** [comment]
The red arrow is kind of meant for this. Even then, in my experience, 'mistake size' does not really tell you very well which were the most important points in the game.
Overall I would expect a feature like this to take many hours of iterating and experimenting, and end up with more confusion than anything.
