### ISSUE TITLE
Played a game for which the file crashes Katrain

### ISSUE THREAD

**Issue by GaijinFizz** [sanderland/katrain#605]
# I have a bug report

This is an .NGF file from a game played on Yugen No Ma (same server as Wbaduk). 
First time I see this but I cannot browse the game in Katrain. 

Analysis starts and the graphs build but impossible to browse the moves (one by one or directly to the end of the game).

Error message:
![image](https://user-images.githubusercontent.com/2937588/218451256-d4c91084-309f-45b8-9761-5010b49c006a.png)

NGF File:
[202302132046ぱいーぐるpjw235165.TXT](https://github.com/sanderland/katrain/files/10721903/202302132046.pjw235165.TXT)

**Comment by GaijinFizz** [comment]
humm actually I think that's just the button to go to the end of the game that works strangely with this game.
It doesnt display the last position but if I go back one move then it works.

**Comment by sanderland** [comment]
It looks like the last move is "AA" which is like (0,0). Can you confirm this was a 'pass' ?

**Comment by GaijinFizz** [comment]
That's right, White passed and then Black just asked for counting.

**Comment by sanderland** [comment]
Fixed in [e75fd1f](https://github.com/sanderland/katrain/pull/606/commits/e75fd1f093146c39597c05825a8fcf65021f86de)
Thank you for the report

**Comment by GaijinFizz** [comment]
Thanks for fixing this!
