### ISSUE TITLE
Scrolling to end of previously analyzed game causes crash

### ISSUE THREAD

**Issue by Eric-Wainwright** [sanderland/katrain#608]
Ver: KaTrain 1.12.3
Env: Windows 10

Repro steps:
1) Start KaTrain and maximize the window.
2) Open one of the attached games.
3) Click towards the end of the move tree.
4) Use the right-arrow to scroll to the end of the game.  KaTrain crashes.

This doesn't happen if the window is not maximized. It also only seems to happen on certain games.

[Games.zip](https://github.com/sanderland/katrain/files/10736934/Games.zip)

**Comment by sanderland** [comment]
Can not reproduce. Do you have a stack trace?

**Comment by Eric-Wainwright** [comment]
I tried capturing the log file by executing this in the console:

    DebugKaTrain.exe > out-crash.txt

But, nothing is written to the file.  If I quit KaTrain normally, then it will record the log.  Is there anyway to force the console to always write the log?

[out-quit.txt](https://github.com/sanderland/katrain/files/10761935/out-quit.txt)
[out-crash.txt](https://github.com/sanderland/katrain/files/10761936/out-crash.txt)

**Comment by sanderland** [comment]
And you don't get a stack trace in the console either when running it there? Very strange.

**Comment by Eric-Wainwright** [comment]
When I say "console", I really mean from cmd, as I'm not compiling the code.  The out-crash.txt file is completely empty if KaTrain crashes (which seems strange).

**Comment by sanderland** [comment]
I mean there is no need to redirect to a file and depend on stdout vs stderr if the cmd just stays open after the crash and allows you to read all output

**Comment by Eric-Wainwright** [comment]
The cmd window stays open after the crash, but nothing is output after I load the game into KaTrain.

![Console output](https://user-images.githubusercontent.com/28121941/219811220-0e0b4d2c-81c3-42cb-acc1-f2c727a72fa2.png)

**Comment by sanderland** [comment]
Very strange. This should not really be possible. Without this information and not being able to reproduce kind of stops any fixes.

**Comment by Eric-Wainwright** [comment]
It's a weird one.  If you're not able to repro it, you should probably just close the issue.  Thanks.
