### ISSUE TITLE
Loading an SGF without analyzing it

### ISSUE THREAD

**Issue by Dontbtme** [sanderland/katrain#61]
_ Sometimes we only want to analyze some parts of a game, like matters of life and death, a joseki trick, the endgame, etc.
_ Sometimes we want to replay some parts of a game against bots for practice, like an invasion, a running battle, the endgame, etc.
1) The problem is that currently as far as I know there's no way to simply open an SGF without the engine starting an analysis of the entire game.
2) There is also no way to interrupt an analysis (apart from shutting down Katrain :D)

_ Sometimes we want to take a look at previously analyzed SGF.

3) Sadly we can't reuse saved SGF from Katrain itself. If a user saved in an SGF say 3 analyzed big mistakes, he probably would expect Katrain to be able to open it and interpret directly the saved data by showing accordingly 3 dots, scores, win rates, lost points, PVs and Top moves.

**Comment by sanderland** [comment]
1. Why is it a problem? The fast analysis is pretty fast, and low-priority asynchronous so you can analyze while it's working.
2. And that will stay that way
3. Likewise
