### ISSUE TITLE
Feature Request: compare current game fork result with main game fork result

### ISSUE THREAD

**Issue by kylebakerio** [sanderland/katrain#611]
When playing out an alternate sequence, it would be nice if we could get some data on how different the outcome would be if this sequence had been played vs. the actual game's main sequence at the equivalent move. Just something like "this sequence would have resulted in B+3.2" shown in the details, basically.

In theory, this _seems_ like this would be a pretty easy feature to implement; I'm a JS guy who hasn't touched python professionally in a few years, and have never done desktop dev, but if you want to guide me with an overview, I'd be open to trying to make the modifications myself.

**Comment by kylebakerio** [comment]
Well, I guess there's two interesting things to check; one is how things have changed since you started the mainline branch, the other is how things went different compared to the game as it went. My use case is analysing games I played out, so I'm interested in comparing branch-move-70 to mainline-move-70.

**Comment by HackYardo** [comment]
You can solve it by running two KaTrains if it possible. 
Or try LizGoban, it can "copy" and "paste" games at sidebar.
