### ISSUE TITLE
Security: username/password should not be stored in plaintext in config file

### ISSUE THREAD

**Issue by kylebakerio** [sanderland/katrain#612]
If you set up for distributed training, the username/password you enter will be stored in the config file in plain text. This is a security risk; people could be re-using that password. They could copy/paste that config during debugging, and if someone gets access to their machine, a search for "password" could turn up that file and give a hacker a password to try for other known accounts (and/or be easily picked up by a script doing this very basic scrape).

**Comment by sanderland** [comment]
Yeah I've had people donate their password in an issue 😅 
The program is open-source though, and needs to send the password in plain text to a server (which is likely not very secure either). There is no way to store it without it being trivially readable.

**Comment by kylebakerio** [comment]
fwiw, katago was also spitting out username/password in the logs when connecting. I mentioned it on discord and lightvector mentioned it was a bug and immediately fixed it on master, which was cool, and supposedly added safeguards to make sure that doesn't happen again.

When compiling katago for distributed training, it requires an ssl package be included, so I am under the impression that it doesn't send that over plaintext.

The option I would imagine (definitely adds complexity) (linux, no idea about windows/mac) would be using local .ssh key to encrypt and store it encrypted. If this were written in node instead of python I'd be able to contribute this, but would probably be a non-trivial dive for me to do this.

If nothing else, you might include a checkbox next to username/password that asks if you want to store it, and include a warning that it's stored in plaintext.

**Comment by sanderland** [comment]
![image](https://user-images.githubusercontent.com/48946947/225300127-87bec7a4-85f8-4868-80a2-df42c7d548e0.png)
[ffe3bb2](https://github.com/sanderland/katrain/pull/606/commits/ffe3bb207be80d43e4dff45b3747868e0e804654)

**Comment by kylebakerio** [comment]
I think that counts as the minimum effort version that's reasonable. I might suggest "stored _locally_", but up to you.
