### ISSUE TITLE
Feature Request: hotkey hints on hover

### ISSUE THREAD

**Issue by kylebakerio** [sanderland/katrain#615]
Memorizing a list of hotkeys available on github is clunky. Would be nice if hotkey hints were available next to clickable options, or at least on mouse hover.

(Again, I hope this is ok; there's no expectation of this work being done, just making suggestions when ideas come to me and putting them here.)

**Comment by sanderland** [comment]
I think this was in some early version and just a maintenance nightmare.

**Comment by kylebakerio** [comment]
Hm, that's a bummer. Should be relatively easy in an html/css environment, but I'm not familiar with desktop app dev.
