### ISSUE TITLE
make modern AIs play at kyu level

### ISSUE THREAD

**Issue by Hong-yu1999** [sanderland/katrain#619]
I am here https://lifein19x19.com/viewtopic.php?f=10&t=17488 I saw in your post that you mentioned some things about adjusting Katago's chess skills, and I am also interested in it. If possible, could you provide a more detailed description?

**Comment by sanderland** [comment]
That is the most detailed description out there, other than the source code.
https://github.com/sanderland/katrain/blob/master/katrain/core/ai.py has the algorithms
if you want to discuss, the discord I keep linking to is a better place than github
