### ISSUE TITLE
after updating AMD adrenalin to a new version the AI calibrated rank plays stupid moves

### ISSUE THREAD

**Issue by nachtzwaluw** [sanderland/katrain#620]
hey,

In the last month's I have tried a few times to update AMD Adrenalin to a higher version than 22.11.2. on my Ryzen 5900HX WIN11 system with Katrain installed (latest version) using OpenCL and a 20 block model.

Every time that I updated it the AI calibrated rank starts to play stupid moves:  passes on move 2, playing a lot of moves on the edge of the board etc.
Even  when I am playing against AI single digit kyu's.

I have tried to remove Katrain and reinstall it but that does not help. The only thing is to reinstall the AMD Adrenalin version 22.11.2.

Anyone an idea how to solve this problem?

Thanks!

**Comment by sanderland** [comment]
no
