### ISSUE TITLE
Suggestion: Syntax

### ISSUE THREAD

**Issue by RobertJasiek** [sanderland/katrain#628]
For Windows, the manual ought to describe the syntax of, and give examples for, the command line for
a) paths without blanks,
b) paths with blanks,
c) commands with gtp,
d) commands without gtp,
e) commands with -model,
f) commands without -model,
g) commands with -config,
h) commands without -config
etc. as far as such variants are possible. Currently, I guess that the following is an example with a correct syntax but I cannot be sure due to bugs:

C:\katago\katago.exe gtp -model C:\katago\b18.bin.gz -config C:\katago\gtp_custom.cfg

**Comment by sanderland** [comment]
It is literally just what you would use to start a katago json based analysis engine, and the option is only there for power users who know the ins and outs of using katago. If you don't, I suggest to stick to using the fields to pick a model and such.

**Comment by RobertJasiek** [comment]
For starters and thus far tested for OpenCL, do the following:

If analysis_config.cfg is missing, copy analysis_example.cfg to analysis_config.cfg . In KaTrain | General & Engine Settings | Override set a command line like this:

C:\<path>\katago.exe analysis -model C:\<path>\<model_name>.bin.gz -config C:\<path>\analysis_config.cfg
