### ISSUE TITLE
Command Line Fails

### ISSUE THREAD

**Issue by RobertJasiek** [sanderland/katrain#629]
I use Windows 11 Pro 64b, Baduk AI Megapack 4_18_0 x64 and its KaTrain 1.7.2.0. In KaTrain, this Override command line does not work due to a bug, although I guess that it has a correct syntax.

C:\katago\katago.exe gtp -model C:\katago\b18.bin.gz -config C:\katago\gtp_custom.cfg

**Comment by sanderland** [comment]
> Finally, you can override the entire command used to start the analysis engine, which can be useful for connecting to a remote server. Do keep in mind that KaTrain uses the analysis engine of KataGo, and not the GTP engine.

**Comment by RobertJasiek** [comment]
After two days of elaboration and help by others, now I know a working sample syntax so that I apologise for the suspicion of a bug! That KaTrain uses the analysis engine of KataGo means that, instead of **gtp**, put **analysis** in the command line and refer to an analysis CFG file.

I do not use a remote server but consider the Override command line essential for using the strongest local KataGo instance.
