### ISSUE TITLE
Update the installation docs for new Mac silicon information

### ISSUE THREAD

**Issue by davehcdn** [sanderland/katrain#632]
It looks like the installation document INSTALL.md is saying that Mac m1 is the "latest" and that some libraries don't support it yet.

I think a modern update of this 2022 install doc might help?

**Comment by sanderland** [comment]
Hey,
Sure, if you have tried installing from source on mac and have found the libraries working, a pr to update with the current state would be nice.

**Comment by davehcdn** [comment]
Yeah, I just tried an install and I think the libraries are working so maybe I'll try a PR
