### ISSUE TITLE
I can't start katrain v.14.0 

### ISSUE THREAD

**Issue by maoiii** [sanderland/katrain#640]
When I started TATRAIN, there was a crash. The interface shows that there may be out of memory. But before I was able to use the previous version of katrain. It's not clear to me if it's true that my hardware is the case.
![Z9TXB3ENKN{96G9MUW2ZG32](https://github.com/sanderland/katrain/assets/96247454/cffe63cb-bd5e-4c96-a772-569bbd3f7b8b)

**Comment by sanderland** [comment]
The default network has gone from 15b to 18b. If you have a very low-resource machine, try changing it back to 15b in general settings (f8)

**Comment by maoiii** [comment]
ok,thank you.The problem is solved.
