### ISSUE TITLE
Kindly move the Pass and Score badges so that it does not cover the board

### ISSUE THREAD

**Issue by hrishim** [sanderland/katrain#644]
Please read and fill in the appropriate template

# I have a question about using the program, or need technical assistance

Please use the Computer Go Community Discord (#gui) : http://discord.gg/AjTPFpN

# I have a bug report

Please include details of the settings you use, steps to reproduce the problem, and console output.

# I have a feature request

The Pass notification pops up right on top of the game. I find it difficult to see if I have any more moves to play. The final score also pops up similarly. It is annoying not being able to see the final played out game. Please move these to a different location.

**Comment by sanderland** [comment]
I find it works well since various weird things can happen in downloaded sgfs that make it unclear what happened at the end.
Simply hit back once or twice to get the board state before the pass moves.
