### ISSUE TITLE
Playing with katrain on a Ubuntu 22.04 computer

### ISSUE THREAD

**Issue by phi0042** [sanderland/katrain#647]
I would like to play with katrain on my Ubuntu 22.04 computer and I need libzip5. I have downloaded a libzip5 package from the Ubuntu 20.04 packages and now I need libssl1.1 which is not "installable". I don't know how to use katrain without breaking Ubuntu 22.04. Would it be possible to have an appImage instead ?

I have installed katrain with the command **pip3 install -U katrain**. I don't understand why my previous question was just closed without explanation and without answer. Once closed, nobody can answer anymore. 

The compilation instructions do not work. The command **pip3 install -r requirements.txt** fails with the message "Encountered error while trying to install package ffpyplayer". I have the version 3.10, which is > 3.6 (the requirement). Some of the missing packages to install with the **apt** command do not exist either in Ubuntu 22.04. If katrain does not support Linux, just say it and I won't waste my time thanks.

**Comment by Cabu** [comment]
I have Ubuntu 22.04 too. To install libzip5, you also need to install libssl1.1. I personally did it the following way:
´´´
wget http://mirrors.kernel.org/ubuntu/pool/universe/libz/libzip/libzip5_1.5.1-0ubuntu1_amd64.deb
wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2_amd64.deb
sudo apt install ./libssl1.1_1.1.1f-1ubuntu2_amd64.deb  
sudo apt install ./libzip5_1.5.1-0ubuntu1_amd64.deb
´´´

References:
https://askubuntu.com/questions/1437133/does-ubuntu-22-04-support-the-libzip5-package
https://gist.github.com/joulgs/c8a85bb462f48ffc2044dd878ecaa786

**Comment by phi0042** [comment]
Thanks, I'll check it out!

pg.

**Comment by EdNa482** [comment]
Hello
These commands helped me run katrain 1.14. with KataGo AI on Ubuntu 22.04:

`sudo ln -s /usr/lib/x86_64-linux-gnu/libzip.so.4 /usr/lib/x86_64-linux-gnu/libzip.so.5`

`sudo ln -s /usr/lib/x86_64-linux-gnu/libssl.so /usr/lib/x86_64-linux-gnu/libssl.so.1.1`

`sudo ln -s /usr/lib/x86_64-linux-gnu/libcrypto.so /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1`

The engine itself is not built correctly; it refers to specific packages, although each package is regularly updated.

**Comment by exxelxior** [comment]
Hi!

> The compilation instructions do not work.


Could you show the errors you have (step by step) when trying installation from sources?

### Installation from sources
This section describes how to install KaTrain from sources, in case you want to run it in a local directory or have more control over the process. It assumes you have a working Python 3.6+ installation.
   * Open a terminal.
   * Run the command git clone https://github.com/sanderland/katrain.git to download the repository and change directory using cd katrain
   * Run the command pip3 install . to install the package globally, or use --user to install locally.
   * Run the program by typing katrain in the terminal.
