### ISSUE TITLE
Point Lost/Gained on the right

### ISSUE THREAD

**Issue by hgfedcba** [sanderland/katrain#65]
I just found out about this program and like it a lot, however I immediately noticed a problem when analysing a game of mine. I the UI-element where Score/Win rate/Point loss are displayed numerically I found it very confusing that the point loss jumps between Black/White and even Loss/Gain. When i am just clicking through the moves I'd much rather see the gain for black every time and if he lost points display it with a "-" sign. The way it is now I activly have to read the whole line every time I click a move foward and sometimes I even get a double negativ (i.e. loss for white = gain for black).

**Comment by sanderland** [comment]
Please try to use it for a while and see if you get used to it. This particular feature has switched between  fixed B+/- x points -> W/B  +/- X points -> points gained lost and of the 3 options, this has so far gotten the fewest complaints about confusion.
