### ISSUE TITLE
No sound, Ubuntu 22.04, ffplayer req'd?

### ISSUE THREAD

**Issue by a1872** [sanderland/katrain#650]
Please read and fill in the appropriate template

# I have a question about using the program, or need technical assistance

I have Ubuntu Mate 22.04 and I have no sound, otherwise, the program works fine.  I was wondering if it's the ffplayer--is there a versiom that katrain needs?

Please use the Computer Go Community Discord (#gui) : http://discord.gg/AjTPFpN

# I have a bug report

Please include details of the settings you use, steps to reproduce the problem, and console output.

# I have a feature request

Go ahead, but keep in mind that the program is mostly in maintenance mode, and big changes are unlikely.

**Comment by a1872** [comment]
I found the deb for ffplay--4.1.9.

**Comment by Arcerius** [comment]
Same problem here (debian bullseye), but I think, I have solved it quite simple: Installed katrain via pipx; than have the installation in home (.katrain) and .local/pipx/venvs/katrain. In ~/.local/pipx/venvs/katrain/lib/python3.11/site-packages/katrain/gui/ is a file sound.py with 

the line 
# prefer ffpyplayer on linux, then others, avoid gst and avoid or ffpyplayer on windows
ranking = [("ffpy", 98 if platform in ["win", "macosx"] else -2), ("sdl", -1), ("gst", 99), ("", 0)]

Just changed ffpy to fflpay and everything works fine.

**Comment by exxelxior** [comment]
> Same problem here (debian bullseye), but I think, I have solved it quite simple: Installed katrain via pipx; than have the installation in home (.katrain) and .local/pipx/venvs/katrain. In ~/.local/pipx/venvs/katrain/lib/python3.11/site-packages/katrain/gui/ is a file sound.py with
> 
> the line
> # prefer ffpyplayer on linux, then others, avoid gst and avoid or ffpyplayer on windows
> 
> ranking = [("ffpy", 98 if platform in ["win", "macosx"] else -2), ("sdl", -1), ("gst", 99), ("", 0)]
> 
> Just changed ffpy to fflpay and everything works fine.

I have Debian Bookworm and the same problem but your solution fixed it!

**Attention**: there's a typing error in your comment: it's **ffplay**, not fflpay!

**Comment by sanderland** [comment]
fix included in 1.15
