### ISSUE TITLE
 I need the simplest method to call the AI model. For example, I directly input the black piece's position, such as  [4,5], and the AI model gives the white piece's position, such as [6,7] . Is there a simple way to achieve this by code ?

### ISSUE THREAD

**Issue by jinpengchina** [sanderland/katrain#651]
I need the simplest method to call the AI model. For example, I directly input the black piece's position, such as
[4,5], and the AI model gives the white piece's position, such as[6,7]. Is there a simple way to achieve this by code ?

**Comment by PJTraill** [comment]
I suspect you are in the wrong place. KaTrain is not a tool for accessing an AI, but for using one. Take a look at KataGo instead, but please read the documentation and choose a suitable (much shorter than here) title before posting. You might also search for the GTP protocol.
