### ISSUE TITLE
Feature Request: Allow weighting analysis mode moves using a certain AI style

### ISSUE THREAD

**Issue by IDex** [sanderland/katrain#655]
Often a player might wonder where e.g. the Simple Style AI would play in a given position/game. Currently the only way to ask these questions to certain strategies in analysis mode is to select them as players and then use the "Force AI move". This gives a one discrete move and a list of alternative coordinates, but actually seeing certain strategy's Top Moves on the board would make exploring those a lot easier.

If this sounds like something that would be useful, I think I could implement this given some rough direction on where to get the weighted moves and where to make the needed UI changes.

**Comment by tellistone** [comment]
I want this feature so bad!

Its fun to make the AI play a particular style, then try to teach yourself to play the same way - this would really assist.

**Comment by sanderland** [comment]
AIs are here: https://github.com/sanderland/katrain/blob/master/katrain/core/ai.py
Board drawing code is here: https://github.com/sanderland/katrain/blob/master/katrain/gui/badukpan.py

Be warned that this is probably a pretty complex thing to do.
