### ISSUE TITLE
Feature Request: "Random" AI and "Custom AI"

### ISSUE THREAD

**Issue by tellistone** [sanderland/katrain#656]
I recently discovered that the Simple AI can be modified, via its sliders, to be a variety of other AIs with distinct personalities. I've been fine tuning the personality to try and and get the style as close to that as my regular opponent as possible. This is AMAZING! 

In practice, I find it works something like this (being mindful of how opponent_fac and settled_weight interact when using negative values):

<img width="1190" alt="image" src="https://github.com/sanderland/katrain/assets/85873295/e1c857b9-5c9c-4392-8bcb-9fbab31ac4e3">

Honestly, I take my hat off to this capability, its made training so much better for me! You get really interesting results when using polarized personalities (only set one slider of **opponent_fac** or **settled weight** for example)

My ask here is two fold:

- Custom AI - same as "Simple AI", with as many configurable values available to sliders as possible. I see in the config file there are other configurable values not currently pushed to the interface, so the ability to tweak those without editing the file would be grand. This would be great for "tuning" custom AI personalities to more closely match a real world opponent for sparring.

- Random AI - Same as "Custom" AI with many sliders, except the sliders have two knobs and can be used to set ranges rather than values. For example, attach penalty range of -3.0 to +3.0. On game start, random values are assigned to each of the attributes within the defined range. The result is an opponent with distinctive style, but that the player is not forewarned of.

**Comment by sanderland** [comment]
I very much like the simple style AI as well, and glad to see someone enjoying it! It was also very funny to see it play on ogs and beat high dan players with relatively simple style.
However, time has shown that this kind of configuration is too complex for most users, and it leads to a lot of questions. The popular option is undoubtedly 'calibrated rank' - essentially the less configurable the better.
KaTrain is also very much in maintenance-only mode with me only reviewing the occasional contributions, keeping katago up to date, fixing bugs, but not much more.

**Comment by tellistone** [comment]
OK, thanks for maintaining this rad software in any case.
