### ISSUE TITLE
Bug: Can not correctly show the gui.

### ISSUE THREAD

**Issue by hiuxia** [sanderland/katrain#657]
# I have a bug report

- Here is the result of running the program from the .exe file (downloaded from github releases): 

![image](https://github.com/sanderland/katrain/assets/98009342/5a313779-9ea8-4876-b421-89e40f8851cc)

- Here is the result of running the source code: 

![image](https://github.com/sanderland/katrain/assets/98009342/225a4385-c44c-4449-8f27-0dd7831c1dd6)

> Still the gui doesn't appear, and the task bar is the same as above. But the config info in the debug panel shows that the app is running.

# testing 

I have installed all the required version with the requirements.txt file, and tried to update the version of the kivy package (imcompability issue). 

# pc info 

- Cpu: AMD Ryzen 7 6800H with Radeon Graphics   
- GPU：AMD 6600s

**Comment by HackYardo** [comment]
It looks like KG has run but KT not. Is it the first time you run KT?  There are some info at ~/.katrain may helpful, handling errors needs informations.

**Comment by hiuxia** [comment]
No, I have run katrain for months, and it corrupted about a month ago after I upgraded to the latest version. I searched Katrain and kivy log files, nothing find.

**Comment by HackYardo** [comment]
Well, you'd better delete old version then install new version.
And the files of KT are two part: 
1. Program files that can be found by right click KT icon.
2. Config files generated by KT that can be find at C:\Users\YourName\.katrain
if ur operating system is MS Windows.

在 2023-09-15 12:04:32，hiuxia ***@***.***> 写道：


No, I have run katrain for months, and it corrupted about a month ago after I upgraded to the latest version. I searched Katrain and kivy log files, nothing find.

**Comment by hiuxia** [comment]
I don't know what to say and This is very incredible! After deleting all the versions I previously installed and install the newest release, problem solved! 

__________

Besides, I am curious about the reason. When multiple katrain instances installed on the same computer, why it will affect the execution of katrain? Thank you very much for your time and patience.

**Comment by HackYardo** [comment]
@hiuxia Hope u have backup ur sgf files before delete. Can not be overwrite-update is a downside of KT, I don't know why.

**Comment by hiuxia** [comment]
Hahaha, i have my sgf files in other locations and only my original configuration file lost. Thanks very much. Have a good time playing baduk!
> @hiuxia Hope u have backup ur sgf files before delete. Can not be overwrite-update is a downside of KT, I don't know why.
