### ISSUE TITLE
libGL errors

### ISSUE THREAD

**Issue by cdhainaut** [sanderland/katrain#658]
Hi,

My machine runs on linux mint 21.2. I tried installing katrain on a fresh conda environment with python 3.11.4 running pip install katrain.
After a successfull installation, this is what I get when trying to run katrain:

```
libGL error: MESA-LOADER: failed to open iris: /usr/lib/dri/iris_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: iris
libGL error: MESA-LOADER: failed to open iris: /usr/lib/dri/iris_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: iris
libGL error: MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: swrast
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  152 (GLX)
  Minor opcode of failed request:  3 (X_GLXCreateContext)
  Value in failed request:  0x0
  Serial number of failed request:  122
  Current serial number in output stream:  123

```

Any idea ?
Thanks

**Comment by HackYardo** [comment]
I just searched on Internet, it may be caused by integrated gpu and discrete gpu run at the same time. To solve it:
```
$ nvidia-setting
PRIME Profiles
NVIDIA（Performance Mode）
```
if ur gpu comes from Nvidia.

**Comment by siasio** [comment]
> Hi,
> 
> My machine runs on linux mint 21.2. I tried installing katrain on a fresh conda environment with python 3.11.4 running pip install katrain. After a successfull installation, this is what I get when trying to run katrain:
> 
> ```
> libGL error: MESA-LOADER: failed to open iris: /usr/lib/dri/iris_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
> libGL error: failed to load driver: iris
> libGL error: MESA-LOADER: failed to open iris: /usr/lib/dri/iris_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
> libGL error: failed to load driver: iris
> libGL error: MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
> libGL error: failed to load driver: swrast
> X Error of failed request:  BadValue (integer parameter out of range for operation)
>   Major opcode of failed request:  152 (GLX)
>   Minor opcode of failed request:  3 (X_GLXCreateContext)
>   Value in failed request:  0x0
>   Serial number of failed request:  122
>   Current serial number in output stream:  123
> ```
> 
> Any idea ? Thanks

Same issue here

**Comment by nrobinaubertin** [comment]
I think you're missing the [libgl1-mesa-dri](https://packages.ubuntu.com/jammy/libgl1-mesa-dri) package. You can install it with `sudo apt install -y libgl1-mesa-dri`
