### ISSUE TITLE
Rules or methods that implement the next 2 steps at a time

### ISSUE THREAD

**Issue by awsjgy** [sanderland/katrain#659]
Hello Author! I learned that this katrain software of yours can realize different styles of katago, this is awesome. I would like to ask you if there is a way to make a katago that plays 2 moves at a time. Although you can pass, the katago won't really consider the combination that has the best chance of winning after 2 moves, he still trains based on one move!
Because the Chinese game platform, also the world go game platform, has a game that can play 2 moves in a row to support this rule, I don't know if you have a way to solve this problem!

**Comment by sanderland** [comment]
No, this is way out of scope
