### ISSUE TITLE
Katrain v1.14.0 crashes

### ISSUE THREAD

**Issue by Azirine** [sanderland/katrain#661]
Bug report: Katrain v1.14.0 crashes

OS: MacOS 10.15.7

Steps to reproduce:
1. Type 'katrain' in terminal (installed via pip)
2. Load this game https://www.go4go.net/go/games/sgfview/111338
3. Go to move 62
4. Press 'space' (to start analysis)
5. Click on M15 (suggested move)
6. Katrain becomes unresponsive and spinning beachball appears

Note: Crashing behaviour is not limited to this game or this move, but this is an example I was able to reproduce. It tends to happen when clicking on an unexplored move while the engine is analysing. I reproduced this crash 3-4 times in a row before it stopped crashing again.

**Comment by sanderland** [comment]
Can you attach the sgf?

**Comment by Azirine** [comment]
> Can you attach the sgf or link it on a medium without a login page?

This is the file:

[__go4go_20230927_Park-Junghwan_Xu-Haohong.txt](https://github.com/sanderland/katrain/files/12778197/__go4go_20230927_Park-Junghwan_Xu-Haohong.txt)

GitHub doesn't allow attaching sgfs so I changed the extension to .txt, just change it back to .sgf.

**Comment by sanderland** [comment]
Can not reproduce. Do you see any console output?

**Comment by Azirine** [comment]
After crashing 3-4 times, I cannot reproduce the crash again. However, after doing the following, I was able to reproduce the crash again:

1. Quit Katrain
2. backup and then delete ~/.katrain/config.json
3. Start Katrain again

The terminal output is as follows.

After launching katrain:
xxxx-xx-xx xx:xx:xx+xxxx: Analyzing up to 12 positions at a time in parallel
xxxx-xx-xx xx:xx:xx+xxxx: Started, ready to begin handling requests

After loading the game:
[WARNING] Deprecated property "<NumericProperty name=padding_x>" of object "<kivy.uix.label.Label object at 0x1237e17e0>" was accessed, it will be removed in a future version

There is no output at the time of crash. After killing katrain due to the crash:
zsh: killed     katrain
