### ISSUE TITLE
Calculation speed

### ISSUE THREAD

**Issue by megbase1** [sanderland/katrain#665]
Why is the calculation speed of Katrain so puzzling? I have RTX 3060 on with an 18B engine, and the speed is only about 300 moves per second.

**Comment by HackYardo** [comment]
- As far as I know, the speed of Nvidia3060 is 300~400 v/s for sure.
- 18b is a new architecture and slower than 40b and little faster than 60b.
- You can test the max speed of a GPU by `./katago benchmark`.
