### ISSUE TITLE
Can you provide an interface to katrain for training katago from 0（能不能提供一个从0训练katago的接口到katrain ）

### ISSUE THREAD

**Issue by awsjgy** [sanderland/katrain#668]
The Chinese Wildfox Go platform has an exciting way to play the Flying Dagger game, which is to play 2 moves at a time. This game has a luck component, but strength is the key. I've played many games, and those who know how to play can win more than 20 games in a row.
And this flying dagger game is currently updated to elevated play. The highest is knife god>knife fairy>knife saint

I want to train a katago from 0, please there is no tutorial, interested partners + my wechat: wsjgya

中国野狐围棋平台有个飞刀游戏的玩法，很刺激，就是一次下2步。这个游戏虽然有运气成分，但是实力是关键。我玩过很多盘，会玩的可以连胜20多盘。
而且这个飞刀游戏，目前更新到升降级玩法。最高是刀神>刀仙>刀圣

我想训练一个从0开始的katago，请问有没有教程，感兴趣的小伙伴+我微信：wsjgya

**Comment by sanderland** [comment]
This is not a discussion forum, nor a place to get tutorials for other programs.
