### ISSUE TITLE
All available engines are crashing: "cannot open shared object file libssl.so.1.1"

### ISSUE THREAD

**Issue by chandujr** [sanderland/katrain#672]
OS: Nobara Linux v38 (Fedora)

I installed the application using the command `pip3 install -U katrain`. While trying to run the game via Terminal I'm getting this error:

```
Using user config file /home/username/.katrain/config.json
/home/username/.local/lib/python3.11/site-packages/katrain/KataGo/katago: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
ERROR: Engine died unexpectedly without sending output:  status 127
[WARNING] [MTD         ] Unable to open device "/dev/input/event9". Please ensure you have the appropriate permissions.
```

I'm able to see the GUI though:
![Screenshot from 2023-11-30 23-13-02](https://github.com/sanderland/katrain/assets/14921501/77c42302-48ca-47bb-8828-ef860d6bdc0c)

It says `ERROR: Engine died unexpectedly without sending output: status 127`

These are the libraries present in the location (`/home/username/.local/lib/python3.11/site-packages/katrain/KataGo/katago`) mentioned in the error message above:

![Screenshot from 2023-11-30 23-17-10](https://github.com/sanderland/katrain/assets/14921501/decfa219-faab-4212-91e4-d8134ab0c77b)

I tried all these engine options but all are throwing the same error:
![Screenshot from 2023-11-30 23-19-41](https://github.com/sanderland/katrain/assets/14921501/af4d9a3c-0659-412c-9b7c-17585fde6076)

**Comment by Wasja7** [comment]
I had the same problem under Arch Linux and solved by installing the openssl-1.1 package from official repositories. Maybe Fedora has it too? Of course the question remains why katago is not using the provided binary.

**Comment by uwouldntgetit** [comment]
I got this same problem but with a different error message:
`ERROR: Engine died unexpectedly without sending output:  status 127
/home/checkthisout/.local/share/pipx/venvs/katrain/lib/python3.11/site-packages/katrain/KataGo/katago: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
 Exception in thread Thread-3 (_write_stdin_thread):
 Traceback (most recent call last):
   File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
     self.run()
   File "/usr/lib/python3.11/threading.py", line 982, in run
     self._target(*self._args, **self._kwargs)
   File "/home/checkthisout/.local/share/pipx/venvs/katrain/lib/python3.11/site-packages/katrain/core/engine.py", line 360, in _write_stdin_thread
     self.katago_process.stdin.write((json.dumps(query) + "\n").encode())
     ^^^^^^^^^^^^^^^^^^^^^^^^^
 AttributeError: 'NoneType' object has no attribute 'stdin'`
Anyone know how to fix it? btw I'm using manjaro's latest version

**Comment by chandujr** [comment]
I installed openssl v1.1 and this issue is fixed.
