### ISSUE TITLE
Can't install Katrain - require Opengl 2.0

### ISSUE THREAD

**Issue by gofengfeng** [sanderland/katrain#679]
I downloaded the katrain.exe 1.14 for windows. 
when install, error message popped up saying that I have Opengl 1.1, but katrain requires 2.0.
However, I updated my graphic card driver, it is a RTX 2060 and the driver supports Opengl 4.6, but since the installation file can't recognize it, it still think I am on 1.1.

**Comment by ladenol** [comment]
download [OpenGL](https://apps.microsoft.com/detail/9nqpsl29bfff) and install
