### ISSUE TITLE
Engine die unexpectedly without sending output status -6

### ISSUE THREAD

**Issue by huanshanxiaoyao** [sanderland/katrain#680]
How to update general & engine setting  to fix the error:Engine die unexpectedly without sending output status -6

I install katrain by dmg file , macos 

and then brew install katago succesfully 

but I can't use it because of the error above , 

![飞书20240309-222935](https://github.com/sanderland/katrain/assets/17615503/19f57925-50cc-4310-8537-57efa8e3425d)

![飞书20240309-222939](https://github.com/sanderland/katrain/assets/17615503/16b45e17-ef54-4ef8-ab9d-fd605ee0b9bb)

**Comment by nrobinaubertin** [comment]
Could that be [CL_OUT_OF_HOST_MEMORY](https://github.com/lightvector/KataGo/blob/fef845741c6195a482ca38fd5d9843f1acaa2d01/cpp/neuralnet/openclhelpers.cpp#L21) ?

The fact that it says "unexpectedly" suggest to me that the process was killed because your machine ran out of memory.

**Comment by huanshanxiaoyao** [comment]
so what's the needed memory?

**Comment by nrobinaubertin** [comment]
It will depend on a lot of factors, like the number of threads spawned. Katrain is supposed to run a benchmark when you first start it to adjust the parameters.  
You can manually adjust [the file](https://github.com/sanderland/katrain/blob/master/katrain/KataGo/analysis_config.cfg).

Here are two issues from the katago repository that may interest you:
- https://github.com/lightvector/KataGo/issues/756
- https://github.com/lightvector/KataGo/issues/303

It seems that there is an ongoing memory leak, so the longer the analysis, the more memory it will use. That's unfortunate.

On my machine, with my settings (the default ones, using katago-v1.13.0-eigenavx2-linux-x64 and the latest 18b model) it is using around 6.4GB while playing against itself

**Comment by eavesz** [comment]
Same issue. It's not because of memory. The brew version of katago can work with lizzieyzy correctly.

**Comment by nrobinaubertin** [comment]
I wonder where this `-6` return code comes from then. Because that's the only one I can see in katago's code (and there's nothing like it in katrain from a rapid search)
