### ISSUE TITLE
Can not import BaseFlatButton

### ISSUE THREAD

**Issue by zhimakaimenxa** [sanderland/katrain#681]
# I have a bug report

Katrain version: 1.18
Kivy version: 3.0
KivyMD version: 2.0.7
Python version: 3.12
OS version: win10

When I try to run katrain.py in vscode in debug mode, I get the following error:

> Exception has occurred: ImportError
> cannot import name 'BaseFlatButton' from 'kivymd.uix.button' (c:\Python312\Lib\site-packages\kivymd\uix\button\__init__.py)
>   File "C:\Users\qibo1\Downloads\katrain-master\katrain-master\katrain\gui\kivyutils.py", line 26, in <module>
>     from kivymd.uix.button import BaseFlatButton, BasePressedButton
>   File "C:\Users\qibo1\Downloads\katrain-master\katrain-master\katrain\gui\popups.py", line 46, in <module>
>     from katrain.gui.kivyutils import (
>   File "C:\Users\qibo1\Downloads\katrain-master\katrain-master\katrain\__main__.py", line 82, in <module>
>     from katrain.gui.popups import (
>   File "C:\Users\qibo1\Downloads\katrain-master\katrain-master\katrain.py", line 2, in <module>
>     from katrain.__main__ import run_app
> ImportError: cannot import name 'BaseFlatButton' from 'kivymd.uix.button' (c:\Python312\Lib\site-packages\kivymd\uix\button\__init__.py)

Waiting for your repsonse.

Thanks in advance

Zhimakaimenxa

**Comment by sanderland** [comment]
You can see the requirements in requirements.txt - installing breaking version changes is, well, likely to break

**Comment by zhimakaimenxa** [comment]
Yes, after I downgrade the KivyMD to 0.104, the code can run now.

Thanks a lot.
