### ISSUE TITLE
Two different Katago networks?

### ISSUE THREAD

**Issue by DacC2605** [sanderland/katrain#687]
Hello! As a matter of fact I only couldn't find the answer to the following question: **can two different Katago networks be paired to play in Katrain** (1.14)? As in Sabaki for instance... And if yes, how? If not, yes, I register it as a feature, even if I understand that it will probably not be done ever. Sorry for my silly question. Thank you for all!

**Comment by sanderland** [comment]
No, it's outside the intended use (many people on the computer go discord have their own tools for testing performance anyway) and would make a complicated part of settings even more complicated.
