### ISSUE TITLE
The problem with having more than one Katrain

### ISSUE THREAD

**Issue by hope366** [sanderland/katrain#69]
Hello.
If you have two versions of the same Katrain in different locations, such as a standalone Katrain and the Katrain that comes with the megapack, changing the settings of one also seems to affect the other.

Is this some kind of mistake on my part? Or was it intentionally made that way from the beginning?

**Comment by sanderland** [comment]
This was introduced in 1.1 to not reset settings on every release and allow for the single-exe distribution.  You can specify the config file as a command line argument if you really want to.
.. but really though, if you can install the main release, using the megapack version seems unnecessary.

**Comment by hope366** [comment]
Thank you for your prompt response as before.
Sharing your settings? and was somewhat confused by the relative path, but I now use the absolute path.
Thank you.

**Comment by hope366** [comment]
I'm not very knowledgeable about computers, so I'm going to use "allow for the single-exe distribution." was hard to understand, but maybe I understand it now. I will.
I interpreted this to mean that when there are multiple executables on the same PC, it is more convenient for each to run with the same rules (settings).
Is this correct?

**Comment by sanderland** [comment]
> 
> 
> I'm not very knowledgeable about computers, so I'm going to use "allow for the single-exe distribution." was hard to understand, but maybe I understand it now. I will.
> I interpreted this to mean that when there are multiple executables on the same PC, it is more convenient for each to run with the same rules (settings).
> Is this correct?

There are windows release as a 'zip' file and an 'exe' file.
The exe file works by unzipping itself to a temporary location and running there - as a result the config file would be thrown away every time!

**Comment by hope366** [comment]
I'm Japanese and I've had some sleep since then, so I'm late in replying. I'm sorry for the delay.
I used to unzip KaTrain.zip and use it, now I'm using KaTrainNC.exe I tried it. When I launched it, my existing Katrain settings were applied.
KaTrainNC.exe can be used directly without the need to decompress it, but there is also a Is there a difference between KaTrain.zip and KaTrain.zip?

**Comment by hope366** [comment]
The translation didn't seem to work.
>between KaTrain.zip and KaTrain.zip?
This was a mistake.

Regarding KaTrainNC.exe and KaTrain.zip, you need to decompress them before you can use them. Is there any other difference between the two?
That's what I wanted to ask you about.

**Comment by hope366** [comment]
＞the config file would be thrown away every time!
That means that whatever is stored in (your user directory/.katrain) will be stored in So it's an absolute setting and it applies to everything?

**Comment by hope366** [comment]
＞the config file would be thrown away every time!
The configuration would be thrown away every time, but you will find your changes in (your user directory/. katrain) and will be applied to all other executables.

**Comment by hope366** [comment]
https://github.com/sanderland/katrain/ releases
Read this carefully and made sure that the modified configuration file is in "your user directory/. katrain".

**Comment by hope366** [comment]
This means that if you have multiple Katrains and you want to use them in different settings, you can use For example, you can add the config.jason of
"config-org.jason", "config-mega.jason", etc. Then copy them and place them in the "C:Users\\ user name\.katrain" and add them to any When you start Katrain, you can add the corresponding "config-##.jason" to It seems that you can change it to "config.jason".
It seems to go against the grain when you're allowing single-executives to be released, but it's fun to try things out.

Translated with www.DeepL.com/Translator (free version)

**Comment by sanderland** [comment]
> The translation didn't seem to work.
> 
> > between KaTrain.zip and KaTrain.zip?
> > This was a mistake.
> 
> Regarding KaTrainNC.exe and KaTrain.zip, you need to decompress them before you can use them. Is there any other difference between the two?
> That's what I wanted to ask you about.

The single .exe file is a bit slower to start than the one in the zip file, that is all.

**Comment by hope366** [comment]
Sorry for prolonging the process.
I finally understand that the settings are managed centrally in "C: Users \ user name\katrain.
I'll end it now.
Thank you very much.
