### ISSUE TITLE
Bulk stones insertion and removal

### ISSUE THREAD

**Issue by jcguu95** [sanderland/katrain#717]
# feature request

It would be great if we could remove stones in bulk, for instance, by dragging to select and carve out a rectangle around the stones we want to remove. This feature would be especially helpful when using AI to review our Go game and recreate similar scenarios, allowing us to see if the AI's responses differ significantly.

**Comment by sanderland** [comment]
There is a very old closed issue for deleting stones. It's actually quite difficult with the current setup, and I don't have capacity for that level of rewrites.
