### ISSUE TITLE
v1.15 windows download gets flagged for containing a virus

### ISSUE THREAD

**Issue by linoba** [sanderland/katrain#719]
Downloading https://github.com/sanderland/katrain/releases/download/v1.15.0-fix/KaTrain-Windows.zip shows a virus warning. The next older version does not.

![image](https://github.com/user-attachments/assets/a24f85f0-bf50-432d-8444-3354a49a6b48)

Sounds bad enough not to try ...

Tested with firefox 131 and windows 11.

**Comment by sanderland** [comment]
bugs in your virus scanner should be reported to them
