### ISSUE TITLE
Feature Request: Endgame practice mode

### ISSUE THREAD

**Issue by Chewt** [sanderland/katrain#724]
# I have a feature request

This is a a big feature request, so I don't actually expect anyone to work on this. I am planning on attempting this in a fork and submitting a PR if I accomplish it, but I understand if this is too big of a change.

Anyway, here is the idea: a way to practice endgame on existing sgf files. 

I definitely lack endgame skills, and I think it would be nice to have an interactive mode where it starts at the endgame of a loaded sgf, and has you play out endgame sequences in order of largest to smallest. I'm imagining this to be similar to the teaching game mode, where it could be calibrated to allow some inaccuracies depending on skill level.

**Comment by sanderland** [comment]
Way out of scope, but maybe [shape](https://github.com/sanderland/shape) can help?
