### ISSUE TITLE
feature request: edit keyboard shortcuts

### ISSUE THREAD

**Issue by lj739** [sanderland/katrain#75]
Where is the AI move button?

**Comment by sanderland** [comment]
in the analysis options menu. or press enter

**Comment by lj739** [comment]
Enter key is not convenient to press, I prefer to space key, how to change it? A button is the most convenient way, please add it back in the next version.
 



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "sanderland"<notifications@github.com&gt;; 
发送时间: 2020年6月16日(星期二) 晚上8:31
收件人: "sanderland/katrain"<katrain@noreply.github.com&gt;; 
抄送: "费而隐"<909417887@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [sanderland/katrain] The most useful button is gone. (#75)





 
in the analysis options menu. or press enter

**Comment by sanderland** [comment]
editing keyboard shortcuts is not a priority, but feel free to PR such an edit settings screen if you really want it.

**Comment by lj739** [comment]
I've&nbsp; retrieved back to 1.06.&nbsp;
 



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "sanderland"<notifications@github.com&gt;; 
发送时间: 2020年6月16日(星期二) 晚上10:58
收件人: "sanderland/katrain"<katrain@noreply.github.com&gt;; 
抄送: "费而隐"<909417887@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [sanderland/katrain] feature request: edit keyboard shortcuts (#75)





 
editing keyboard shortcuts is not a priority, but feel free to PR such an edit settings screen if you really want it.
