### ISSUE TITLE
Exception when using touch screen

### ISSUE THREAD

**Issue by owenwp** [sanderland/katrain#84]
When using a touch screen on a Windows device to play a move or click on any UI element, the click fails to register and the info pane shows "ERROR: Exception AttributeError: "'WM_MotionEvent' object has no attribute 'button'" in base.py line 334.

**Comment by sanderland** [comment]
could you post the entire stack trace?

**Comment by owenwp** [comment]
![image](https://user-images.githubusercontent.com/229827/85216907-55156b00-b33f-11ea-8f43-7ad75065baf2.png)

**Comment by sanderland** [comment]
should be fixed in v1.2.1 - I don't have a touch screen so i'd appreciate if you can confirm this using https://sharefiles.app/download/c985d21717f789fb898253c11d979bf9b80dba37

**Comment by owenwp** [comment]
Thanks, that fixed playing moves and opening the menu, but the bug is still there for the pass/undo buttons and the menu options like new game. 
![image](https://user-images.githubusercontent.com/229827/85227675-c67f0900-b393-11ea-93c1-65244a56a828.png)

**Comment by sanderland** [comment]
One more try then:
https://sharefiles.app/download/ef190c86fb96e43b825e6975893a325d57ad6a3e

**Comment by owenwp** [comment]
Looks good, thanks.
