### ISSUE TITLE
Downloading models isn't working on my mac

### ISSUE THREAD

**Issue by castal** [sanderland/katrain#89]
I just installed 1.2.1 and tried out the "Download Models" command. I am not seeing the progress percentages shown in your 1.2.1 graphic, and I am not seeing any activity in the destination directory. After a while I clicked on the "Download Models" button again, and it seems to have tried to run another download session in parallel.
<img width="1237" alt="Screen Shot 2020-06-21 at 2 51 08 PM" src="https://user-images.githubusercontent.com/9596277/85234225-863e7b80-b3d1-11ea-920c-914cddabf1fc.png">

I was, however, able to download the new 20-block model directly from the katago releases page, so it shouldn't be a network problem.

**Comment by sanderland** [comment]
openssl fix added to readme and better errors in v1.2.2
