### ISSUE TITLE
SGF editing features

### ISSUE THREAD

**Issue by SylvainNZ** [sanderland/katrain#92]
I thought it would be quite handy to be able to remove a variation.
'Right-click on the move > Cut' would feel a very natural way of doing this.

Now I know it's easy to say and not so easy to implement but anyway I thought that would be a nice feature to have.

**Comment by sanderland** [comment]
don't you end up in an area where you then want all the sgf editor features?

**Comment by SylvainCME** [comment]
that would be great indeed

**Comment by SylvainNZ** [comment]
yes, I guess that would be best to include 'basic' sgf editing features at least.
I am actively using Katrain at the moment and I did notice that would be quite useful.

**Comment by sanderland** [comment]
I'll put this as help wanted to indicate that I'd happily include the feature, but it's not my priority to implement myself for now.

**Comment by sanderland** [comment]
![delete](https://user-images.githubusercontent.com/48946947/87345558-86edac00-c550-11ea-9ba2-792f50316248.gif)
How does this look @SylvainNZ @rollinghills ?
Check out the v1.3.2 branch to test

**Comment by rollinghills** [comment]
Unbelievable. You wrote a program that´s simply outstanding. Thank you so much!

Where can I donate?

**Comment by sanderland** [comment]
@rollinghills the "sponsor" heart link at the top has the options: github sponsors or liberapay.  thanks! :)

**Comment by SylvainNZ** [comment]
Damn, you're a legend ! This is exactly what I was hoping for.
I haven't had time to test it yet but thats what I imagined.
It makes navigation in the tree easier.

**Comment by SylvainNZ** [comment]
I managed to install from the repo :)
The tree edition and the sgf output worked perfectly with my tests. Awesome job

**Comment by sanderland** [comment]
great, thanks for testing, I'll wrap this up in a v1.3.2 release soon then

**Comment by rollinghills** [comment]
OK, I just made a monthly donation, I hope it works. Outerwise, please let me know 

One question: Fore some reason I´m not able to start the clock. It never counts down.

All the best

 

Matthias

 

Von: sanderland <notifications@github.com> 
Gesendet: Montag, 13. Juli 2020 21:45
An: sanderland/katrain <katrain@noreply.github.com>
Cc: rollinghills <info@matthiasrichter.de>; Mention <mention@noreply.github.com>
Betreff: Re: [sanderland/katrain] SGF editing features (#92)

 

@rollinghills <https://github.com/rollinghills>  the "sponsor" heart link at the top has the options: github sponsors or liberapay. thanks! :)

**Comment by sanderland** [comment]
> One question: Fore some reason I´m not able to start the clock. It never counts down. 

As long as (a) it's a human's turn (b) you're in play mode (c) you clicked the pause button to start it, it should work. are all those true?

**Comment by sanderland** [comment]
@rollinghills I didn't see it show up, so maybe something went wrong or it takes some time,

In any case, closing the issue as it's now released in v1.3.2
