### ISSUE TITLE
No sound

### ISSUE THREAD

**Issue by Arborescent** [sanderland/katrain#95]
I get this error upon startup: 
```
[CRITICAL] [AudioSDL2   ] Unable to open mixer: b'No such audio device'
[WARNING] [AudioSDL2   ] Unable to load /usr/local/lib/python3.8/dist-packages/katrain/beep.wav: b"Audio device hasn't been opened"
```

I am using pulseaudio.
If I start katrain using `padsp katrain`, the error goes away, but the audio issue remains.

**Comment by sanderland** [comment]
I am getting the same on linux, as well as font problems in Korean. Unfortunately this is a case of kivy shipping with unstable/misconfigured backends and then blaming said backends.
e.g. https://github.com/kivy/kivy/issues/6601
KIVY_AUDIO=[some other backend] as described here: https://kivy.org/doc/stable/guide/environment.html might work

**Comment by pythonic64** [comment]
SDL2 as audio provider works for me on Linux 18, but you have install Kivy from source. Ensure that you have `libpulse` and kivy deps installed first and then run:

`pip install git+https://github.com/kivy/kivy.git@2.0.0rc3`

**Comment by sanderland** [comment]
improved workarounds/installation instructions for linux in 1.3
