### ISSUE TITLE
Hidden UI widgets

### ISSUE THREAD

**Issue by Arborescent** [sanderland/katrain#96]
If you unfocus the katrain window during initialization, and then focus it again, many UI widgets get hidden.

![image](https://user-images.githubusercontent.com/66987221/85452384-aeec7f80-b54f-11ea-9e9d-7be4f0ea10a4.png)

In the screenshot, note how the top menu is not visible.

**Comment by sanderland** [comment]
you probably hit '~' or 'm' which are shortcuts for cycling through UI modes

**Comment by sanderland** [comment]
ensured those shortcuts do not work when control is pressed in 1.3
