### ISSUE TITLE
Client not opening on MacOS

### ISSUE THREAD

**Issue by pcorey** [sanderland/katrain#98]
Hi, I'm having some trouble getting katrain running on MacOS. I've followed the [installation instructions](https://github.com/sanderland/katrain/blob/master/INSTALL.md#MacPrereq) (`brew install katago && pip3 install katrain`). When I try to run `katrain` in my terminal, it seems to fire up katago, but the katrain UI never pops up. I'm just left in the terminal with the following output:

```
➜  ~ katrain
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
[WARNING] [Deprecated  ] Pygame has been deprecated and will be removed after 1.11.0: Call to deprecated function __init__ in /usr/local/lib/python3.7/site-packages/kivy/core/window
/window_pygame.py line 42.Called from /usr/local/lib/python3.7/site-packages/kivy/core/__init__.py line 70 by core_select_lib().
Using user config file /Users/pcorey/.katrain/config.json
[WARNING] [Deprecated  ] Pygame has been deprecated and will be removed after 1.11.0: Call to deprecated function __init__ in /usr/local/lib/python3.7/site-packages/kivy/core/text/t
ext_pygame.py line 36.Called from /usr/local/lib/python3.7/site-packages/kivy/uix/label.py line 349 by _create_label().
[WARNING] [Audio       ] Unable to find a loader for </usr/local/lib/python3.7/site-packages/katrain/beep.wav>
[WARNING] [Deprecated  ] Pygame has been deprecated and will be removed after 1.11.0: Call to deprecated function __init__ in /usr/local/lib/python3.7/site-packages/kivy/core/text/t
ext_pygame.py line 36.Called from /usr/local/lib/python3.7/site-packages/kivy/core/text/markup.py line 94 by __init__().
2020-06-24 09:16:31-0600: Analysis Engine starting...
2020-06-24 09:16:31-0600: KataGo v1.4.5
2020-06-24 09:16:31-0600: nnRandSeed0 = 15176681108110430856
2020-06-24 09:16:31-0600: After dedups: nnModelFile0 = /usr/local/lib/python3.7/site-packages/katrain/models/g170e-b15c192-s1672170752-d466197061.bin.gz useFP16 auto useNHWC auto
[WARNING] [Deprecated  ] Pygame has been deprecated and will be removed after 1.11.0: Call to deprecated function __init__ in /usr/local/lib/python3.7/site-packages/kivy/core/text/t
ext_pygame.py line 36.Called from /usr/local/lib/python3.7/site-packages/kivy/uix/textinput.py line 2252 by _get_line_options().
[WARNING] [Deprecated  ] Pygame has been deprecated and will be removed after 1.11.0: Call to deprecated function __init__ in /usr/local/lib/python3.7/site-packages/kivy/core/text/t
ext_pygame.py line 36.Called from /usr/local/lib/python3.7/site-packages/katrain/gui/kivyutils.py line 504 by draw_text().
2020-06-24 09:16:32-0600: Found OpenCL Platform 0: Apple (Apple) (OpenCL 1.2 (Sep  5 2019 21:59:08))
2020-06-24 09:16:32-0600: Found 2 device(s) on platform 0 with type CPU or GPU or Accelerator
2020-06-24 09:16:32-0600: Found OpenCL Device 0: Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz (Intel) (score 102)
2020-06-24 09:16:32-0600: Found OpenCL Device 1: Intel(R) Iris(TM) Graphics 6100 (Intel Inc.) (score 6000102)
2020-06-24 09:16:32-0600: Creating context for OpenCL Platform: Apple (Apple) (OpenCL 1.2 (Sep  5 2019 21:59:08))
2020-06-24 09:16:32-0600: Using OpenCL Device 1: Intel(R) Iris(TM) Graphics 6100 (Intel Inc.) OpenCL 1.2
2020-06-24 09:16:32-0600: Loaded tuning parameters from: /Users/pcorey/.katago/opencltuning/tune6_gpuIntelRIrisTMGraphics6100_x19_y19_c192_mv8.txt
2020-06-24 09:16:42-0600: Loaded config /usr/local/lib/python3.7/site-packages/katrain/KataGo/analysis_config.cfg
2020-06-24 09:16:42-0600: Loaded model /usr/local/lib/python3.7/site-packages/katrain/models/g170e-b15c192-s1672170752-d466197061.bin.gz
2020-06-24 09:16:42-0600: OpenCL backend: Model version 8
2020-06-24 09:16:42-0600: OpenCL backend: Model name: g170-b15c192-s1672170752-d466197061
2020-06-24 09:16:42-0600: Analyzing up to 12 positions at at time in parallel
2020-06-24 09:16:42-0600: Started, ready to begin handling requests
```

I've tried forcing it to render something with the `-f` flag, but that just seems to change my resolution and keep me in the terminal.

Here are the Python3 and Katago versions I'm running:

```
➜  ~ python3 --version
Python 3.7.5
➜  ~ katago version
KataGo v1.4.5
Git revision: <omitted>
Compile Time: Jun 21 2020 20:20:57
Using OpenCL backend
```

Any ideas what's going on? Did I miss something?

**Comment by sanderland** [comment]
Can you pip list

**Comment by pcorey** [comment]
@sanderland 

```
➜  ~ pip3 list
Package            Version
------------------ ---------
beautifulsoup4     4.8.1
certifi            2020.6.20
chardet            3.0.4
Cython             0.29.14
docutils           0.16
idna               2.9
importlib-metadata 1.3.0
KaTrain            1.2.2
keyring            20.0.0
Kivy               2.0.0rc3
Kivy-Garden        0.1.4
kivymd             0.104.1
lxml               4.4.2
more-itertools     8.0.2
ofxclient          2.0.3
ofxhome            0.3.3
ofxparse           0.20
Pillow             7.1.2
pip                19.3.1
pygame             1.9.6
Pygments           2.6.1
requests           2.24.0
setuptools         41.6.0
six                1.13.0
soupsieve          1.9.5
urllib3            1.25.9
wheel              0.33.6
zipp               0.6.0
```

**Comment by sanderland** [comment]
this is very strange indeed. Could you find debug_level in /Users/pcorey/.katrain/config.json and set it to 2 before trying again? this should result in a loooong wall of text.

you could also try

`KIVY_WINDOW=sdl2 katrain`

**Comment by pcorey** [comment]
So it seems like there are a few things going on. I was running `katrain` from within a fullscreen iTerm2 instance. I tried running it from a windowed iTerm2, and `katrain` did pop up in the background. But it seems like it's not fully instantiating a window, as I can't cmd+tab to it, or find it in the dock.

If I run `katrain` from a windowed version of Terminal, it creates a full window that I can cmd+tab to. Unfortunately, it looks like it's not taking into account my laptop's retina display pixel density when rendering the UI. Strangely, mouse clicks _are_ respecting the pixel density, so to open the hamburger menu, I need to click in the grey void at the top left of the window, not on the actual hamburger menu.

<img width="1348" alt="Screen Shot 2020-06-24 at 3 00 59 PM" src="https://user-images.githubusercontent.com/3384035/85627470-c7ca6300-b62b-11ea-9654-0b49c1051d53.png">

[Here's `katrain` running in iTerm2 with `debug_level` set to `2`.](https://gist.github.com/pcorey/831a194b7e83418404b4169ee7392098)

**Comment by sanderland** [comment]
I don't see any errors, I presume the trace at the end is from you hitting ctrl-c and seems normal for that.
@tshirtman suggested to another user that this seems related to https://github.com/kivy/kivy/pull/6289 - but I don't know why this was never merged in over a year despite being quite a critical bug. The only suggestion I heard was about whether said user had two screens attached, one retina and one non-retina -- do you?

**Comment by pcorey** [comment]
@sanderland No, I'm just running a single. That's a shame about the kivy bug. It sounds like this is an upstream issue, so feel free to close this. Thanks for looking into it for me.

**Comment by sanderland** [comment]
Filed upstream as https://github.com/kivy/kivy/issues/6968
